import { Continent } from '../../../common/continent.enum';
import type { CountrySeed } from '../country.seed-data';

/**
 * Amerika kıtası (Kuzey + Güney) — dünya haritası base-data seed (35 ülke). Structured fields only; the
 * narrative prose fields (introTr/landformNoteTr/climateNoteTr/hydrographyNoteTr) are
 * seeded null and filled in later regional content waves. populationYear is null across
 * the board (world-scale ruling, DEC 2026-07-13). Source of record:
 * Owner's Inbox/dunya-haritasi-base-data/americas.md. Every value transcribed from the
 * approved research; slugs generated by an ASCII/Turkish-fold rule (matches the pilot).
 * nameTr uses the source "kısa" (short) name; where the bare short form is ambiguous the
 * official name is kept (ABD → "Amerika Birleşik Devletleri"). Danimarka (DK) / Fransa
 * (FR) appear only as overseas-territory parents in the source notes (Grönland, Fransız
 * Guyanası) and are seeded in the Europe lane, not here.
 */
export const AMERICAS_COUNTRIES: readonly CountrySeed[] = [
  {
    isoCode: 'CA',
    isoCodeAlpha3: 'CAN',
    nameTr: 'Kanada',
    nameEn: 'Canada',
    slugTr: 'kanada',
    slugEn: 'canada',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Kuzey Amerika',
    population: 41_651_653,
    populationYear: null,
    areaKm2: 8_788_700,
    capitalNameTr: 'Ottava',
    capitalNameEn: 'Ottawa',
    capitalLatitude: 45.4215,
    capitalLongitude: -75.6972,
    neighborIsoCodes: ['US', 'DK'],
    officialLanguagesTr: ['İngilizce', 'Fransızca'],
    currencyNameTr: 'Kanada Doları',
    currencyCode: 'CAD',
    governmentFormTr: 'Federal parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr:
      "Federasyon 1 Temmuz 1867'de kuruldu; tam bağımsızlık kademeli (1931 Westminster, 1982 Kanada Yasası).",
  },
  {
    isoCode: 'US',
    isoCodeAlpha3: 'USA',
    nameTr: 'Amerika Birleşik Devletleri',
    nameEn: 'United States',
    slugTr: 'amerika-birlesik-devletleri',
    slugEn: 'united-states',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Kuzey Amerika',
    population: 341_784_857,
    populationYear: null,
    areaKm2: 9_147_420,
    capitalNameTr: 'Vaşington',
    capitalNameEn: 'Washington, D.C.',
    capitalLatitude: 38.9072,
    capitalLongitude: -77.0369,
    neighborIsoCodes: ['CA', 'MX'],
    officialLanguagesTr: null,
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "4 Temmuz 1776'da bağımsızlığını ilan etti (İngiltere'nin tanıması 1783 Paris Antlaşması).",
    introTr:
      'Kuzey Amerika kıtasının büyük bölümünü kaplayan Amerika Birleşik Devletleri, Atlantik ve ' +
      'Pasifik okyanuslarına birden kıyısı olan, elli eyaletten oluşan federal bir ' +
      "cumhuriyettir; kıtadaki tek iki kara komşusu Kanada ve Meksika'dır.",
    landformNoteTr:
      "Ülkenin batısına Kuzey Amerika'nın en büyük sıradağı olan Kayalık Dağları hakimdir; " +
      "Alaska'daki 6.190 metrelik Denali, ülkenin ve kıtanın en yüksek noktasıdır (kıtasal 48 " +
      "eyalette en yüksek nokta ise Kaliforniya'daki 4.421 metrelik Mount Whitney'dir). Pasifik " +
      'kıyısı boyunca Cascade ve Kıyı Sıradağları uzanır. Ülkenin ortasını, ortalama 300 metre ' +
      'yükseklikte, geniş prerilerden oluşan Büyük Ovalar kaplar; bu düzlük 2.000 kilometreden ' +
      "uzun bir alana yayılır. Doğuda, Kanada'dan Alabama'ya kadar uzanan Appalaş Dağları, " +
      'genellikle 1.800 metrenin altında kalan, yaşlı ve aşınmış bir sıradağdır.',
    climateNoteTr:
      'Enlem, denizden uzaklık ve dağların yarattığı yağış gölgesi etkisi, iklimi bölgeden ' +
      'bölgeye keskin biçimde farklılaştırır. Doğu kıyısında ve iç kesimlerde (Orta Batı, Büyük ' +
      'Göller, Yeni İngiltere) dört mevsimin belirgin yaşandığı nemli karasal bir iklim ' +
      "egemendir; güneydoğuda, Florida'ya kadar uzanan kesimde ise sıcak-nemli subtropikal bir " +
      "iklime geçilir. Büyük Ovalar'ın batı kesimi yarı-kurak bir karaktere sahiptir. " +
      'Güneybatıda, Arizona ve Nevada gibi eyaletlerde sıcak ve düşük yağışlı bir çöl iklimi ' +
      'görülür. Pasifik kıyısında ise kuzeyden güneye geçiş belirgindir — Oregon ve ' +
      "Washington'da nemli bir deniz iklimi, Kaliforniya kıyısında ise yazı kurak, kışı yağışlı " +
      'bir Akdeniz iklimi hakimdir. Alaska büyük ölçüde subarktik ve tundra iklimi altındayken, ' +
      'Hawaii adaları tropikal bir iklime sahiptir.',
    hydrographyNoteTr:
      "Ülkenin en uzun nehri, Montana'da doğup Mississippi'ye katılan 3.767 kilometrelik " +
      "Missouri'dir; Mississippi Nehri'yle birleşerek dünyanın dördüncü en büyük nehir " +
      "sistemini oluşturur. Mississippi, Minnesota'dan Meksika Körfezi'ne kadar 3.766 kilometre " +
      "boyunca ülkeyi kuzeyden güneye kat eder. Colorado Nehri, Kayalık Dağları'ndan doğarak " +
      "2.334 kilometre boyunca güneybatıyı kat eder ve Kaliforniya Körfezi'ne ulaşır." +
      '\n\n' +
      'Kuzeyde, Büyük Göller sistemi — Superior, Michigan, Huron, Erie ve Ontario — dünyanın en ' +
      "büyük tatlı su kaynaklarından birini oluşturur; Michigan Gölü dışındaki dördü Kanada'yla " +
      'paylaşılır.',
  },
  {
    isoCode: 'MX',
    isoCodeAlpha3: 'MEX',
    nameTr: 'Meksika',
    nameEn: 'Mexico',
    slugTr: 'meksika',
    slugEn: 'mexico',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 131_946_900,
    populationYear: null,
    areaKm2: 1_943_950,
    capitalNameTr: 'Meksika Şehri',
    capitalNameEn: 'Mexico City',
    capitalLatitude: 19.4326,
    capitalLongitude: -99.1332,
    neighborIsoCodes: ['US', 'BZ', 'GT'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Meksika Pesosu',
    currencyCode: 'MXN',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "16 Eylül 1810'da bağımsızlık mücadelesi başladı (resmî millî gün); İspanya'nın tanıması 1821.",
    introTr:
      "Kuzey Amerika'nın güneyinde yer alan Meksika, kuzeyde ABD, güneydoğuda Belize ve " +
      "Guatemala ile komşudur. Batıda Büyük Okyanus'a, doğuda Meksika Körfezi ve Karayip " +
      "Denizi'ne kıyısı vardır. Ülkenin kuzeybatısındaki Baja California ve " +
      'güneydoğusundaki Yucatán, birbirinden çok farklı iki yarımadadır — biri kurak ve ' +
      'dağlık, diğeri düz ve ormanlık kireçtaşı bir plato.',
    landformNoteTr:
      "Orta plato'yu doğu ve batıdan çevreleyen Sierra Madre Occidental (~1.250 km) ve " +
      "Sierra Madre Oriental (~1.000 km), Meksika'nın ana dağ sistemini oluşturur. Bu iki " +
      "sıradağ, Mexico City'nin doğusunda, doğu-batı doğrultulu Trans-Meksika Volkanik " +
      "Kuşağı'yla birleşir; ülkenin en yüksek üç zirvesi de bu kuşaktadır. En yükseği, " +
      "5.636 metreyle Kuzey Amerika'nın en yüksek volkanı olan Pico de Orizaba'dır; onu " +
      '5.393 metrelik hâlâ aktif Popocatépetl ve 5.230 metrelik Iztaccíhuatl izler. ' +
      'Güneydoğuda, Yucatán Yarımadası bunların hiçbirine benzemez: düz, alçak bir ' +
      'kireçtaşı plato olan bu bölgede yüzey nehri neredeyse yoktur, su büyük ölçüde ' +
      "yeraltından akar ve çökme çukurları olan cenote'leri besler.",
    climateNoteTr:
      "Yengeç Dönencesi Meksika'yı kabaca iki iklim kuşağına böler; kuzey daha kurak, " +
      'güney daha nemli ve tropikaldir. Baja California, batı Sonora ve orta platonun ' +
      'kuzey kesimi çöl ya da yarı çöl iklimindedir, yıllık yağış çoğu yerde 250 ' +
      'milimetrenin altında kalır. Rakım da en az enlem kadar belirleyicidir: 900 ' +
      'metrenin altındaki tierra caliente sıcak ve nemli geçer, 900-1.800 metre ' +
      'arasındaki tierra templada ılıman bir iklim sunar; 1.800 metrenin üzerindeki ' +
      'tierra fría ise serin ve kurak geçer — 2.240 metre yükseklikteki Mexico City de ' +
      'bu üst kuşaktadır.',
    hydrographyNoteTr:
      "Kuzeyde Rio Bravo (ABD'de Rio Grande), yaklaşık 3.000 kilometrelik uzunluğunun " +
      '2.000 kilometrelik bölümünde Meksika ile ABD arasındaki sınırı çizer ve Meksika ' +
      "Körfezi'ne dökülür. Meksika platosunda doğan 750 kilometrelik Lerma Nehri, " +
      "ülkenin en büyük gölü olan Chapala Gölü'ne akar. Güneydoğuda Usumacinta Nehri, " +
      "Guatemala sınırından geçerek Meksika Körfezi'ne ulaşır; Guatemala'daki kaynak " +
      "kollarıyla birlikte toplam uzunluğu yaklaşık 1.000 kilometredir. Yucatán'da ise " +
      "yüzey nehri yerine cenote'ler ve yeraltı su sistemleri hakimdir.",
  },
  {
    isoCode: 'BZ',
    isoCodeAlpha3: 'BLZ',
    nameTr: 'Belize',
    nameEn: 'Belize',
    slugTr: 'belize',
    slugEn: 'belize',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 422_924,
    populationYear: null,
    areaKm2: 22_810,
    capitalNameTr: 'Belmopan',
    capitalNameEn: 'Belmopan',
    capitalLatitude: 17.251,
    capitalLongitude: -88.759,
    neighborIsoCodes: ['MX', 'GT'],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Belize Doları',
    currencyCode: 'BZD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "21 Eylül 1981'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'CR',
    isoCodeAlpha3: 'CRI',
    nameTr: 'Kosta Rika',
    nameEn: 'Costa Rica',
    slugTr: 'kosta-rika',
    slugEn: 'costa-rica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 5_152_950,
    populationYear: null,
    areaKm2: 51_060,
    capitalNameTr: 'San Hose',
    capitalNameEn: 'San José',
    capitalLatitude: 9.9281,
    capitalLongitude: -84.0907,
    neighborIsoCodes: ['NI', 'PA'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Kosta Rika Kolonu',
    currencyCode: 'CRC',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
  },
  {
    isoCode: 'SV',
    isoCodeAlpha3: 'SLV',
    nameTr: 'El Salvador',
    nameEn: 'El Salvador',
    slugTr: 'el-salvador',
    slugEn: 'el-salvador',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 6_365_503,
    populationYear: null,
    areaKm2: 20_720,
    capitalNameTr: 'San Salvador',
    capitalNameEn: 'San Salvador',
    capitalLatitude: 13.6929,
    capitalLongitude: -89.2182,
    neighborIsoCodes: ['GT', 'HN'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
  },
  {
    isoCode: 'GT',
    isoCodeAlpha3: 'GTM',
    nameTr: 'Guatemala',
    nameEn: 'Guatemala',
    slugTr: 'guatemala',
    slugEn: 'guatemala',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 18_687_881,
    populationYear: null,
    areaKm2: 107_160,
    capitalNameTr: 'Guatemala',
    capitalNameEn: 'Guatemala City',
    capitalLatitude: 14.6349,
    capitalLongitude: -90.5069,
    neighborIsoCodes: ['MX', 'BZ', 'HN', 'SV'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Guatemala Ketzali',
    currencyCode: 'GTQ',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
  },
  {
    isoCode: 'HN',
    isoCodeAlpha3: 'HND',
    nameTr: 'Honduras',
    nameEn: 'Honduras',
    slugTr: 'honduras',
    slugEn: 'honduras',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 11_005_850,
    populationYear: null,
    areaKm2: 111_890,
    capitalNameTr: 'Tegusigalpa',
    capitalNameEn: 'Tegucigalpa',
    capitalLatitude: 14.0723,
    capitalLongitude: -87.1921,
    neighborIsoCodes: ['GT', 'SV', 'NI'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Honduras Lempirası',
    currencyCode: 'HNL',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
  },
  {
    isoCode: 'NI',
    isoCodeAlpha3: 'NIC',
    nameTr: 'Nikaragua',
    nameEn: 'Nicaragua',
    slugTr: 'nikaragua',
    slugEn: 'nicaragua',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 7_007_502,
    populationYear: null,
    areaKm2: 120_340,
    capitalNameTr: 'Managua',
    capitalNameEn: 'Managua',
    capitalLatitude: 12.1364,
    capitalLongitude: -86.2514,
    neighborIsoCodes: ['HN', 'CR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Nikaragua Kordobası',
    currencyCode: 'NIO',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
  },
  {
    isoCode: 'PA',
    isoCodeAlpha3: 'PAN',
    nameTr: 'Panama',
    nameEn: 'Panama',
    slugTr: 'panama',
    slugEn: 'panama',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 4_571_189,
    populationYear: null,
    areaKm2: 74_180,
    capitalNameTr: 'Panama Şehri',
    capitalNameEn: 'Panamá',
    capitalLatitude: 8.9824,
    capitalLongitude: -79.5199,
    neighborIsoCodes: ['CR', 'CO'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Panama Balboası',
    currencyCode: 'PAB',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "Kolombiya'dan 3 Kasım 1903'te ayrıldı (daha önce 28 Kasım 1821'de İspanya'dan bağımsızlık kazanıp Gran Kolombiya'ya katılmıştı).",
  },
  {
    isoCode: 'AG',
    isoCodeAlpha3: 'ATG',
    nameTr: 'Antigua ve Barbuda',
    nameEn: 'Antigua and Barbuda',
    slugTr: 'antigua-ve-barbuda',
    slugEn: 'antigua-and-barbuda',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 94_209,
    populationYear: null,
    areaKm2: 440,
    capitalNameTr: "Saint John's",
    capitalNameEn: "Saint John's",
    capitalLatitude: 17.1274,
    capitalLongitude: -61.8468,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "1 Kasım 1981'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'BS',
    isoCodeAlpha3: 'BHS',
    nameTr: 'Bahamalar',
    nameEn: 'Bahamas',
    slugTr: 'bahamalar',
    slugEn: 'bahamas',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 403_033,
    populationYear: null,
    areaKm2: 10_010,
    capitalNameTr: 'Nassau',
    capitalNameEn: 'Nassau',
    capitalLatitude: 25.0343,
    capitalLongitude: -77.3963,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Bahama Doları',
    currencyCode: 'BSD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "10 Temmuz 1973'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'BB',
    isoCodeAlpha3: 'BRB',
    nameTr: 'Barbados',
    nameEn: 'Barbados',
    slugTr: 'barbados',
    slugEn: 'barbados',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 282_623,
    populationYear: null,
    areaKm2: 430,
    capitalNameTr: 'Bridgetown',
    capitalNameEn: 'Bridgetown',
    capitalLatitude: 13.1132,
    capitalLongitude: -59.5988,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Barbados Doları',
    currencyCode: 'BBD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "30 Kasım 1966'da Birleşik Krallık'tan bağımsız oldu (2021'de cumhuriyete geçti).",
  },
  {
    isoCode: 'CU',
    isoCodeAlpha3: 'CUB',
    nameTr: 'Küba',
    nameEn: 'Cuba',
    slugTr: 'kuba',
    slugEn: 'cuba',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 10_937_203,
    populationYear: null,
    areaKm2: 103_800,
    capitalNameTr: 'Havana',
    capitalNameEn: 'Havana',
    capitalLatitude: 23.1136,
    capitalLongitude: -82.3666,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Küba Pesosu',
    currencyCode: 'CUP',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr:
      "İspanya egemenliğinin ardından 20 Mayıs 1902'de bağımsız cumhuriyet ilan edildi.",
    introTr:
      "Karayipler'in yüzölçümce en büyük adası olan Küba'nın kara sınırı yoktur. Kuzeyinde " +
      'Florida Boğazı, kuzeybatısında Meksika Körfezi, güneyinde ise Karayip Denizi yer ' +
      'alır. Ülke toprağının yaklaşık üçte ikisi düz ya da hafif dalgalı ovalardan oluşur, ' +
      'dağlık kesimler adanın belirli bölgelerinde toplanmıştır.',
    landformNoteTr:
      "Küba'nın dağlık arazisi üç ayrı kümede toplanır: güneydoğuda, ülkenin en yüksek " +
      "noktası olan 1.974 metrelik Pico Turquino'yu barındıran Sierra Maestra; orta " +
      'kesimde Sierra del Escambray; batıda ise Sierra del Rosario. Batıdaki Viñales ' +
      "Vadisi, dik yamaçlı kireçtaşı tepeleri olan mogote'leriyle Küba'nın en tanınmış " +
      'karst manzarasını oluşturur.',
    climateNoteTr:
      "Köppen sınıflandırmasında Aw kodlu tropikal savan iklimi, Küba'nın büyük bölümünde " +
      "görülür. Sierra Maestra ve Sierra del Rosario'nun rüzgar alan yamaçlarında bu iklim, " +
      'daha nemli bir muson ya da yağmur ormanı karakterine yaklaşır. Buna karşılık ' +
      "Guantánamo Körfezi çevresi, Sierra Maestra'nın yağış gölgesinde kaldığı için yarı " +
      'kurak bir iklime sahiptir. Kasım-Nisan arasında kurak, Mayıs-Ekim arasında yağışlı ' +
      'mevsim yaşanır; Haziran-Kasım kasırga sezonu adayı düzenli olarak etkiler.',
    hydrographyNoteTr:
      "Sierra Maestra'da doğan Cauto Nehri, kuzeybatıya akarak 370 kilometre sonra denize " +
      'ulaşır — ülkenin en uzun nehridir. Debi bakımından en yüksek ve en bakir ' +
      "nehirlerden biri olan Toa Nehri de yine doğu Küba'da yer alır. Adanın dar ve uzun " +
      "biçimi yüzünden Küba'nın nehirleri genellikle kısa kalır, çoğu da gemi " +
      'taşımacılığına elverişli değildir. Batıdaki karst bölgelerinde ise yüzey nehirleri ' +
      'yerine yeraltı nehir ve mağara sistemleri yaygındır.',
  },
  {
    isoCode: 'DM',
    isoCodeAlpha3: 'DMA',
    nameTr: 'Dominika',
    nameEn: 'Dominica',
    slugTr: 'dominika',
    slugEn: 'dominica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 65_871,
    populationYear: null,
    areaKm2: 750,
    capitalNameTr: 'Roseau',
    capitalNameEn: 'Roseau',
    capitalLatitude: 15.3092,
    capitalLongitude: -61.3794,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "3 Kasım 1978'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'DO',
    isoCodeAlpha3: 'DOM',
    nameTr: 'Dominik Cumhuriyeti',
    nameEn: 'Dominican Republic',
    slugTr: 'dominik-cumhuriyeti',
    slugEn: 'dominican-republic',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 11_520_487,
    populationYear: null,
    areaKm2: 48_198,
    capitalNameTr: 'Santo Domingo',
    capitalNameEn: 'Santo Domingo',
    capitalLatitude: 18.4861,
    capitalLongitude: -69.9312,
    neighborIsoCodes: ['HT'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Dominik Pesosu',
    currencyCode: 'DOP',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "27 Şubat 1844'te Haiti'den bağımsız oldu.",
  },
  {
    isoCode: 'GD',
    isoCodeAlpha3: 'GRD',
    nameTr: 'Grenada',
    nameEn: 'Grenada',
    slugTr: 'grenada',
    slugEn: 'grenada',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 117_303,
    populationYear: null,
    areaKm2: 340,
    capitalNameTr: "Saint George's",
    capitalNameEn: "Saint George's",
    capitalLatitude: 12.0561,
    capitalLongitude: -61.7488,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "7 Şubat 1974'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'HT',
    isoCodeAlpha3: 'HTI',
    nameTr: 'Haiti',
    nameEn: 'Haiti',
    slugTr: 'haiti',
    slugEn: 'haiti',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 11_906_095,
    populationYear: null,
    areaKm2: 27_560,
    capitalNameTr: 'Port-au-Prince',
    capitalNameEn: 'Port-au-Prince',
    capitalLatitude: 18.5944,
    capitalLongitude: -72.3074,
    neighborIsoCodes: ['DO'],
    officialLanguagesTr: ['Fransızca', 'Haiti Kreyolu'],
    currencyNameTr: 'Haiti Gurdu',
    currencyCode: 'HTG',
    governmentFormTr: null,
    independenceNoteTr:
      "1 Ocak 1804'te Fransa'dan bağımsız oldu (dünyanın ilk bağımsız siyah cumhuriyeti).",
  },
  {
    isoCode: 'JM',
    isoCodeAlpha3: 'JAM',
    nameTr: 'Jamaika',
    nameEn: 'Jamaica',
    slugTr: 'jamaika',
    slugEn: 'jamaica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 2_837_077,
    populationYear: null,
    areaKm2: 10_830,
    capitalNameTr: 'Kingston',
    capitalNameEn: 'Kingston',
    capitalLatitude: 17.9712,
    capitalLongitude: -76.7936,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Jamaika Doları',
    currencyCode: 'JMD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "6 Ağustos 1962'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'KN',
    isoCodeAlpha3: 'KNA',
    nameTr: 'Saint Kitts ve Nevis',
    nameEn: 'Saint Kitts and Nevis',
    slugTr: 'saint-kitts-ve-nevis',
    slugEn: 'saint-kitts-and-nevis',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 46_922,
    populationYear: null,
    areaKm2: 260,
    capitalNameTr: 'Baster',
    capitalNameEn: 'Basseterre',
    capitalLatitude: 17.3026,
    capitalLongitude: -62.7177,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Federal parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "19 Eylül 1983'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'LC',
    isoCodeAlpha3: 'LCA',
    nameTr: 'Saint Lucia',
    nameEn: 'Saint Lucia',
    slugTr: 'saint-lucia',
    slugEn: 'saint-lucia',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 180_149,
    populationYear: null,
    areaKm2: 610,
    capitalNameTr: 'Castries',
    capitalNameEn: 'Castries',
    capitalLatitude: 14.0101,
    capitalLongitude: -60.9875,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "22 Şubat 1979'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'VC',
    isoCodeAlpha3: 'VCT',
    nameTr: 'Saint Vincent ve Grenadinler',
    nameEn: 'Saint Vincent and the Grenadines',
    slugTr: 'saint-vincent-ve-grenadinler',
    slugEn: 'saint-vincent-and-the-grenadines',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 99_924,
    populationYear: null,
    areaKm2: 390,
    capitalNameTr: 'Kingstown',
    capitalNameEn: 'Kingstown',
    capitalLatitude: 13.1587,
    capitalLongitude: -61.2248,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "27 Ekim 1979'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'TT',
    isoCodeAlpha3: 'TTO',
    nameTr: 'Trinidad ve Tobago',
    nameEn: 'Trinidad and Tobago',
    slugTr: 'trinidad-ve-tobago',
    slugEn: 'trinidad-and-tobago',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 1_367_764,
    populationYear: null,
    areaKm2: 5_130,
    capitalNameTr: 'Port of Spain',
    capitalNameEn: 'Port of Spain',
    capitalLatitude: 10.6549,
    capitalLongitude: -61.5019,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Trinidad ve Tobago Doları',
    currencyCode: 'TTD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "31 Ağustos 1962'de Birleşik Krallık'tan bağımsız oldu (Cumhuriyet 1976).",
  },
  {
    isoCode: 'AR',
    isoCodeAlpha3: 'ARG',
    nameTr: 'Arjantin',
    nameEn: 'Argentina',
    slugTr: 'arjantin',
    slugEn: 'argentina',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 45_851_378,
    populationYear: null,
    areaKm2: 2_736_690,
    capitalNameTr: 'Buenos Aires',
    capitalNameEn: 'Buenos Aires',
    capitalLatitude: -34.6037,
    capitalLongitude: -58.3816,
    neighborIsoCodes: ['CL', 'BO', 'PY', 'BR', 'UY'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Arjantin Pesosu',
    currencyCode: 'ARS',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "9 Temmuz 1816'da İspanya'dan bağımsızlığını ilan etti (süreç 25 Mayıs 1810'da başladı).",
    introTr:
      "Güney Amerika'nın (Brezilya'dan sonra) yüzölçümce ikinci büyük ülkesi olan Arjantin, " +
      'batıda And Dağları boyunca Şili ile sınırlanır. Ülke kuzeyden güneye yaklaşık 3.700 ' +
      'kilometre uzanır ve üç farklı bölgeye ayrılır: kuzeyde Gran Chaco, orta kesimde ' +
      'Pampalar, güneyde ise Patagonya.',
    landformNoteTr:
      'And Dağları, ülkenin batı sınırı boyunca uzanır ve en yüksek noktasını, 6.961 ' +
      "metrelik Aconcagua'da bulur — yalnızca Arjantin'in değil, Amerika kıtalarının ve tüm " +
      'Batı ile Güney yarımkürenin en yüksek zirvesidir. Merkezde, yaklaşık 760.000 ' +
      'kilometrekarelik geniş ve düz bir çayır olan Pampalar uzanır; batıdaki kurak Pampa ' +
      'ile doğudaki nemli Pampa arasındaki fark, bölgeyi tarım ve hayvancılığın kalbi ' +
      'haline getirir. Güneyde ise Patagonya başlar: doğusu rüzgarlı ve kurak bir ' +
      'yayla-step, batısındaki Andine kesimi ise buzullarla kaplıdır.',
    climateNoteTr:
      'Kuzeyde neredeyse tropikal bir iklim görülürken, Buenos Aires ve Pampalar bölgesinde ' +
      'ılıman bir iklim hakimdir. Daha güneyde, Patagonya soğuk ve sürekli rüzgarlı bir ' +
      "iklime sahiptir; ülkenin en güneyindeki Ateş Ülkesi'nde ise subpolar koşullar " +
      "yaşanır. Kuzeyden güneye 3.700 kilometreyi bulan bu uzunluk, Arjantin'e kıtanın en " +
      'geniş iklim yelpazelerinden birini kazandırır.',
    hydrographyNoteTr:
      "Ülkenin en uzun nehri, Brezilya'da doğup güneye akan ve toplamda yaklaşık 4.880 " +
      "kilometreye ulaşan Paraná'dır; Uruguay Nehri ile birleştiği noktada geniş bir haliç " +
      "olan Río de la Plata'yı oluşturur. Gran Chaco'da, Paraguay ve Paraná'nın kolları " +
      "olan Pilcomayo ve Bermejo nehirleri akar. Patagonya'da ise Colorado ve Negro " +
      "nehirleri, And Dağları'ndan doğup Atlantik'e ulaşan başlıca su yollarıdır.",
  },
  {
    isoCode: 'BO',
    isoCodeAlpha3: 'BOL',
    nameTr: 'Bolivya',
    nameEn: 'Bolivia',
    slugTr: 'bolivya',
    slugEn: 'bolivia',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 12_581_843,
    populationYear: null,
    areaKm2: 1_083_300,
    capitalNameTr: 'La Paz',
    capitalNameEn: 'La Paz',
    capitalLatitude: -16.5,
    capitalLongitude: -68.15,
    neighborIsoCodes: ['PE', 'CL', 'AR', 'PY', 'BR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Bolivya Bolivianosu',
    currencyCode: 'BOB',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "6 Ağustos 1825'te İspanya'dan bağımsız oldu.",
  },
  {
    isoCode: 'BR',
    isoCodeAlpha3: 'BRA',
    nameTr: 'Brezilya',
    nameEn: 'Brazil',
    slugTr: 'brezilya',
    slugEn: 'brazil',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 212_812_405,
    populationYear: null,
    areaKm2: 8_358_140,
    capitalNameTr: 'Brazilya',
    capitalNameEn: 'Brasília',
    capitalLatitude: -15.7939,
    capitalLongitude: -47.8828,
    neighborIsoCodes: ['UY', 'AR', 'PY', 'BO', 'PE', 'CO', 'VE', 'GY', 'SR', 'FR'],
    officialLanguagesTr: ['Portekizce'],
    currencyNameTr: 'Brezilya Reali',
    currencyCode: 'BRL',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr: "7 Eylül 1822'de Portekiz'den bağımsız oldu.",
    introTr:
      "Güney Amerika kıtasının yaklaşık %47'sini kaplayan Brezilya, kıtanın yüzölçümce en " +
      'büyük ülkesidir. Şili ve Ekvator dışındaki her Güney Amerika ülkesiyle kara sınırı ' +
      "paylaşır. Doğuda Atlantik Okyanusu'na kıyısı vardır; kuzeyini Amazon Havzası, güney " +
      've orta kesimini ise geniş bir yayla kaplar.',
    landformNoteTr:
      'Ülkenin güney ve orta kesimini, ortalama 1.000 metre yükseklikteki Brezilya Yaylası ' +
      '(Planalto Brasileiro) kaplar; bu yaylanın karakteristik bitki örtüsü, geniş bir ' +
      "savan ekosistemi olan Cerrado'dur. Kuzeyde ise düz ve alçak Amazon Havzası uzanır, " +
      "dünyanın en büyük yağmur ormanına ev sahipliği yapar. Brezilya'nın en yüksek " +
      "noktası, Amazonas eyaletindeki İmeri Dağları'nda yükselen 2.995 metrelik Pico da " +
      "Neblina'dır; bu zirve, ülkenin en dağlık bölgesi olan güneydoğu değil, Amazon " +
      'ormanının derinlikleri içinde yer alır. Ülkenin batı-orta kesiminde, Paraguay ' +
      "Nehri'nin taşkın ovasında yer alan Pantanal, dünyanın en büyük tropikal sulak " +
      'alanlarından biridir.',
    climateNoteTr:
      "Brezilya beş farklı iklim bölgesine ayrılır. Amazon Havzası'nda yıl boyunca sıcak " +
      've nemli kalan ekvatoral iklim egemendir. Kuzeydoğu kıyısı boyunca, belirgin ' +
      'yağışlı ve kurak dönemleri olan tropikal iklim görülür; kıyının hemen iç kesiminde, ' +
      'Sertão olarak bilinen bölgede ise yarı kurak bir iklim hakimdir. Brezilya ' +
      "Yaylası'nın iç kesimlerinde Cerrado'nun tropikal yükseklik iklimi, güneyde ise dört " +
      'mevsimin belirgin olduğu ılıman subtropikal iklim yaşanır.',
    hydrographyNoteTr:
      'Amazon Nehri, debi bakımından dünyanın en büyük nehridir; saniyede yaklaşık 209.000 ' +
      "metreküp su Atlantik'e boşalır, bu da dünya okyanuslarına giren nehir suyunun " +
      "yaklaşık beşte biri anlamına gelir. 1.100'den fazla kolu vardır, bunlardan 17'si " +
      '1.500 kilometreden uzundur. En büyük kollarından biri olan 2.230 kilometrelik Rio ' +
      "Negro, Manaus yakınlarında Solimões Nehri'yle birleşir — bu birleşmeden sonra nehir " +
      "Brezilya'da Amazon adını alır. İki kolun farklı renkteki suları, birleşme " +
      'noktasından sonra uzun süre karışmadan yan yana akar; bu görüntü ' +
      '"Encontro das Águas" (suların buluşması) adıyla bilinir. Güneyde Paraná, Paraguay ' +
      "ve Uruguay nehirleri, Brezilya Yaylası'nda doğup güneye akarak Río de la Plata " +
      'havzasını besler.',
  },
  {
    isoCode: 'CL',
    isoCodeAlpha3: 'CHL',
    nameTr: 'Şili',
    nameEn: 'Chile',
    slugTr: 'sili',
    slugEn: 'chile',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 19_859_921,
    populationYear: null,
    areaKm2: 742_832,
    capitalNameTr: 'Santiago',
    capitalNameEn: 'Santiago',
    capitalLatitude: -33.4489,
    capitalLongitude: -70.6693,
    neighborIsoCodes: ['PE', 'BO', 'AR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Şili Pesosu',
    currencyCode: 'CLP',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      '18 Şubat 1818\'de bağımsızlık ilan edildi (millî gün "Fiestas Patrias" ise mücadelenin başladığı 18 Eylül 1810\'da kutlanır).',
    introTr:
      "Güney Amerika'nın batı kıyısında, kuzeyden güneye yaklaşık 4.300 kilometre uzanan " +
      'ama ortalama yalnızca 180 kilometre genişliğinde olan Şili, dünyanın en uzun ve dar ' +
      "ülkelerinden biridir. Doğuda And Dağları boyunca Arjantin'e, kuzeyde Peru ve " +
      "Bolivya'ya komşudur.",
    landformNoteTr:
      'Ülke, kuzeyden güneye üç paralel kuşaktan oluşur: doğuda kıtanın omurgası olan And ' +
      'Dağları, batıda genellikle 2.000 metrenin altında kalan Kıyı Sıradağları, ikisinin ' +
      'arasında ise yaklaşık 965 kilometre uzunluğundaki Orta Vadi — ülke nüfusunun ve ' +
      'tarımının büyük bölümü bu vadide yoğunlaşır. Kuzeyde, And Dağları ile Kıyı ' +
      "Sıradağları'nın iki yönden kapattığı Atakama Çölü, dünyanın kutup dışındaki en kurak " +
      'çölüdür. Güneye inildikçe Kıyı Sıradağları parçalanıp adalara dönüşür; bu bölgede ' +
      'Kuzey ve Güney Patagonya Buz Tarlaları ile derin fiyortlar yer alır.',
    climateNoteTr:
      "Kuzeydeki Atakama'da yıllarca hiç yağış görmeyen alanlar bulunan hiper-kurak bir çöl " +
      "iklimi hakimdir. Orta kesimde, başkent Santiago'nun da bulunduğu bölgede Akdeniz " +
      'iklimi görülür — yazlar sıcak ve kurak, kışlar ılık ve yağışlıdır. Güneye doğru ' +
      "iklim giderek soğur ve nemlenir; Patagonya'ya yakın kesimlerde okyanusal, soğuk ve " +
      'yağışlı bir iklim egemen olur. Kıyı boyunca kuzeyden güneye akan soğuk Humboldt ' +
      'Akıntısı, bu iklim çeşitliliğinin başlıca belirleyicilerinden biridir.',
    hydrographyNoteTr:
      "Şili'nin dar yapısı nehirlerin genellikle kısa olmasına yol açar; neredeyse tamamı " +
      "And Dağları'nda doğup batıya, Pasifik Okyanusu'na akar. Ülkenin en uzun nehri, " +
      'kuzeyde Antofagasta bölgesinde U biçiminde bir yörünge izleyen 440 kilometrelik Loa ' +
      "Nehri'dir. Orta-güney kesimdeki 380 kilometrelik Biobío Nehri ise ülkenin en geniş " +
      'nehridir, ortalama genişliği 1 kilometreyi bulur.',
  },
  {
    isoCode: 'CO',
    isoCodeAlpha3: 'COL',
    nameTr: 'Kolombiya',
    nameEn: 'Colombia',
    slugTr: 'kolombiya',
    slugEn: 'colombia',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 53_425_635,
    populationYear: null,
    areaKm2: 1_109_500,
    capitalNameTr: 'Bogota',
    capitalNameEn: 'Bogotá',
    capitalLatitude: 4.711,
    capitalLongitude: -74.0721,
    neighborIsoCodes: ['PA', 'VE', 'BR', 'PE', 'EC'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Kolombiya Pesosu',
    currencyCode: 'COP',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "20 Temmuz 1810'da İspanya'ya karşı mücadele başladı (resmî millî gün); tam bağımsızlık 1819.",
    introTr:
      "And Dağları, Ekvator sınırından Kolombiya'ya girer girmez üçe ayrılır — kıtadaki " +
      "hiçbir başka ülkede görülmeyen bu yapı, Kolombiya'nın coğrafyasını baştan sona " +
      "şekillendirir. Ülke, kuzeyde Karayip Denizi'ne, batıda ise Büyük Okyanus'a kıyısı " +
      'olan tek Güney Amerika ülkesidir.',
    landformNoteTr:
      'And Dağları, Kolombiya sınırları içinde Batı, Orta ve Doğu Kordilyera olmak üzere üç ' +
      "paralel sıradağa ayrılır; bunların en yükseği Orta Kordilyera'dır. Magdalena ve " +
      'Cauca nehirlerinin vadileri, bu üç sıradağı birbirinden ayırır. Doğuda, Orinoco ' +
      "Havzası'nın bir parçası olan Llanos düzlükleri geniş bir savan örtüsüyle uzanır; " +
      'güneyde ise Amazon yağmur ormanı başlar. Batı kıyısındaki Chocó bölgesi, yılda ' +
      '7.000 ila 13.000 milimetre arasında yağış alarak dünyanın en yağışlı yerlerinden ' +
      'biri sayılır.',
    climateNoteTr:
      "Ekvator'a yakınlığı nedeniyle Kolombiya'da mevsimsel sıcaklık farkı azdır; iklimi " +
      'büyük ölçüde rakım belirler. Deniz seviyesinden 900 metreye kadar tierra caliente ' +
      'kuşağında sıcak ve nemli bir iklim görülür. 900-1.980 metre arasındaki tierra ' +
      "templada'da ılıman koşullar hakimdir — Medellín bu kuşaktadır. 1.980-3.500 metre " +
      'arasındaki tierra fría serindir; 2.640 metre yükseklikteki başkent Bogotá bu ' +
      'kuşağın içinde yer alır. 3.000 metrenin üzerinde başlayan páramo kuşağında ise ' +
      'sıcaklık 10 santigrat derecenin altına düşer, kar yağışı sık görülür.',
    hydrographyNoteTr:
      "Ülkenin ana nehri Magdalena, And Dağları'nda doğar ve yaklaşık 1.528 kilometre " +
      "boyunca kuzeye akarak Karayip Denizi'ne dökülür; kolu Cauca ile birlikte Batı ve " +
      "Orta Kordilyera arasındaki vadiyi oluşturur. Pasifik kıyısında, Chocó'nun yoğun " +
      'yağmur ormanından geçen Atrato ve San Juan nehirleri kısa ama hızlı akışlıdır. ' +
      "Güneyde ise Putumayo ve Caquetá nehirleri, Kolombiya topraklarını Amazon Havzası'na " +
      'bağlar.',
  },
  {
    isoCode: 'EC',
    isoCodeAlpha3: 'ECU',
    nameTr: 'Ekvator',
    nameEn: 'Ecuador',
    slugTr: 'ekvator',
    slugEn: 'ecuador',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 18_289_896,
    populationYear: null,
    areaKm2: 248_360,
    capitalNameTr: 'Kito',
    capitalNameEn: 'Quito',
    capitalLatitude: -0.1807,
    capitalLongitude: -78.4678,
    neighborIsoCodes: ['CO', 'PE'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "24 Mayıs 1822'de İspanya'dan bağımsız oldu; Büyük Kolombiya'dan ayrılış 1830.",
  },
  {
    isoCode: 'GY',
    isoCodeAlpha3: 'GUY',
    nameTr: 'Guyana',
    nameEn: 'Guyana',
    slugTr: 'guyana',
    slugEn: 'guyana',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 835_986,
    populationYear: null,
    areaKm2: 211_140,
    capitalNameTr: 'Georgetown',
    capitalNameEn: 'Georgetown',
    capitalLatitude: 6.8013,
    capitalLongitude: -58.1551,
    neighborIsoCodes: ['VE', 'BR', 'SR'],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Guyana Doları',
    currencyCode: 'GYD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "26 Mayıs 1966'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'PY',
    isoCodeAlpha3: 'PRY',
    nameTr: 'Paraguay',
    nameEn: 'Paraguay',
    slugTr: 'paraguay',
    slugEn: 'paraguay',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 7_013_078,
    populationYear: null,
    areaKm2: 396_012,
    capitalNameTr: 'Asuncion',
    capitalNameEn: 'Asunción',
    capitalLatitude: -25.2637,
    capitalLongitude: -57.5759,
    neighborIsoCodes: ['BO', 'BR', 'AR'],
    officialLanguagesTr: ['İspanyolca', 'Guarani'],
    currencyNameTr: 'Paraguay Guaranisi',
    currencyCode: 'PYG',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr: "14-15 Mayıs 1811'de İspanya'dan bağımsız oldu.",
  },
  {
    isoCode: 'PE',
    isoCodeAlpha3: 'PER',
    nameTr: 'Peru',
    nameEn: 'Peru',
    slugTr: 'peru',
    slugEn: 'peru',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 34_576_665,
    populationYear: null,
    areaKm2: 1_280_000,
    capitalNameTr: 'Lima',
    capitalNameEn: 'Lima',
    capitalLatitude: -12.0464,
    capitalLongitude: -77.0428,
    neighborIsoCodes: ['EC', 'CO', 'BR', 'BO', 'CL'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Peru Solü',
    currencyCode: 'PEN',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr: "28 Temmuz 1821'de İspanya'dan bağımsızlığını ilan etti.",
    introTr:
      'Peru, birbirinden çok farklı üç boylamsal bölgeye ayrılır: batıda kurak kıyı ' +
      '(Costa), ortada And Dağları (Sierra), doğuda ise Amazon ormanı (Selva). Bu üç bölge ' +
      "içinde en büyüğü Selva'dır — ülke topraklarının %60'ından fazlasını kaplar, ama " +
      "nüfusun büyük kısmı Costa ve Sierra'da yaşar.",
    landformNoteTr:
      'And Dağları, Peru topraklarını kuzeyden güneye boydan boya kat eder; ülkenin en ' +
      "yüksek noktası, 6.768 metrelik Huascarán'dır. And Dağları'nın içinde, Bolivya ile " +
      'paylaşılan Titicaca Gölü yer alır — 3.812 metre yükseklikteki bu göl, dünyanın ' +
      'seyrüsefere elverişli en yüksek gölüdür. Kıyı boyunca dar bir çöl şeridi uzanır; ' +
      "And Dağları'ndan inen birkaç nehrin oluşturduğu vadiler bu kurak şeritte tarıma " +
      "elverişli cepler yaratır. Doğuda başlayan Selva, Amazon Havzası'nın bir parçasıdır " +
      've alçak, yoğun ormanla kaplıdır.',
    climateNoteTr:
      "Kıyı boyunca, soğuk Humboldt Akıntısı'nın etkisiyle nemli ama neredeyse yağışsız bir " +
      'çöl iklimi hakimdir; başkent Lima yılda ortalama yalnızca 10 milimetre yağış alır ' +
      "ve Mayıs-Kasım arasında sık sık yoğun sis (garúa) örter. And Dağları'nda rakım " +
      'arttıkça sıcaklık düşer; Mayıs-Eylül arasındaki kuru mevsimde gökyüzü açık ve ' +
      'geceler soğuk geçerken, Ekim-Nisan yağışlı mevsiminde öğleden sonraları sağanak ' +
      "yağış görülür. Doğudaki Selva'da ise yıl boyunca sıcak ve nemli, yılda 2.000-3.000 " +
      'milimetre yağış alan tropikal bir iklim egemendir.',
    hydrographyNoteTr:
      "Amazon Nehri'nin en uzak kaynağı, onlarca yıl boyunca Peru'daki Apurímac Nehri'nin " +
      "başlangıç noktası olarak kabul edildi; 2014'te yapılan bir çalışma bu kaynağı, yine " +
      "Peru'da bulunan Cordillera Rumi Cruz'daki Mantaro Nehri'nin başlangıcına taşıdı — " +
      "Mantaro, Apurímac'tan yaklaşık 75 kilometre daha uzun çıktı. Doğuda, Marañón ve " +
      "Ucayali nehirleri Peru topraklarında birleşerek Amazon'un ana gövdesini başlatır.",
  },
  {
    isoCode: 'SR',
    isoCodeAlpha3: 'SUR',
    nameTr: 'Surinam',
    nameEn: 'Suriname',
    slugTr: 'surinam',
    slugEn: 'suriname',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 639_850,
    populationYear: null,
    areaKm2: 160_508,
    capitalNameTr: 'Paramaribo',
    capitalNameEn: 'Paramaribo',
    capitalLatitude: 5.852,
    capitalLongitude: -55.2038,
    neighborIsoCodes: ['GY', 'BR', 'FR'],
    officialLanguagesTr: ['Hollandaca'],
    currencyNameTr: 'Surinam Doları',
    currencyCode: 'SRD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "25 Kasım 1975'te Hollanda'dan bağımsız oldu.",
  },
  {
    isoCode: 'UY',
    isoCodeAlpha3: 'URY',
    nameTr: 'Uruguay',
    nameEn: 'Uruguay',
    slugTr: 'uruguay',
    slugEn: 'uruguay',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 3_384_688,
    populationYear: null,
    areaKm2: 175_020,
    capitalNameTr: 'Montevideo',
    capitalNameEn: 'Montevideo',
    capitalLatitude: -34.9011,
    capitalLongitude: -56.1645,
    neighborIsoCodes: ['BR', 'AR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Uruguay Pesosu',
    currencyCode: 'UYU',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "25 Ağustos 1825'te bağımsızlığını ilan etti; uluslararası tanınma 1828 Montevideo Antlaşması ile.",
  },
  {
    isoCode: 'VE',
    isoCodeAlpha3: 'VEN',
    nameTr: 'Venezuela',
    nameEn: 'Venezuela',
    slugTr: 'venezuela',
    slugEn: 'venezuela',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 28_516_896,
    populationYear: null,
    areaKm2: 882_050,
    capitalNameTr: 'Karakas',
    capitalNameEn: 'Caracas',
    capitalLatitude: 10.4806,
    capitalLongitude: -66.9036,
    neighborIsoCodes: ['CO', 'BR', 'GY'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Venezuela Bolivarı',
    currencyCode: 'VES',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr: "5 Temmuz 1811'de İspanya'dan bağımsızlığını ilan etti.",
    introTr:
      "Venezuela, kuzeyde Karayip Denizi'ne kıyısı olan ve dört farklı coğrafi bölgeye " +
      "ayrılan bir ülkedir: kuzeybatıda Maracaibo alçak arazisi, kuzeyde And Dağları'nın " +
      'uzantısı olan kıyı sıradağları, orta kesimde geniş Orinoco düzlükleri (Llanos) ve ' +
      'güneydoğuda Guyana Yaylası.',
    landformNoteTr:
      "And Dağları'nın Venezuela'ya uzanan kolu, ülkenin kuzeybatısını kaplar; en yüksek " +
      "noktası, Mérida yakınlarındaki 4.978 metrelik Pico Bolívar'dır. Maracaibo Gölü, " +
      "Karayip Denizi'ne açık olduğu için teknik olarak bir göl sayılmasa da, Güney " +
      "Amerika'nın en büyük iç su kütlesi kabul edilir. Ülkenin yaklaşık üçte birini " +
      'kaplayan Llanos, Orinoco Nehri havzasının parçası olan geniş bir çayır-savan ' +
      "düzlüğüdür. Güneydoğuda ise Guyana Yaylası'nda, dik yamaçlı ve düz tepeli tepui'ler " +
      "yükselir; bunlardan Auyán-tepui'nin kenarından dökülen Angel Şelalesi, 979 metre " +
      'yükseklikle dünyanın en yüksek şelalesidir.',
    climateNoteTr:
      "Llanos'ta, belirgin yağışlı ve kurak dönemleri olan tropikal savan iklimi hakimdir. " +
      'Maracaibo Gölü çevresi ise ülkenin en sıcak bölgesidir; bazı yerleşimlerde sıcaklık ' +
      "46-47 santigrat dereceye kadar çıkabilir. And Dağları'nın yüksek vadilerinde, Mérida " +
      've Karakas çevresinde ise ılıman bir dağ iklimi görülür — Mérida eyaletindeki en ' +
      'yüksek kesimlerde sıcaklık eksi 11 santigrat dereceye kadar düşebilir.',
    hydrographyNoteTr:
      "Debi bakımından Güney Amerika'da Amazon'dan sonra en büyük, dünya genelinde ise " +
      "üçüncü büyük nehir olan Orinoco, Guyana Yaylası'nda doğar ve yaklaşık 2.140 " +
      "kilometre sonra Atlantik Okyanusu'na ulaşır. Guyana Yaylası'ndan inen Caroní Nehri " +
      "de Orinoco'ya katılır; güzergahı boyunca Angel Şelalesi dahil çok sayıda şelale " +
      'barındırır.',
  },
];
