import { Continent } from '../../../common/continent.enum';
import type { CountrySeed } from '../country.seed-data';

/**
 * Amerika kıtası (Kuzey + Güney) — dünya haritası base-data seed (35 ülke). Structured fields only; the
 * narrative prose fields (introTr/landformNoteTr/climateNoteTr/hydrographyNoteTr) are
 * seeded null and filled in later regional content waves. populationYear is null across
 * the board (world-scale ruling, DEC 2026-07-13). Source of record:
 * Owner's Inbox/dunya-haritasi-base-data/americas.md. Every value transcribed from the
 * approved research; slugs generated by an ASCII/Turkish-fold rule (matches the pilot).
 * nameTr uses the source "kısa" (short) name; where the bare short form is ambiguous the
 * official name is kept (ABD → "Amerika Birleşik Devletleri"). Danimarka (DK) / Fransa
 * (FR) appear only as overseas-territory parents in the source notes (Grönland, Fransız
 * Guyanası) and are seeded in the Europe lane, not here.
 */
export const AMERICAS_COUNTRIES: readonly CountrySeed[] = [
  {
    isoCode: 'CA',
    isoCodeAlpha3: 'CAN',
    nameTr: 'Kanada',
    nameEn: 'Canada',
    slugTr: 'kanada',
    slugEn: 'canada',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Kuzey Amerika',
    population: 41_651_653,
    populationYear: null,
    areaKm2: 8_788_700,
    capitalNameTr: 'Ottava',
    capitalNameEn: 'Ottawa',
    capitalLatitude: 45.4215,
    capitalLongitude: -75.6972,
    neighborIsoCodes: ['US', 'DK'],
    officialLanguagesTr: ['İngilizce', 'Fransızca'],
    currencyNameTr: 'Kanada Doları',
    currencyCode: 'CAD',
    governmentFormTr: 'Federal parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr:
      "Federasyon 1 Temmuz 1867'de kuruldu; tam bağımsızlık kademeli (1931 Westminster, 1982 Kanada Yasası).",
  },
  {
    isoCode: 'US',
    isoCodeAlpha3: 'USA',
    nameTr: 'Amerika Birleşik Devletleri',
    nameEn: 'United States',
    slugTr: 'amerika-birlesik-devletleri',
    slugEn: 'united-states',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Kuzey Amerika',
    population: 341_784_857,
    populationYear: null,
    areaKm2: 9_147_420,
    capitalNameTr: 'Vaşington',
    capitalNameEn: 'Washington, D.C.',
    capitalLatitude: 38.9072,
    capitalLongitude: -77.0369,
    neighborIsoCodes: ['CA', 'MX'],
    officialLanguagesTr: null,
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "4 Temmuz 1776'da bağımsızlığını ilan etti (İngiltere'nin tanıması 1783 Paris Antlaşması).",
    introTr:
      'Kuzey Amerika kıtasının büyük bölümünü kaplayan Amerika Birleşik Devletleri, Atlantik ve ' +
      'Pasifik okyanuslarına birden kıyısı olan, elli eyaletten oluşan federal bir ' +
      "cumhuriyettir; kıtadaki tek iki kara komşusu Kanada ve Meksika'dır.",
    landformNoteTr:
      "Ülkenin batısına Kuzey Amerika'nın en büyük sıradağı olan Kayalık Dağları hakimdir; " +
      "Alaska'daki 6.190 metrelik Denali, ülkenin ve kıtanın en yüksek noktasıdır (kıtasal 48 " +
      "eyalette en yüksek nokta ise Kaliforniya'daki 4.421 metrelik Mount Whitney'dir). Pasifik " +
      'kıyısı boyunca Cascade ve Kıyı Sıradağları uzanır. Ülkenin ortasını, ortalama 300 metre ' +
      'yükseklikte, geniş prerilerden oluşan Büyük Ovalar kaplar; bu düzlük 2.000 kilometreden ' +
      "uzun bir alana yayılır. Doğuda, Kanada'dan Alabama'ya kadar uzanan Appalaş Dağları, " +
      'genellikle 1.800 metrenin altında kalan, yaşlı ve aşınmış bir sıradağdır.',
    climateNoteTr:
      'Enlem, denizden uzaklık ve dağların yarattığı yağış gölgesi etkisi, iklimi bölgeden ' +
      'bölgeye keskin biçimde farklılaştırır. Doğu kıyısında ve iç kesimlerde (Orta Batı, Büyük ' +
      'Göller, Yeni İngiltere) dört mevsimin belirgin yaşandığı nemli karasal bir iklim ' +
      "egemendir; güneydoğuda, Florida'ya kadar uzanan kesimde ise sıcak-nemli subtropikal bir " +
      "iklime geçilir. Büyük Ovalar'ın batı kesimi yarı-kurak bir karaktere sahiptir. " +
      'Güneybatıda, Arizona ve Nevada gibi eyaletlerde sıcak ve düşük yağışlı bir çöl iklimi ' +
      'görülür. Pasifik kıyısında ise kuzeyden güneye geçiş belirgindir — Oregon ve ' +
      "Washington'da nemli bir deniz iklimi, Kaliforniya kıyısında ise yazı kurak, kışı yağışlı " +
      'bir Akdeniz iklimi hakimdir. Alaska büyük ölçüde subarktik ve tundra iklimi altındayken, ' +
      'Hawaii adaları tropikal bir iklime sahiptir.',
    hydrographyNoteTr:
      "Ülkenin en uzun nehri, Montana'da doğup Mississippi'ye katılan 3.767 kilometrelik " +
      "Missouri'dir; Mississippi Nehri'yle birleşerek dünyanın dördüncü en büyük nehir " +
      "sistemini oluşturur. Mississippi, Minnesota'dan Meksika Körfezi'ne kadar 3.766 kilometre " +
      "boyunca ülkeyi kuzeyden güneye kat eder. Colorado Nehri, Kayalık Dağları'ndan doğarak " +
      "2.334 kilometre boyunca güneybatıyı kat eder ve Kaliforniya Körfezi'ne ulaşır." +
      '\n\n' +
      'Kuzeyde, Büyük Göller sistemi — Superior, Michigan, Huron, Erie ve Ontario — dünyanın en ' +
      "büyük tatlı su kaynaklarından birini oluşturur; Michigan Gölü dışındaki dördü Kanada'yla " +
      'paylaşılır.',
  },
  {
    isoCode: 'MX',
    isoCodeAlpha3: 'MEX',
    nameTr: 'Meksika',
    nameEn: 'Mexico',
    slugTr: 'meksika',
    slugEn: 'mexico',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 131_946_900,
    populationYear: null,
    areaKm2: 1_943_950,
    capitalNameTr: 'Meksika Şehri',
    capitalNameEn: 'Mexico City',
    capitalLatitude: 19.4326,
    capitalLongitude: -99.1332,
    neighborIsoCodes: ['US', 'BZ', 'GT'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Meksika Pesosu',
    currencyCode: 'MXN',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "16 Eylül 1810'da bağımsızlık mücadelesi başladı (resmî millî gün); İspanya'nın tanıması 1821.",
    introTr:
      "Kuzey Amerika'nın güneyinde yer alan Meksika, kuzeyde ABD, güneydoğuda Belize ve " +
      "Guatemala ile komşudur. Batıda Büyük Okyanus'a, doğuda Meksika Körfezi ve Karayip " +
      "Denizi'ne kıyısı vardır. Ülkenin kuzeybatısındaki Baja California ve " +
      'güneydoğusundaki Yucatán, birbirinden çok farklı iki yarımadadır — biri kurak ve ' +
      'dağlık, diğeri düz ve ormanlık kireçtaşı bir plato.',
    landformNoteTr:
      "Orta plato'yu doğu ve batıdan çevreleyen Sierra Madre Occidental (~1.250 km) ve " +
      "Sierra Madre Oriental (~1.000 km), Meksika'nın ana dağ sistemini oluşturur. Bu iki " +
      "sıradağ, Mexico City'nin doğusunda, doğu-batı doğrultulu Trans-Meksika Volkanik " +
      "Kuşağı'yla birleşir; ülkenin en yüksek üç zirvesi de bu kuşaktadır. En yükseği, " +
      "5.636 metreyle Kuzey Amerika'nın en yüksek volkanı olan Pico de Orizaba'dır; onu " +
      '5.393 metrelik hâlâ aktif Popocatépetl ve 5.230 metrelik Iztaccíhuatl izler. ' +
      'Güneydoğuda, Yucatán Yarımadası bunların hiçbirine benzemez: düz, alçak bir ' +
      'kireçtaşı plato olan bu bölgede yüzey nehri neredeyse yoktur, su büyük ölçüde ' +
      "yeraltından akar ve çökme çukurları olan cenote'leri besler.",
    climateNoteTr:
      "Yengeç Dönencesi Meksika'yı kabaca iki iklim kuşağına böler; kuzey daha kurak, " +
      'güney daha nemli ve tropikaldir. Baja California, batı Sonora ve orta platonun ' +
      'kuzey kesimi çöl ya da yarı çöl iklimindedir, yıllık yağış çoğu yerde 250 ' +
      'milimetrenin altında kalır. Rakım da en az enlem kadar belirleyicidir: 900 ' +
      'metrenin altındaki tierra caliente sıcak ve nemli geçer, 900-1.800 metre ' +
      'arasındaki tierra templada ılıman bir iklim sunar; 1.800 metrenin üzerindeki ' +
      'tierra fría ise serin ve kurak geçer — 2.240 metre yükseklikteki Mexico City de ' +
      'bu üst kuşaktadır.',
    hydrographyNoteTr:
      "Kuzeyde Rio Bravo (ABD'de Rio Grande), yaklaşık 3.000 kilometrelik uzunluğunun " +
      '2.000 kilometrelik bölümünde Meksika ile ABD arasındaki sınırı çizer ve Meksika ' +
      "Körfezi'ne dökülür. Meksika platosunda doğan 750 kilometrelik Lerma Nehri, " +
      "ülkenin en büyük gölü olan Chapala Gölü'ne akar. Güneydoğuda Usumacinta Nehri, " +
      "Guatemala sınırından geçerek Meksika Körfezi'ne ulaşır; Guatemala'daki kaynak " +
      "kollarıyla birlikte toplam uzunluğu yaklaşık 1.000 kilometredir. Yucatán'da ise " +
      "yüzey nehri yerine cenote'ler ve yeraltı su sistemleri hakimdir.",
  },
  {
    isoCode: 'BZ',
    isoCodeAlpha3: 'BLZ',
    nameTr: 'Belize',
    nameEn: 'Belize',
    slugTr: 'belize',
    slugEn: 'belize',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 422_924,
    populationYear: null,
    areaKm2: 22_810,
    capitalNameTr: 'Belmopan',
    capitalNameEn: 'Belmopan',
    capitalLatitude: 17.251,
    capitalLongitude: -88.759,
    neighborIsoCodes: ['MX', 'GT'],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Belize Doları',
    currencyCode: 'BZD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "21 Eylül 1981'de Birleşik Krallık'tan bağımsız oldu.",
    introTr:
      "Belize, Orta Amerika'nın Karayip kıyısında, Yucatán Yarımadası'nın hemen güneyinde yer " +
      "alır. Bölgenin resmi dili İngilizce olan tek ülkesidir; bu miras, 1981'e kadar Britanya " +
      "Honduras'ı adıyla bir Birleşik Krallık sömürgesi olmasından gelir. Nüfusun büyük bölümü " +
      'kıyı şeridinde ve güneydeki nehir vadilerinde toplanır, iç kesimlerin geniş bir bölümü ' +
      'seyrek nüfusludur ve yağmur ormanıyla kaplıdır.',
    landformNoteTr:
      "Ülkenin güneyinde yükselen Maya Dağları, 1.124 metrelik Doyle's Delight zirvesiyle " +
      "Belize'nin en yüksek noktasını oluşturur; daha uzun süre bu unvanı taşıdığı sanılan " +
      'Victoria Peak (1.120 m), uydu ölçümleriyle ikinci sıraya inmiştir. Sıradağın granit ve ' +
      "şist çekirdeği yaklaşık 300-400 milyon yıl önce şekillenmiştir ve Orta Amerika'nın " +
      'bilinen en eski kayaçları arasında sayılır. Ülkenin geri kalanını kaplayan kireçtaşı ' +
      'arazi çok daha genç bir dönemde, sığ bir denizin tortullarından oluşmuştur; bu jeolojik ' +
      "fark, Maya Dağları'nın asidik ve besince fakir topraklarıyla çevresindeki kireçtaşı " +
      'ovaların bitki örtüsü arasında belirgin bir ayrım yaratır.' +
      '\n\n' +
      'Kıyı açıklarında uzanan Belize Bariyer Resifi, yaklaşık 300 kilometrelik uzunluğuyla ' +
      "Büyük Set Resifi'nin ardından dünyanın en uzun ikinci kesintisiz bariyer resifidir. Resif " +
      'içindeki Lighthouse Reef atolünde yer alan Büyük Mavi Delik, son buzul çağında oluşmuş ' +
      'bir kireçtaşı mağaranın deniz seviyesi yükselişiyle sular altında kalmasından doğmuştur; ' +
      'çapı 300 metreyi aşan bu neredeyse dairesel çukur dünya çapında tanınan bir dalış ' +
      'noktasıdır.',
    climateNoteTr:
      "Belize'de tropikal bir iklim egemendir; Mayıs-Kasım arası yağışlı, Aralık-Nisan arası " +
      'görece kurak bir mevsim izler. Ülke Karayip kasırga kuşağının içinde yer alır, kıyı ' +
      'bölgeleri yaz sonu ve sonbahar aylarında tropikal fırtına riskiyle karşı karşıyadır. ' +
      'Güneydeki dağlık kesimler kuzeydeki düz ovalara göre belirgin biçimde daha fazla yağış ' +
      "alır; Maya Dağları'nın rüzgar alan yamaçları ülkenin en yağışlı bölgeleridir.",
    hydrographyNoteTr:
      "Belize'nin en uzun nehri, Guatemala'da Mopán Nehri adıyla doğan ve 290 kilometre sonra " +
      "Belize Kenti yakınında Karayip Denizi'ne dökülen Belize Nehri'dir; kollarıyla birlikte " +
      'ülkenin en yoğun nüfuslu ve en verimli tarım bölgelerini sular. Kuzeyde Meksika sınırının ' +
      'büyük bölümünü belirleyen Rio Hondo yaklaşık 150 kilometre, güneyde Guatemala sınırını ' +
      'izleyen Sarstoon Nehri ise 111 kilometre uzunluğundadır. Kireçtaşı arazinin bulunduğu iç ' +
      'kesimlerde çok sayıda yeraltı nehri ve mağara sistemi bulunur, yüzey suyunun önemli bir ' +
      'bölümü bu mağaralardan beslenir.',
  },
  {
    isoCode: 'CR',
    isoCodeAlpha3: 'CRI',
    nameTr: 'Kosta Rika',
    nameEn: 'Costa Rica',
    slugTr: 'kosta-rika',
    slugEn: 'costa-rica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 5_152_950,
    populationYear: null,
    areaKm2: 51_060,
    capitalNameTr: 'San Hose',
    capitalNameEn: 'San José',
    capitalLatitude: 9.9281,
    capitalLongitude: -84.0907,
    neighborIsoCodes: ['NI', 'PA'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Kosta Rika Kolonu',
    currencyCode: 'CRC',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
    introTr:
      "Kosta Rika, kuzeyde Nikaragua, güneydoğuda Panama ile komşu, batıda Büyük Okyanus'a, " +
      "doğuda ise Karayip Denizi'ne kıyısı olan dar bir Orta Amerika ülkesidir. Ülkenin " +
      'ortasından geçen volkanik sıradağlar zinciri, kıyı ovalarını birbirinden ayırır ve ' +
      "nüfusun büyük bölümünün yaşadığı Orta Vadi'yi (Valle Central) çevreler. 200'den " +
      'fazla sönmüş ve etkin volkan barındıran ülke, dünyanın volkanik açıdan en yoğun ' +
      'bölgelerinden biridir.',
    landformNoteTr:
      'Kuzeyden güneye sırasıyla Guanacaste, Tilarán, Orta (Central) ve Talamanca ' +
      'sıradağları ülkenin ana dağ dizisini oluşturur; ilk üçü büyük ölçüde volkanik ' +
      'kökenlidir ve Poás, Irazú, Arenal ile Turrialba gibi hâlâ etkin yanardağları ' +
      'barındırır. Ülkenin en yüksek noktası, volkanik olmayan Talamanca sıradağlarındaki ' +
      "3.821 metrelik Cerro Chirripó'dur; açık havalarda zirveden aynı anda hem Büyük " +
      'Okyanus hem de Karayip Denizi görülebilir. Kıyı ovaları dardır — Karayip kıyısında ' +
      'düz ve bataklık, Pasifik kıyısında ise Nicoya ve Osa gibi yarımadalarla girintili ' +
      'çıkıntılıdır.',
    climateNoteTr:
      'Karayip kıyısında belirgin bir kurak mevsim yoktur; yağış yıl boyunca düşer ve ' +
      'yıllık ortalama 3.500 milimetreyi bulur. Pasifik kıyısında ise durum tam tersidir — ' +
      'kuzeydeki Guanacaste bölgesinde Kasım-Mayıs arasında altı ay süren belirgin bir ' +
      'kurak mevsim yaşanır ve bölge ülkenin en az yağış alan kesimidir; güneye inildikçe ' +
      "yağış artar. Orta Vadi'deki yükseklik sıcaklığı dengeler; başkent San José'de yıl " +
      'boyunca sıcaklık dar bir aralıkta, genellikle 15-26 santigrat derece arasında kalır.',
    hydrographyNoteTr:
      'Ülkenin dar yapısı, nehirlerin kısa ve dik eğimli olmasına yol açar; dağlardan ' +
      'kıyıya inen çok sayıda bağımsız akarsu sistemi bulunur, tek bir baskın ana nehir ' +
      'yoktur. Karayip yamacındaki Reventazón ve Pacuare nehirleri, hızlı akışlarıyla ' +
      'rafting güzergâhı olarak bilinir. Kuzeyde, Nikaragua sınırı boyunca akan San Juan ' +
      "Nehri, Nikaragua Gölü'nün fazla suyunu Karayip Denizi'ne taşır ve sınırın büyük " +
      'bölümünü oluşturur.',
  },
  {
    isoCode: 'SV',
    isoCodeAlpha3: 'SLV',
    nameTr: 'El Salvador',
    nameEn: 'El Salvador',
    slugTr: 'el-salvador',
    slugEn: 'el-salvador',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 6_365_503,
    populationYear: null,
    areaKm2: 20_720,
    capitalNameTr: 'San Salvador',
    capitalNameEn: 'San Salvador',
    capitalLatitude: 13.6929,
    capitalLongitude: -89.2182,
    neighborIsoCodes: ['GT', 'HN'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
    introTr:
      "El Salvador, Orta Amerika'da yalnızca Büyük Okyanus'a kıyısı olan tek ülkedir; kıtanın " +
      'Karayip kıyısına hiç ulaşmayan bu konum, onu bölgedeki diğer altı ülkeden ayıran temel ' +
      "özelliktir. Yüzölçümü 20.720 km² ile Orta Amerika'nın en küçük ülkesi olmasına karşın " +
      "nüfus yoğunluğu bölgede en yüksek seviyededir. Ülke, Kokos Plakası'nın Karayip " +
      "Plakası'nın altına daldığı aktif bir yitim kuşağı üzerinde yer alır ve bu nedenle sık " +
      'depremle ve etkin volkanizmayla karşı karşıyadır.',
    landformNoteTr:
      "Ülkeyi doğu-batı doğrultusunda kesen bir volkanik sıradağ, El Salvador'un iç coğrafyasını " +
      'belirler; bu hat üzerinde yirmiden fazla volkan sıralanır. Ülkenin en yüksek noktası, ' +
      "batıda Guatemala sınırına yakın 2.381 metrelik Santa Ana Yanardağı'dır (Ilamatepec). " +
      "Hemen yanı başındaki Izalco Yanardağı, 1770'ten bu yana 50'den fazla patlama geçirmiştir; " +
      'geceleri gemilere yol gösteren düzenli kızıl parıltısı nedeniyle tarihte "Büyük ' +
      'Okyanus\'un Feneri" adıyla anılmıştır.',
    climateNoteTr:
      "El Salvador'da tropikal bir iklim egemendir; Mayıs-Ekim arası yağışlı mevsim, Kasım-Nisan " +
      'arası ise kurak mevsim olarak ayrılır. Kıyı ovaları ve iç vadiler yıl boyunca sıcak ' +
      'kalırken, volkanik sıradağın yüksek kesimlerinde rakımın etkisiyle sıcaklıklar belirgin ' +
      'biçimde düşer. Ülke, Karayip kıyısındaki komşularını düzenli vuran tropikal siklonlardan ' +
      'büyük ölçüde uzak kalır; bunun yerine sık deprem ve volkanik patlama riskiyle karşı ' +
      'karşıyadır.',
    hydrographyNoteTr:
      "Ülkenin en önemli akarsuyu, Guatemala'da doğan, kuzey sıradağlarını kestikten sonra " +
      "merkezi platoyu geçen ve güneydeki volkanik sıradağı da yararak Büyük Okyanus'a dökülen " +
      "Lempa Nehri'dir; ülke topraklarının yaklaşık yarısı bu nehir ve kolları tarafından " +
      'sulanır. Lempa, ülkenin gemi taşımacılığına elverişli tek akarsuyudur. İç kesimdeki ' +
      'Coatepeque ve Ilopango gölleri, sönmüş volkanik kalderaların su tutmasıyla oluşmuştur.',
  },
  {
    isoCode: 'GT',
    isoCodeAlpha3: 'GTM',
    nameTr: 'Guatemala',
    nameEn: 'Guatemala',
    slugTr: 'guatemala',
    slugEn: 'guatemala',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 18_687_881,
    populationYear: null,
    areaKm2: 107_160,
    capitalNameTr: 'Guatemala',
    capitalNameEn: 'Guatemala City',
    capitalLatitude: 14.6349,
    capitalLongitude: -90.5069,
    neighborIsoCodes: ['MX', 'BZ', 'HN', 'SV'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Guatemala Ketzali',
    currencyCode: 'GTQ',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
    introTr:
      'Guatemala, kuzey ve batıda Meksika, doğuda Belize ve Honduras, güneydoğuda El ' +
      "Salvador ile komşudur; güneybatıda Büyük Okyanus'a, doğuda ise kısa bir Karayip " +
      'Denizi kıyısına sahiptir. Ülke topraklarını doğu-batı doğrultusunda kat eden ' +
      "volkanik dağ kuşağı, Guatemala'yı üç farklı bölgeye ayırır: ortadaki yüksek dağlık " +
      'bölge (Highlands), güneyde dar bir Pasifik kıyı ovası ve kuzeyde geniş bir kireçtaşı ' +
      "platosu olan Petén alçak ovaları. Orta Amerika'nın nüfusça en kalabalık ülkesi olan " +
      "Guatemala'da halkın büyük bölümü dağlık bölgede yaşar.",
    landformNoteTr:
      "Guatemala'nın dağlık bölgesinde 30'dan fazla volkanik zirve sıralanır; bunların en " +
      "yükseği, Orta Amerika'nın da en yüksek noktası olan 4.220 metrelik Tajumulco " +
      "Yanardağı'dır. Aynı volkanik kuşakta, yaklaşık 84.000 yıl önce büyük bir patlamayla " +
      'oluşan kalderanın içini dolduran Atitlán Gölü yer alır; 340 metreyi bulan ' +
      "derinliğiyle Orta Amerika'nın en derin gölüdür ve kenarında Atitlán, Tolimán ve San " +
      "Pedro yanardağları yükselir. Kuzeyde, Meksika'daki Yucatán Platosu'nun uzantısı olan " +
      'Petén bölgesi bunların tam tersidir: yüksekliği nadiren 200 metreyi aşan, düz ve ' +
      'alçak bir kireçtaşı arazidir; yüzey suyu azdır, drenaj büyük ölçüde yeraltından ' +
      'gerçekleşir.',
    climateNoteTr:
      'Pasifik kıyı ovası ve kuzeydeki Petén alçak ovaları yıl boyunca sıcak ve nemli bir ' +
      'iklime sahiptir. Orta yükseklikteki dağlık bölge, "ebedi bahar" olarak tanımlanan ' +
      "ılıman bir iklimle bilinir — başkent Guatemala Şehri'nde yıllık sıcaklık farkı " +
      'azdır. Kuzeybatıdaki Cuchumatanes sıradağlarının yüksek kesimlerinde ise kışın ' +
      'donlar ve hatta kar görülebilir. Ülkenin doğu uçlarında, Karayip nemi dağlarla ' +
      'kesildiği için daha kurak ve sıcak bir iklim hakimdir.',
    hydrographyNoteTr:
      'Batı dağlarından doğan Motagua, doğuya akarak yaklaşık 480 kilometre sonra Karayip ' +
      "Denizi'ne ulaşır ve ülkenin en uzun nehridir; aşağı yatağında Honduras sınırının bir " +
      "bölümünü de çizer. Kuzeydoğuda, Polochic Nehri'nin beslediği Izabal Gölü ülkenin en " +
      "büyük gölüdür ve dar Río Dulce boğazı aracılığıyla Karayip Denizi'ne bağlanır. " +
      "Kuzeyde, Petén'in düz kireçtaşı arazisinden geçen Usumacinta Nehri, aşağı yatağında " +
      'Meksika sınırının önemli bir bölümünü oluşturur ve bölgenin en büyük akarsu ' +
      'sistemlerinden biridir.',
  },
  {
    isoCode: 'HN',
    isoCodeAlpha3: 'HND',
    nameTr: 'Honduras',
    nameEn: 'Honduras',
    slugTr: 'honduras',
    slugEn: 'honduras',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 11_005_850,
    populationYear: null,
    areaKm2: 111_890,
    capitalNameTr: 'Tegusigalpa',
    capitalNameEn: 'Tegucigalpa',
    capitalLatitude: 14.0723,
    capitalLongitude: -87.1921,
    neighborIsoCodes: ['GT', 'SV', 'NI'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Honduras Lempirası',
    currencyCode: 'HNL',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
    introTr:
      "Honduras, Orta Amerika'da hem Karayip hem de Büyük Okyanus kıyısına sahip ülkelerden " +
      'biridir: kuzeyde 700 kilometrelik bir Karayip kıyı şeridi uzanırken, güneyde Fonseka ' +
      'Körfezi üzerinden yalnızca 153 kilometrelik dar bir Büyük Okyanus kıyısına açılır. Ülke ' +
      'topraklarının büyük bölümü dağlık ve engebelidir, düzlükler yalnızca kıyı şeritlerinde ve ' +
      'nehir vadilerinde görülür. Kuzey kıyısı açıklarındaki Bahía Adaları, ülkenin dalış ve ' +
      'kıyı turizminin merkezidir.',
    landformNoteTr:
      "Ülkenin en yüksek noktası, batıdaki Lempira Departmanı'nda yükselen 2.870 metrelik Cerro " +
      "Las Minas'tır; zirve ve çevresindeki 266 kilometrekarelik alan Celaque Ulusal Parkı " +
      'sınırları içinde korunur. Dağlık iç kesim, rakıma göre üç farklı iklim-arazi kuşağına ' +
      'ayrılır: 1.000 metrenin altında sıcak tierra caliente, 1.000-2.000 metre arası ılıman ' +
      'tierra templada, 2.000 metrenin üzerinde ise serin tierra fría. Başkent Tegusigalpa, ' +
      '1.000 metre rakımdaki bir vadide kurulu olması nedeniyle bu ılıman kuşağın tipik bir ' +
      'örneğidir.' +
      '\n\n' +
      'Kuzey kıyısı açıklarındaki Roatán, Utila ve Guanaja adalarından oluşan Bahía Adaları, ' +
      "Mezoamerika Resif Sistemi'nin bir parçasıdır; bu sistem, Büyük Set Resifi'nden sonra " +
      'dünyanın en büyük ikinci mercan resif ağıdır.',
    climateNoteTr:
      "Honduras'ın iklimi kıyı ve iç kesimler arasında belirgin biçimde farklılaşır. Karayip " +
      'kıyısı yıl boyunca sıcak ve nemli kalırken, Fonseka Körfezi çevresindeki Büyük Okyanus ' +
      'kıyısında Kasım-Nisan arası belirgin bir kurak mevsim yaşanır. İç kesimlerdeki yüksek ' +
      'vadiler, rakımın etkisiyle kıyı ovalarına göre çok daha ılımandır. Ülke Karayip kasırga ' +
      'kuşağının içinde yer alır; kuzey kıyısı zaman zaman tropikal fırtına ve kasırga etkisi ' +
      'altında kalır.',
    hydrographyNoteTr:
      'Ülkenin en uzun nehirlerinden Ulúa Nehri, kuzeydeki verimli ovaları sulayarak Karayip ' +
      "Denizi'ne dökülür; kollarıyla birlikte ülke topraklarının yaklaşık üçte birini sular. " +
      'Chamelecón, Aguán, Plátano ve Patuca gibi diğer büyük nehirler de kuzey kıyısına paralel ' +
      'havzalarda akar. Doğudaki La Mosquitia bölgesinde, Patuca ve Plátano nehirlerinin ' +
      'çevresinde geniş ve seyrek nüfuslu yağmur ormanı ile sulak alanlar uzanır.',
  },
  {
    isoCode: 'NI',
    isoCodeAlpha3: 'NIC',
    nameTr: 'Nikaragua',
    nameEn: 'Nicaragua',
    slugTr: 'nikaragua',
    slugEn: 'nicaragua',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 7_007_502,
    populationYear: null,
    areaKm2: 120_340,
    capitalNameTr: 'Managua',
    capitalNameEn: 'Managua',
    capitalLatitude: 12.1364,
    capitalLongitude: -86.2514,
    neighborIsoCodes: ['HN', 'CR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Nikaragua Kordobası',
    currencyCode: 'NIO',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "15 Eylül 1821'de İspanya'dan bağımsız oldu (ortak Orta Amerika bildirgesiyle).",
    introTr:
      "Nikaragua, Orta Amerika'nın yüzölçümce en büyük ülkesidir; buna karşın nüfus yoğunluğu " +
      'bölgede düşük seviyededir. Ülkenin batı yarısını volkanik bir sıradağ ve iki büyük göl — ' +
      'Managua ve Nikaragua Gölleri — kaplarken, doğu yarısı seyrek nüfuslu, alçak ve ormanlık ' +
      "Mosquito Kıyısı'ndan oluşur. Bu iki bölge arasındaki nüfus ve altyapı farkı, ülkenin " +
      'coğrafi kimliğinin temel eksenini oluşturur.',
    landformNoteTr:
      "Ülkenin en yüksek noktası, kuzeyde Honduras sınırındaki Dipilto ve Jalapa Sıradağı'nda " +
      "yükselen 2.085 metrelik Mogotón Tepesi'dir. Batı Nikaragua'yı boydan boya kateden " +
      'volkanik hat üzerinde yirmiye yakın etkin ya da sönmüş volkan sıralanır. Nikaragua ' +
      "Gölü'nün ortasında yükselen Ometepe Adası, biri hâlâ etkin olan 1.610 metrelik Concepción " +
      've sönmüş 1.394 metrelik Maderas volkanlarının dar bir kıstakla birleşmesinden oluşur; ' +
      'ada genellikle dünyanın bir tatlı su gölü içindeki en büyük volkanik ada toprağı olarak ' +
      'anılır.',
    climateNoteTr:
      "Nikaragua'da tropikal iklim egemendir, ancak Karayip ve Büyük Okyanus kıyıları arasında " +
      'belirgin bir yağış farkı vardır. Doğudaki Karayip kıyısı ve Mosquito Kıyısı yıl boyunca ' +
      'bol yağış alır; Bluefields kenti yılda ortalama 2.700 milimetrenin üzerinde yağışla ' +
      'ülkenin en yağışlı yerleşimlerinden biridir. Batıdaki Büyük Okyanus kıyısında ise ' +
      'Kasım-Nisan arası belirgin bir kurak mevsim yaşanır, ticaret rüzgarları bu dönemde ' +
      'serinletici bir etki yaratır.',
    hydrographyNoteTr:
      'Ülkenin en büyük gölü olan Nikaragua Gölü (Cocibolca), 8.264 kilometrekarelik ' +
      "yüzölçümüyle Orta Amerika'nın en büyük tatlı su gölüdür; gölde yaşayan boğa " +
      'köpekbalıkları, okyanusla göl arasında haftalar içinde gidip gelebilen, tatlı suya uyum ' +
      'sağlamış nadir popülasyonlardan biridir. Göl doğuda San Juan Nehri aracılığıyla Karayip ' +
      "Denizi'ne boşalır; bu 192 kilometrelik nehir, uzun bir bölümünde Kosta Rika sınırını da " +
      "belirler. Daha küçük Managua Gölü (Xolotlán), Tipitapa Nehri ile Nikaragua Gölü'ne " +
      'bağlanır.',
  },
  {
    isoCode: 'PA',
    isoCodeAlpha3: 'PAN',
    nameTr: 'Panama',
    nameEn: 'Panama',
    slugTr: 'panama',
    slugEn: 'panama',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Orta Amerika',
    population: 4_571_189,
    populationYear: null,
    areaKm2: 74_180,
    capitalNameTr: 'Panama Şehri',
    capitalNameEn: 'Panamá',
    capitalLatitude: 8.9824,
    capitalLongitude: -79.5199,
    neighborIsoCodes: ['CR', 'CO'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Panama Balboası',
    currencyCode: 'PAB',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "Kolombiya'dan 3 Kasım 1903'te ayrıldı (daha önce 28 Kasım 1821'de İspanya'dan bağımsızlık kazanıp Gran Kolombiya'ya katılmıştı).",
    introTr:
      'Panama, Kuzey ve Güney Amerika kıtalarını birbirine bağlayan dar bir kara köprüsü ' +
      '(kıstak) üzerinde yer alır; batıda Kosta Rika, doğuda Kolombiya ile komşudur. ' +
      "Ülkenin ortasından geçen Panama Kanalı, Atlas ve Büyük Okyanus'u birbirine bağlar ve " +
      'dünya deniz ticaretinin en önemli geçitlerinden biridir. Doğudaki Darién bölgesi, ' +
      'yol ve köprü bulunmayan yoğun bir yağmur ormanıyla kaplıdır — Amerika kıtalarını ' +
      "uçtan uca bağlayan Pan-Amerikan Otoyolu'nun tek kesintiye uğradığı yer burasıdır.",
    landformNoteTr:
      'Kosta Rika sınırından başlayıp ülkenin ortasına kadar uzanan Cordillera Central, ' +
      "Orta Amerika'nın ana dağ sisteminin güney ucudur ve Panama'nın tek büyük " +
      'sıradağıdır. Ülkenin en yüksek noktası, bu sıradağ üzerindeki 3.474 metrelik Volcán ' +
      "Barú'dur; son patlamasının üzerinden yüzyıllar geçmiş olsa da jeologlar onu hâlâ " +
      'etkin bir stratovolkan olarak sınıflandırıyor. Doğuda, Kolombiya sınırına kadar ' +
      'uzanan Darién bölgesi alçak, sarp ve yoğun ormanlıktır; bu coğrafya bölgeyi kara ' +
      "yoluyla neredeyse geçilmez kılar. Ülke boyunca 500'e yakın nehir, dar kıstağı kuzey " +
      've güney kıyılarına bağlar.',
    climateNoteTr:
      "Panama'da yıl boyunca sıcaklık farkı azdır; iklimi asıl belirleyen unsur yağış " +
      'rejimidir. Nisan-Aralık arasındaki yağışlı mevsimde neredeyse tüm yıllık yağış ' +
      'düşer; Ocak-Nisan arasındaki kısa kurak dönem ise özellikle Pasifik kıyısında ' +
      'belirgindir. Karayip kıyısında yağış daha bol ve daha az mevsimsel dağılımlıdır, ' +
      "kurak dönem burada zayıf biçimde hissedilir. Panama Kanalı'nın işleyişi doğrudan bu " +
      'yağış rejimine bağlıdır — kanaldaki gölleri besleyen suyun neredeyse tamamı ' +
      'yağmurdan gelir.',
    hydrographyNoteTr:
      "Kanal havzasının en büyük nehri olan Chagres, Gatún Barajı ile setlenerek 1912'de " +
      "Gatún Gölü'nü oluşturmuştur; bu göl kanal boyunca gemilerin geçişini sağlayan " +
      'yükseltilmiş su yolunun büyük bölümünü kapsar ve halen ülkenin en büyük su ' +
      'kütlesidir. Karayip kıyısına akan yaklaşık 150 nehrin en önemlisi Chagres iken, ' +
      "Pasifik tarafında bu rolü, Darién'de doğup 230 kilometre boyunca güneye akan Tuira " +
      'Nehri üstlenir; havza büyüklüğü ve debisiyle ülkenin en büyük nehri budur, ülkenin ' +
      "en uzun akarsuyu ise Tuira'nın bir kolu olan Chucunaque'dir. İki kıyıya akan " +
      "nehirlerin bu şekilde ayrışması, Cordillera Central'in su ayrım hattı olarak işlev " +
      'görmesinden kaynaklanır.',
  },
  {
    isoCode: 'AG',
    isoCodeAlpha3: 'ATG',
    nameTr: 'Antigua ve Barbuda',
    nameEn: 'Antigua and Barbuda',
    slugTr: 'antigua-ve-barbuda',
    slugEn: 'antigua-and-barbuda',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 94_209,
    populationYear: null,
    areaKm2: 440,
    capitalNameTr: "Saint John's",
    capitalNameEn: "Saint John's",
    capitalLatitude: 17.1274,
    capitalLongitude: -61.8468,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "1 Kasım 1981'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'BS',
    isoCodeAlpha3: 'BHS',
    nameTr: 'Bahamalar',
    nameEn: 'Bahamas',
    slugTr: 'bahamalar',
    slugEn: 'bahamas',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 403_033,
    populationYear: null,
    areaKm2: 10_010,
    capitalNameTr: 'Nassau',
    capitalNameEn: 'Nassau',
    capitalLatitude: 25.0343,
    capitalLongitude: -77.3963,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Bahama Doları',
    currencyCode: 'BSD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "10 Temmuz 1973'te Birleşik Krallık'tan bağımsız oldu.",
    introTr:
      "Bahamalar, Karayip Denizi'nde değil Atlantik Okyanusu'nda, Küba'nın ve Florida'nın " +
      "kuzeyinde yer alan bir takımadadır; 700'den fazla ada ve 2.000'den fazla küçük kayalık " +
      'adacıktan (cay) oluşur, bunların yalnızca otuz kadarı kalıcı olarak yerleşiktir. Ülke, ' +
      'karbonat kayaçlardan oluşan sığ deniz platformları — Büyük ve Küçük Bahama Bankaları — ' +
      'üzerine kuruludur. Adaların hiçbiri volkanik kökenli değildir; tamamı, milyonlarca yıl ' +
      'boyunca sığ tropikal denizlerde birikmiş mercan ve kireçtaşı katmanlarından oluşur.',
    landformNoteTr:
      "Bahamalar'ın tamamı alçak ve düzdür; ülkenin en yüksek noktası, Cat Adası'ndaki yalnızca " +
      "63 metrelik Mount Alvernia'dır — bu rakım, egemen bir ülkenin en yüksek noktası olarak " +
      'dünyanın en düşük değerlerinden biridir. Kireçtaşı zemin, yağış suyunun kimyasal ' +
      'aşınmasıyla yer yer çökerek adalar boyunca çok sayıda mavi delik (blue hole) ' +
      "oluşturmuştur. Long Adası açıklarındaki Dean's Mavi Deliği 202 metre derinliğindedir; " +
      "uzun yıllar dünyanın en derin mavi deliği kabul edilmiştir. 2018'de ölçülen Çin'deki 301 " +
      "metrelik Dragon Hole ve 2024'te keşfedilen Meksika kıyısındaki 420 metreden derin Taam " +
      "Ja', bu unvanı geride bırakmıştır. Dean's Mavi Deliği bugün de dünyanın önde gelen " +
      'serbest dalış noktalarından biridir.',
    climateNoteTr:
      "Bahamalar'da tropikal ve yarı tropikal iklim arasında bir geçiş yaşanır; kuzeydeki adalar " +
      "Florida'ya yakınlığı nedeniyle güneydekilere göre biraz daha serin kışlar geçirir. Ülke " +
      'Atlantik kasırga kuşağının tam merkezinde yer alır ve Haziran-Kasım arası kasırga ' +
      'mevsiminde düzenli risk altındadır. Sığ banka suları çevredeki derin okyanus sularına ' +
      'göre daha hızlı ısınıp soğur; bu fark adalar çevresindeki deniz yüzeyi sıcaklıklarını da ' +
      'etkiler.',
    hydrographyNoteTr:
      "Bahamalar'da Andros Adası dışında akarsu bulunmaz; kireçtaşı zemin yağış suyunu hızla " +
      'yeraltına geçirdiğinden yüzeyde kalıcı bir nehir ağı gelişmemiştir. Tatlı su ihtiyacı ' +
      'büyük ölçüde yeraltı su mercekleri (freshwater lens) ve yağmur suyu toplama sistemleriyle ' +
      "karşılanır. Andros Adası'nın iç kesimlerinde, dünyanın en yoğun mavi delik kümelerinden " +
      'birine ev sahipliği yapan geniş sulak alanlar ve iç göller bulunur.',
  },
  {
    isoCode: 'BB',
    isoCodeAlpha3: 'BRB',
    nameTr: 'Barbados',
    nameEn: 'Barbados',
    slugTr: 'barbados',
    slugEn: 'barbados',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 282_623,
    populationYear: null,
    areaKm2: 430,
    capitalNameTr: 'Bridgetown',
    capitalNameEn: 'Bridgetown',
    capitalLatitude: 13.1132,
    capitalLongitude: -59.5988,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Barbados Doları',
    currencyCode: 'BBD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "30 Kasım 1966'da Birleşik Krallık'tan bağımsız oldu (2021'de cumhuriyete geçti).",
    introTr:
      "Barbados, Küçük Antiller'in çoğu adasından farklı olarak volkanik kökenli değildir; " +
      "yüzeyinin %85'ten fazlası mercan kökenli kireçtaşından oluşur. Karayip ada yayının en " +
      'doğusunda, diğer adalardan yaklaşık 160 kilometre uzakta, açık Atlantik sularına bakan ' +
      'izole bir konumdadır. Ülke düz ve hafif dalgalı bir arazi yapısına sahiptir, iç ' +
      'kesimlerdeki tepeler bile alçak kalır.',
    landformNoteTr:
      'Ülkenin en yüksek noktası, kuzey-orta kesimdeki Aziz Andrew bölgesinde yükselen 336 ' +
      "metrelik Mount Hillaby'dir. Kireçtaşı zemin, yüzyıllar boyunca yağış suyunun " +
      'aşındırmasıyla adanın ortasında Harrison Mağarası gibi geniş yeraltı boşlukları ' +
      'oluşturmuştur; bu mağara sistemi sarkıt ve dikitlerle kaplı galerileri ve yeraltı ' +
      'akarsularıyla tanınır. Kıyı boyunca uzanan mercan resif kalıntıları, adanın deniz kökenli ' +
      'geçmişinin yüzeydeki izleridir.',
    climateNoteTr:
      "Barbados'ta tropikal bir iklim egemendir; Aralık-Mayıs arası kurak, Haziran-Kasım arası " +
      'ise yağışlı mevsim olarak ayrılır. Ada, Karayip kasırga kuşağının doğu ucunda yer ' +
      "almasına karşın komşu adalara göre çarpıcı biçimde az kasırga alır: 1955'teki Kasırga " +
      "Janet'in ardından, 2021'de Kasırga Elsa vurana kadar 66 yıl boyunca adaya doğrudan bir " +
      'kasırga kaydedilmemiştir. Kuzeydoğu ticaret rüzgarları yıl boyunca eserek adanın ' +
      'sıcaklığını dengeler.',
    hydrographyNoteTr:
      "Barbados'ta kalıcı akarsu bulunmaz; kireçtaşı zemin yağış suyunu hızla yeraltına " +
      'geçirdiğinden yüzey akışı gelişmemiştir. Bunun yerine adayı boydan boya kesen derin ' +
      'vadiler (gully), yağmur sularını kıyıya doğru yönlendirir. Yeraltına sızan su, adanın ' +
      'içme suyu ihtiyacının neredeyse tamamını karşılayan geniş bir kireçtaşı akiferini besler.',
  },
  {
    isoCode: 'CU',
    isoCodeAlpha3: 'CUB',
    nameTr: 'Küba',
    nameEn: 'Cuba',
    slugTr: 'kuba',
    slugEn: 'cuba',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 10_937_203,
    populationYear: null,
    areaKm2: 103_800,
    capitalNameTr: 'Havana',
    capitalNameEn: 'Havana',
    capitalLatitude: 23.1136,
    capitalLongitude: -82.3666,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Küba Pesosu',
    currencyCode: 'CUP',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr:
      "İspanya egemenliğinin ardından 20 Mayıs 1902'de bağımsız cumhuriyet ilan edildi.",
    introTr:
      "Karayipler'in yüzölçümce en büyük adası olan Küba'nın kara sınırı yoktur. Kuzeyinde " +
      'Florida Boğazı, kuzeybatısında Meksika Körfezi, güneyinde ise Karayip Denizi yer ' +
      'alır. Ülke toprağının yaklaşık üçte ikisi düz ya da hafif dalgalı ovalardan oluşur, ' +
      'dağlık kesimler adanın belirli bölgelerinde toplanmıştır.',
    landformNoteTr:
      "Küba'nın dağlık arazisi üç ayrı kümede toplanır: güneydoğuda, ülkenin en yüksek " +
      "noktası olan 1.974 metrelik Pico Turquino'yu barındıran Sierra Maestra; orta " +
      'kesimde Sierra del Escambray; batıda ise Sierra del Rosario. Batıdaki Viñales ' +
      "Vadisi, dik yamaçlı kireçtaşı tepeleri olan mogote'leriyle Küba'nın en tanınmış " +
      'karst manzarasını oluşturur.',
    climateNoteTr:
      "Köppen sınıflandırmasında Aw kodlu tropikal savan iklimi, Küba'nın büyük bölümünde " +
      "görülür. Sierra Maestra ve Sierra del Rosario'nun rüzgar alan yamaçlarında bu iklim, " +
      'daha nemli bir muson ya da yağmur ormanı karakterine yaklaşır. Buna karşılık ' +
      "Guantánamo Körfezi çevresi, Sierra Maestra'nın yağış gölgesinde kaldığı için yarı " +
      'kurak bir iklime sahiptir. Kasım-Nisan arasında kurak, Mayıs-Ekim arasında yağışlı ' +
      'mevsim yaşanır; Haziran-Kasım kasırga sezonu adayı düzenli olarak etkiler.',
    hydrographyNoteTr:
      "Sierra Maestra'da doğan Cauto Nehri, kuzeybatıya akarak 370 kilometre sonra denize " +
      'ulaşır — ülkenin en uzun nehridir. Debi bakımından en yüksek ve en bakir ' +
      "nehirlerden biri olan Toa Nehri de yine doğu Küba'da yer alır. Adanın dar ve uzun " +
      "biçimi yüzünden Küba'nın nehirleri genellikle kısa kalır, çoğu da gemi " +
      'taşımacılığına elverişli değildir. Batıdaki karst bölgelerinde ise yüzey nehirleri ' +
      'yerine yeraltı nehir ve mağara sistemleri yaygındır.',
  },
  {
    isoCode: 'DM',
    isoCodeAlpha3: 'DMA',
    nameTr: 'Dominika',
    nameEn: 'Dominica',
    slugTr: 'dominika',
    slugEn: 'dominica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 65_871,
    populationYear: null,
    areaKm2: 750,
    capitalNameTr: 'Roseau',
    capitalNameEn: 'Roseau',
    capitalLatitude: 15.3092,
    capitalLongitude: -61.3794,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "3 Kasım 1978'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'DO',
    isoCodeAlpha3: 'DOM',
    nameTr: 'Dominik Cumhuriyeti',
    nameEn: 'Dominican Republic',
    slugTr: 'dominik-cumhuriyeti',
    slugEn: 'dominican-republic',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 11_520_487,
    populationYear: null,
    areaKm2: 48_198,
    capitalNameTr: 'Santo Domingo',
    capitalNameEn: 'Santo Domingo',
    capitalLatitude: 18.4861,
    capitalLongitude: -69.9312,
    neighborIsoCodes: ['HT'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Dominik Pesosu',
    currencyCode: 'DOP',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "27 Şubat 1844'te Haiti'den bağımsız oldu.",
    introTr:
      "Dominik Cumhuriyeti, Büyük Antiller'deki Hispaniola adasının doğu üçte ikisini " +
      "kaplar; adanın batı kesimini Haiti ile paylaşır ve bu, Karayipler'deki 13 ada " +
      'devleti arasında kara sınırı bulunan tek çifttir. Ülkenin kuzeyinde Atlas Okyanusu, ' +
      'güneyinde ise Karayip Denizi yer alır. Topraklarının ortasından geçen dağ sıraları, ' +
      'adayı ve ülkeyi birbirinden farklı iklim ve arazi bölgelerine ayırır.',
    landformNoteTr:
      "Ülkenin ortasından geçen Cordillera Central, yalnızca Dominik Cumhuriyeti'nin değil, " +
      "tüm Karayipler'in en yüksek dağ sırasıdır; 3.101 metrelik Pico Duarte, adanın ve " +
      "Karayipler'in en yüksek noktasıdır. Bu zirveden yalnızca 85 kilometre uzaklıkta, " +
      'adanın en alçak noktası olan Enriquillo Gölü bulunur — deniz seviyesinin 46 metre ' +
      'altında kalan, tuzlu sulu kapalı bir göl. Kuzeyde, Cordillera Central ile kıyı ' +
      'boyunca uzanan Cordillera Septentrional arasında, verimli ve geniş Cibao Vadisi yer ' +
      'alır; ülkenin en önemli tarım bölgesidir.',
    climateNoteTr:
      'Ülke genelinde tropikal bir iklim hakimdir; Aralık-Nisan arasında görece kurak, ' +
      'Mayıs-Kasım arasında ise yağışlı bir dönem yaşanır. Kuzeydoğudan esen ticaret ' +
      'rüzgarları adanın kuzey ve doğu kesimlerine bol yağış taşır — buralarda yıllık yağış ' +
      '1.350 milimetreye ulaşabilirken, dağların rüzgar gölgesinde kalan batı kesiminde 430 ' +
      'milimetrenin altına iner. Haziran-Kasım arasındaki kasırga mevsiminde, özellikle ' +
      'Ağustos-Ekim döneminde, Atlas Okyanusu kökenli tropik fırtınalar ülkeyi ' +
      'etkileyebilir.',
    hydrographyNoteTr:
      'Cordillera Central, ülkenin üç ana nehir sisteminin de kaynağını oluşturur: kuzeye ' +
      "akan Yaque del Norte, kuzeydoğuya akıp Cibao Vadisi'ni sulayan Yuna ve güneye akan " +
      "Yaque del Sur. Yuna Nehri, Samaná Körfezi'ne dökülmeden önce Cibao Vadisi'nin " +
      "verimli topraklarını besler. Enriquillo Gölü'ne akan akarsular ise denize ulaşamaz; " +
      'havza, adanın diğer nehir sistemlerinden bağımsız, kapalı bir drenaj sistemidir.',
  },
  {
    isoCode: 'GD',
    isoCodeAlpha3: 'GRD',
    nameTr: 'Grenada',
    nameEn: 'Grenada',
    slugTr: 'grenada',
    slugEn: 'grenada',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 117_303,
    populationYear: null,
    areaKm2: 340,
    capitalNameTr: "Saint George's",
    capitalNameEn: "Saint George's",
    capitalLatitude: 12.0561,
    capitalLongitude: -61.7488,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "7 Şubat 1974'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'HT',
    isoCodeAlpha3: 'HTI',
    nameTr: 'Haiti',
    nameEn: 'Haiti',
    slugTr: 'haiti',
    slugEn: 'haiti',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 11_906_095,
    populationYear: null,
    areaKm2: 27_560,
    capitalNameTr: 'Port-au-Prince',
    capitalNameEn: 'Port-au-Prince',
    capitalLatitude: 18.5944,
    capitalLongitude: -72.3074,
    neighborIsoCodes: ['DO'],
    officialLanguagesTr: ['Fransızca', 'Haiti Kreyolu'],
    currencyNameTr: 'Haiti Gurdu',
    currencyCode: 'HTG',
    governmentFormTr: null,
    independenceNoteTr:
      "1 Ocak 1804'te Fransa'dan bağımsız oldu (dünyanın ilk bağımsız siyah cumhuriyeti).",
    introTr:
      'Haiti, adını Taino dilinde "dağlık toprak" anlamına gelen "Ayiti" sözcüğünden alır; ülke ' +
      "topraklarının %80'den fazlası dağlık veya tepeliktir. Hispaniola adasının batı üçte " +
      'birini kaplar, adanın kalan kesimini Dominik Cumhuriyeti oluşturur; iki ülke arasındaki ' +
      "391 kilometrelik kara sınırı, Karayipler'deki 13 ada devleti arasında tek kara sınırı " +
      'örneğidir. Ülkenin dağlık yapısı tarih boyunca ulaşımı güçleştirmiş, kıyı ovalarındaki ' +
      'yerleşimlerin birbirinden görece izole gelişmesine yol açmıştır.',
    landformNoteTr:
      "Ülkenin güneyindeki yarımadayı boydan boya kateden Selle Sıradağı'nda yükselen 2.680 " +
      "metrelik Pic la Selle, Haiti'nin en yüksek noktasıdır. Kuzeyde Massif du Nord, orta " +
      "kesimde ise Karayip Denizi'ne doğru daralan bir dizi paralel sıradağ uzanır; bu dağ " +
      'dizileri arasında Cul-de-Sac ve Artibonite gibi dar ovalar yer alır. Ülkenin başlıca ' +
      'tarım alanları, bu dağlar arasındaki alüvyal ovalarda ve nehir vadilerinde toplanır.',
    climateNoteTr:
      "Haiti'de tropikal bir iklim egemendir, ancak dağlık arazi yerel iklimde büyük " +
      'farklılıklara yol açar. Kıyı ovaları yıl boyunca sıcak ve nemli kalırken, yüksek dağlık ' +
      'kesimlerde rakımın etkisiyle sıcaklıklar belirgin biçimde düşer. Ülke Karayip kasırga ' +
      'kuşağı içinde yer alır; Mayıs-Kasım arası kasırga mevsiminde şiddetli yağışlar, dağlık ' +
      'arazinin dik yamaçlarında sel ve heyelan riskini artırır.',
    hydrographyNoteTr:
      "Ülkenin en uzun nehri olan Artibonite Nehri, kaynağını komşu Dominik Cumhuriyeti'ndeki " +
      "Cordillera Central'dan alır; toplam yaklaşık 320 kilometrelik akışının büyük bölümünü " +
      "Haiti topraklarında tamamladıktan sonra Gonâve Körfezi'ne dökülür ve Hispaniola adasının " +
      'en uzun akarsuyu sayılır. Nehir üzerindeki Péligre Barajı ülkenin başlıca hidroelektrik ' +
      "kaynaklarından birini oluşturur ve aşağı Artibonite Vadisi'ndeki geniş pirinç tarımını " +
      'sular.',
  },
  {
    isoCode: 'JM',
    isoCodeAlpha3: 'JAM',
    nameTr: 'Jamaika',
    nameEn: 'Jamaica',
    slugTr: 'jamaika',
    slugEn: 'jamaica',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 2_837_077,
    populationYear: null,
    areaKm2: 10_830,
    capitalNameTr: 'Kingston',
    capitalNameEn: 'Kingston',
    capitalLatitude: 17.9712,
    capitalLongitude: -76.7936,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Jamaika Doları',
    currencyCode: 'JMD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "6 Ağustos 1962'de Birleşik Krallık'tan bağımsız oldu.",
    introTr:
      "Jamaika, Karayipler'in Küba ve Hispaniola'dan sonra üçüncü büyük adasıdır. Ülkenin iç " +
      'kesimi büyük ölçüde dağlık ve kireçtaşı araziyle kaplıdır, düzlükler yalnızca dar kıyı ' +
      'şeritlerinde bulunur. Ada Karayip kasırga kuşağının tam ortasında yer alır ve tarihi ' +
      'boyunca birçok büyük kasırgadan etkilenmiştir.',
    landformNoteTr:
      "Ülkenin doğusunda yükselen Mavi Dağlar, 2.256 metrelik Blue Mountain Peak ile Jamaika'nın " +
      'en yüksek noktasını oluşturur; bu sıradağın yüksek ve bulutlu yamaçlarında yetiştirilen ' +
      'kahve dünya çapında tanınır. Adanın batı-orta kesimini kaplayan Cockpit Country, dünyanın ' +
      'en dramatik karst arazi örneklerinden biridir; yüzlerce huni biçimli çukur ve tepecik ' +
      'birbirini izler, aralarındaki vadi ve çöküntüler yer yer onlarca metre derinliğe ulaşır. ' +
      'Bu engebeli ve erişimi güç arazi, tarihte kaçak köle topluluklarının (Maroon) sığındığı ' +
      'bir bölge olmuştur.',
    climateNoteTr:
      "Jamaika'da tropikal deniz iklimi egemendir; kıyı ovaları yıl boyunca sıcak kalırken, Mavi " +
      "Dağlar'ın yüksek kesimlerinde geceleri serin bir hava hâkimdir. Ülke Haziran-Kasım " +
      "kasırga mevsiminde düzenli risk altındadır: 1988'de adayı vuran Kasırga Gilbert, kategori " +
      "beşe ulaşan rüzgarlarıyla evlerin yaklaşık %80'ini hasara uğratmış, 500 bin kişiyi evsiz " +
      'bırakmıştır. Kuzey kıyısı, ticaret rüzgarlarına daha açık olduğundan güney kıyısına göre ' +
      'genellikle daha fazla yağış alır.',
    hydrographyNoteTr:
      "Jamaika'nın en uzun nehri, orta kesimden güneye akan 93 kilometrelik Rio Minho'dur. " +
      'Güneybatıdaki Black Nehri ise 53 kilometrelik akışıyla adanın en geniş sulak alanlarından ' +
      'birini besler ve teknelerle gezilebilen bataklık kesimleriyle tanınır. Cockpit ' +
      "Country'nin yaygın kireçtaşı arazisinde yüzey suları büyük ölçüde yeraltına sızar, bu " +
      'nedenle bölgede belirgin bir yüzey akarsu ağı gelişmemiştir.',
  },
  {
    isoCode: 'KN',
    isoCodeAlpha3: 'KNA',
    nameTr: 'Saint Kitts ve Nevis',
    nameEn: 'Saint Kitts and Nevis',
    slugTr: 'saint-kitts-ve-nevis',
    slugEn: 'saint-kitts-and-nevis',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 46_922,
    populationYear: null,
    areaKm2: 260,
    capitalNameTr: 'Baster',
    capitalNameEn: 'Basseterre',
    capitalLatitude: 17.3026,
    capitalLongitude: -62.7177,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Federal parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "19 Eylül 1983'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'LC',
    isoCodeAlpha3: 'LCA',
    nameTr: 'Saint Lucia',
    nameEn: 'Saint Lucia',
    slugTr: 'saint-lucia',
    slugEn: 'saint-lucia',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 180_149,
    populationYear: null,
    areaKm2: 610,
    capitalNameTr: 'Castries',
    capitalNameEn: 'Castries',
    capitalLatitude: 14.0101,
    capitalLongitude: -60.9875,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "22 Şubat 1979'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'VC',
    isoCodeAlpha3: 'VCT',
    nameTr: 'Saint Vincent ve Grenadinler',
    nameEn: 'Saint Vincent and the Grenadines',
    slugTr: 'saint-vincent-ve-grenadinler',
    slugEn: 'saint-vincent-and-the-grenadines',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 99_924,
    populationYear: null,
    areaKm2: 390,
    capitalNameTr: 'Kingstown',
    capitalNameEn: 'Kingstown',
    capitalLatitude: 13.1587,
    capitalLongitude: -61.2248,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Doğu Karayip Doları',
    currencyCode: 'XCD',
    governmentFormTr: 'Parlamenter monarşi (Commonwealth realm)',
    independenceNoteTr: "27 Ekim 1979'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'TT',
    isoCodeAlpha3: 'TTO',
    nameTr: 'Trinidad ve Tobago',
    nameEn: 'Trinidad and Tobago',
    slugTr: 'trinidad-ve-tobago',
    slugEn: 'trinidad-and-tobago',
    continent: Continent.NorthAmerica,
    unSubregionTr: 'Karayipler',
    population: 1_367_764,
    populationYear: null,
    areaKm2: 5_130,
    capitalNameTr: 'Port of Spain',
    capitalNameEn: 'Port of Spain',
    capitalLatitude: 10.6549,
    capitalLongitude: -61.5019,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Trinidad ve Tobago Doları',
    currencyCode: 'TTD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "31 Ağustos 1962'de Birleşik Krallık'tan bağımsız oldu (Cumhuriyet 1976).",
    introTr:
      "Trinidad ve Tobago, Karayipler'deki diğer adaların çoğundan farklı olarak volkanik " +
      'kökenli değildir; Trinidad adası jeolojik olarak Venezuela kıyısındaki Güney Amerika ' +
      'kıtasal sahanlığının bir parçasıdır ve yalnızca yaklaşık 11 kilometrelik dar bir su ' +
      'yoluyla anakaradan ayrılır. İki ana adadan oluşan ülkenin nüfusunun büyük bölümü, ' +
      "güneybatıda Port of Spain çevresinde yoğunlaşan Trinidad'da yaşar; Tobago ise " +
      'kuzeydoğuda, daha küçük ve seyrek nüfusludur.',
    landformNoteTr:
      "Trinidad'ın kuzeyinde kıyıya paralel uzanan Kuzey Sıradağları, Venezuela'daki And " +
      "Dağları'nın bir uzantısıdır; sıradağın 940 metrelik El Cerro del Aripo zirvesi ülkenin en " +
      'yüksek noktasıdır. Adanın güneybatısındaki La Brea kasabası yakınında bulunan Katran Gölü ' +
      '(Pitch Lake), dünyanın en büyük doğal asfalt yatağıdır; yaklaşık 40 hektarlık yüzeyi ' +
      'altında binlerce yıldır sürekli yenilenen katran, 19. yüzyıldan bu yana ticari olarak ' +
      "çıkarılır. Tobago'nun iç kesimini kaplayan Ana Sıradağ (Main Ridge), 1776'da koruma " +
      "altına alınmıştır ve Batı Yarımküre'nin resmi olarak korunan en eski yağmur ormanı " +
      'rezervidir.',
    climateNoteTr:
      'Trinidad ve Tobago, kuzeye 10-11 derece enlemde ve Güney Amerika kıyısına yakın konumu ' +
      'nedeniyle Karayip kasırga kuşağının büyük ölçüde dışında kalır; bölgeye ulaşan tropikal ' +
      'sistemler bu enlemde güçlenme fırsatı bulamadan geçer. Bu konum ülkeyi kuzeydeki ' +
      'komşularına göre doğrudan kasırga vuruşlarına karşı belirgin biçimde daha az savunmasız ' +
      'kılar. Ülkede yıl boyunca sıcak ve nemli tropikal bir iklim egemendir; Haziran-Aralık ' +
      'arası yağışlı, Ocak-Mayıs arası ise görece kurak bir mevsim yaşanır.',
    hydrographyNoteTr:
      "Trinidad'ın en uzun nehirlerinden Ortoire Nehri, adanın doğusunda Atlantik kıyısına " +
      'dökülür. Hacim bakımından adanın en büyük nehri olan Caroni Nehri ise başkent Port of ' +
      "Spain yakınında Caroni Bataklığı'nı besler; bu bataklık, ülkenin ulusal kuşu allık ibisin " +
      "dünyadaki en büyük tünekleme alanlarından biridir. Dağlık ve dar Tobago'da ise kısa, " +
      'hızlı akan dereler dışında büyük bir akarsu sistemi bulunmaz.',
  },
  {
    isoCode: 'AR',
    isoCodeAlpha3: 'ARG',
    nameTr: 'Arjantin',
    nameEn: 'Argentina',
    slugTr: 'arjantin',
    slugEn: 'argentina',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 45_851_378,
    populationYear: null,
    areaKm2: 2_736_690,
    capitalNameTr: 'Buenos Aires',
    capitalNameEn: 'Buenos Aires',
    capitalLatitude: -34.6037,
    capitalLongitude: -58.3816,
    neighborIsoCodes: ['CL', 'BO', 'PY', 'BR', 'UY'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Arjantin Pesosu',
    currencyCode: 'ARS',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "9 Temmuz 1816'da İspanya'dan bağımsızlığını ilan etti (süreç 25 Mayıs 1810'da başladı).",
    introTr:
      "Güney Amerika'nın (Brezilya'dan sonra) yüzölçümce ikinci büyük ülkesi olan Arjantin, " +
      'batıda And Dağları boyunca Şili ile sınırlanır. Ülke kuzeyden güneye yaklaşık 3.700 ' +
      'kilometre uzanır ve üç farklı bölgeye ayrılır: kuzeyde Gran Chaco, orta kesimde ' +
      'Pampalar, güneyde ise Patagonya.',
    landformNoteTr:
      'And Dağları, ülkenin batı sınırı boyunca uzanır ve en yüksek noktasını, 6.961 ' +
      "metrelik Aconcagua'da bulur — yalnızca Arjantin'in değil, Amerika kıtalarının ve tüm " +
      'Batı ile Güney yarımkürenin en yüksek zirvesidir. Merkezde, yaklaşık 760.000 ' +
      'kilometrekarelik geniş ve düz bir çayır olan Pampalar uzanır; batıdaki kurak Pampa ' +
      'ile doğudaki nemli Pampa arasındaki fark, bölgeyi tarım ve hayvancılığın kalbi ' +
      'haline getirir. Güneyde ise Patagonya başlar: doğusu rüzgarlı ve kurak bir ' +
      'yayla-step, batısındaki Andine kesimi ise buzullarla kaplıdır.',
    climateNoteTr:
      'Kuzeyde neredeyse tropikal bir iklim görülürken, Buenos Aires ve Pampalar bölgesinde ' +
      'ılıman bir iklim hakimdir. Daha güneyde, Patagonya soğuk ve sürekli rüzgarlı bir ' +
      "iklime sahiptir; ülkenin en güneyindeki Ateş Ülkesi'nde ise subpolar koşullar " +
      "yaşanır. Kuzeyden güneye 3.700 kilometreyi bulan bu uzunluk, Arjantin'e kıtanın en " +
      'geniş iklim yelpazelerinden birini kazandırır.',
    hydrographyNoteTr:
      "Ülkenin en uzun nehri, Brezilya'da doğup güneye akan ve toplamda yaklaşık 4.880 " +
      "kilometreye ulaşan Paraná'dır; Uruguay Nehri ile birleştiği noktada geniş bir haliç " +
      "olan Río de la Plata'yı oluşturur. Gran Chaco'da, Paraguay ve Paraná'nın kolları " +
      "olan Pilcomayo ve Bermejo nehirleri akar. Patagonya'da ise Colorado ve Negro " +
      "nehirleri, And Dağları'ndan doğup Atlantik'e ulaşan başlıca su yollarıdır.",
  },
  {
    isoCode: 'BO',
    isoCodeAlpha3: 'BOL',
    nameTr: 'Bolivya',
    nameEn: 'Bolivia',
    slugTr: 'bolivya',
    slugEn: 'bolivia',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 12_581_843,
    populationYear: null,
    areaKm2: 1_083_300,
    capitalNameTr: 'La Paz',
    capitalNameEn: 'La Paz',
    capitalLatitude: -16.5,
    capitalLongitude: -68.15,
    neighborIsoCodes: ['PE', 'CL', 'AR', 'PY', 'BR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Bolivya Bolivianosu',
    currencyCode: 'BOB',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "6 Ağustos 1825'te İspanya'dan bağımsız oldu.",
    introTr:
      "Bolivya, Güney Amerika'nın ortasında, Peru, Şili, Arjantin, Paraguay ve Brezilya ile " +
      'komşu, kıtanın denize kıyısı olmayan iki ülkesinden biridir. Ülke toprakları üç ana ' +
      "coğrafi bölgeye ayrılır: batıda And Dağları'nın yüksek platosu Altiplano, ortada " +
      "nemli geçiş bölgesi Yungas, doğuda ise alçak ovalar (Llanos) ile Gran Chaco'nun " +
      'kuzey ucu. Nüfusun büyük bölümü, deniz seviyesinden ortalama 3.700 metre ' +
      "yükseklikteki Altiplano'da ve çevresindeki vadilerde yaşar.",
    landformNoteTr:
      'Bolivya toprakları, birbirine paralel uzanan iki And Dağları sırası arasında ' +
      'sıkışmıştır: batıda, Şili sınırını izleyen ve volkanik zirveler barındıran ' +
      'Cordillera Occidental; doğuda ise daha eski kristalen kayaçlardan oluşan Cordillera ' +
      'Oriental. Ülkenin en yüksek noktası, Cordillera Occidental üzerindeki 6.542 metrelik ' +
      "Sajama Yanardağı'dır. İki sıradağ arasında, ortalama 3.700 metre yükseklikte uzanan " +
      'geniş bir plato olan Altiplano yer alır; platonun güneyinde, eski göllerin ' +
      'kurumasıyla oluşan ve 10.000 kilometrekareyi aşan, dünyanın en büyük tuz düzlüğü ' +
      'Salar de Uyuni bulunur.' +
      '\n\n' +
      "Altiplano'nun kuzeyinde, Peru ile paylaşılan Titicaca Gölü'nün Bolivya kıyısı " +
      'uzanır; 3.812 metre yükseklikteki bu göl dünyanın seyrüsefere elverişli en yüksek ' +
      "gölüdür ve yüzeyinin yaklaşık %40'ı Bolivya sınırları içinde kalır. Cordillera " +
      "Oriental'in doğu yamaçlarında nemli ve ormanlık Yungas bölgesi başlar; ülkenin " +
      "doğusundaki geniş ovalar (Llanos) Amazon Havzası'na, güneydeki Gran Chaco'nun kuzey " +
      'ucu ise yarı-kurak bir düzlüğe açılır.',
    climateNoteTr:
      "Altiplano'da rakımın da etkisiyle serin ve yarı-kurak bir iklim hakimdir; yıllık " +
      'ortalama sıcaklık 5-15 santigrat derece arasında değişir, yağış çoğunlukla ' +
      "Aralık-Mart döneminde düşer ve yılda 500 milimetreyi geçmez. Cordillera Oriental'in " +
      "doğu yamaçlarındaki Yungas'a Amazon Havzası'ndan gelen nemli hava kütleleri ulaşır; " +
      'sis sık görülür, yağış yılda 1.500 milimetreye kadar çıkabilir. Doğudaki alçak ' +
      'Llanos bölgesinde ise sıcaklık yıl boyunca 25-30 santigrat derece bandında seyreder, ' +
      'yağış birçok kesimde 2.000 milimetreyi aşar ve yağmur ormanı sektörlerinde 4.000 ' +
      'milimetreye ulaşabilir.',
    hydrographyNoteTr:
      "Titicaca Gölü'nün fazla suyu, Desaguadero Nehri aracılığıyla güneye, sığ ve tuzlu " +
      "Poopó Gölü'ne akar; bu havza denize bağlantısı olmayan kapalı bir drenaj sistemidir. " +
      'Poopó son derece sığ olduğu için yüzey alanı yıldan yıla büyük ölçüde değişir — göl ' +
      "2015-2016'da tamamen kurumuş, o tarihten bu yana ancak kısmi ve kırılgan bir düzeyde " +
      "su tutabiliyor. Doğudaki Llanos'ta Mamoré ve Beni nehirleri, And Dağları'ndan inen " +
      "suları toplayarak kuzeye, Brezilya'daki Madeira Nehri üzerinden Amazon sistemine " +
      "taşır. Güneydoğuda, Gran Chaco'nun kuzey ucundan geçen Pilcomayo Nehri Bolivya And " +
      "Dağları'nda doğar ve güneydoğuya akarak Paraguay Nehri'ne katılır.",
  },
  {
    isoCode: 'BR',
    isoCodeAlpha3: 'BRA',
    nameTr: 'Brezilya',
    nameEn: 'Brazil',
    slugTr: 'brezilya',
    slugEn: 'brazil',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 212_812_405,
    populationYear: null,
    areaKm2: 8_358_140,
    capitalNameTr: 'Brazilya',
    capitalNameEn: 'Brasília',
    capitalLatitude: -15.7939,
    capitalLongitude: -47.8828,
    neighborIsoCodes: ['UY', 'AR', 'PY', 'BO', 'PE', 'CO', 'VE', 'GY', 'SR', 'FR'],
    officialLanguagesTr: ['Portekizce'],
    currencyNameTr: 'Brezilya Reali',
    currencyCode: 'BRL',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr: "7 Eylül 1822'de Portekiz'den bağımsız oldu.",
    introTr:
      "Güney Amerika kıtasının yaklaşık %47'sini kaplayan Brezilya, kıtanın yüzölçümce en " +
      'büyük ülkesidir. Şili ve Ekvador dışındaki her Güney Amerika ülkesiyle kara sınırı ' +
      "paylaşır. Doğuda Atlantik Okyanusu'na kıyısı vardır; kuzeyini Amazon Havzası, güney " +
      've orta kesimini ise geniş bir yayla kaplar.',
    landformNoteTr:
      'Ülkenin güney ve orta kesimini, ortalama 1.000 metre yükseklikteki Brezilya Yaylası ' +
      '(Planalto Brasileiro) kaplar; bu yaylanın karakteristik bitki örtüsü, geniş bir ' +
      "savan ekosistemi olan Cerrado'dur. Kuzeyde ise düz ve alçak Amazon Havzası uzanır, " +
      "dünyanın en büyük yağmur ormanına ev sahipliği yapar. Brezilya'nın en yüksek " +
      "noktası, Amazonas eyaletindeki İmeri Dağları'nda yükselen 2.995 metrelik Pico da " +
      "Neblina'dır; bu zirve, ülkenin en dağlık bölgesi olan güneydoğu değil, Amazon " +
      'ormanının derinlikleri içinde yer alır. Ülkenin batı-orta kesiminde, Paraguay ' +
      "Nehri'nin taşkın ovasında yer alan Pantanal, dünyanın en büyük tropikal sulak " +
      'alanlarından biridir.',
    climateNoteTr:
      "Brezilya beş farklı iklim bölgesine ayrılır. Amazon Havzası'nda yıl boyunca sıcak " +
      've nemli kalan ekvatoral iklim egemendir. Kuzeydoğu kıyısı boyunca, belirgin ' +
      'yağışlı ve kurak dönemleri olan tropikal iklim görülür; kıyının hemen iç kesiminde, ' +
      'Sertão olarak bilinen bölgede ise yarı kurak bir iklim hakimdir. Brezilya ' +
      "Yaylası'nın iç kesimlerinde Cerrado'nun tropikal yükseklik iklimi, güneyde ise dört " +
      'mevsimin belirgin olduğu ılıman subtropikal iklim yaşanır.',
    hydrographyNoteTr:
      'Amazon Nehri, debi bakımından dünyanın en büyük nehridir; saniyede yaklaşık 209.000 ' +
      "metreküp su Atlantik'e boşalır, bu da dünya okyanuslarına giren nehir suyunun " +
      "yaklaşık beşte biri anlamına gelir. 1.100'den fazla kolu vardır, bunlardan 17'si " +
      '1.500 kilometreden uzundur. En büyük kollarından biri olan 2.230 kilometrelik Rio ' +
      "Negro, Manaus yakınlarında Solimões Nehri'yle birleşir — bu birleşmeden sonra nehir " +
      "Brezilya'da Amazon adını alır. İki kolun farklı renkteki suları, birleşme " +
      'noktasından sonra uzun süre karışmadan yan yana akar; bu görüntü ' +
      '"Encontro das Águas" (suların buluşması) adıyla bilinir. Güneyde Paraná, Paraguay ' +
      "ve Uruguay nehirleri, Brezilya Yaylası'nda doğup güneye akarak Río de la Plata " +
      'havzasını besler.',
  },
  {
    isoCode: 'CL',
    isoCodeAlpha3: 'CHL',
    nameTr: 'Şili',
    nameEn: 'Chile',
    slugTr: 'sili',
    slugEn: 'chile',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 19_859_921,
    populationYear: null,
    areaKm2: 742_832,
    capitalNameTr: 'Santiago',
    capitalNameEn: 'Santiago',
    capitalLatitude: -33.4489,
    capitalLongitude: -70.6693,
    neighborIsoCodes: ['PE', 'BO', 'AR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Şili Pesosu',
    currencyCode: 'CLP',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      '18 Şubat 1818\'de bağımsızlık ilan edildi (millî gün "Fiestas Patrias" ise mücadelenin başladığı 18 Eylül 1810\'da kutlanır).',
    introTr:
      "Güney Amerika'nın batı kıyısında, kuzeyden güneye yaklaşık 4.300 kilometre uzanan " +
      'ama ortalama yalnızca 180 kilometre genişliğinde olan Şili, dünyanın en uzun ve dar ' +
      "ülkelerinden biridir. Doğuda And Dağları boyunca Arjantin'e, kuzeyde Peru ve " +
      "Bolivya'ya komşudur.",
    landformNoteTr:
      'Ülke, kuzeyden güneye üç paralel kuşaktan oluşur: doğuda kıtanın omurgası olan And ' +
      'Dağları, batıda genellikle 2.000 metrenin altında kalan Kıyı Sıradağları, ikisinin ' +
      'arasında ise yaklaşık 965 kilometre uzunluğundaki Orta Vadi — ülke nüfusunun ve ' +
      'tarımının büyük bölümü bu vadide yoğunlaşır. Kuzeyde, And Dağları ile Kıyı ' +
      "Sıradağları'nın iki yönden kapattığı Atakama Çölü, dünyanın kutup dışındaki en kurak " +
      'çölüdür. Güneye inildikçe Kıyı Sıradağları parçalanıp adalara dönüşür; bu bölgede ' +
      'Kuzey ve Güney Patagonya Buz Tarlaları ile derin fiyortlar yer alır.',
    climateNoteTr:
      "Kuzeydeki Atakama'da yıllarca hiç yağış görmeyen alanlar bulunan hiper-kurak bir çöl " +
      "iklimi hakimdir. Orta kesimde, başkent Santiago'nun da bulunduğu bölgede Akdeniz " +
      'iklimi görülür — yazlar sıcak ve kurak, kışlar ılık ve yağışlıdır. Güneye doğru ' +
      "iklim giderek soğur ve nemlenir; Patagonya'ya yakın kesimlerde okyanusal, soğuk ve " +
      'yağışlı bir iklim egemen olur. Kıyı boyunca kuzeyden güneye akan soğuk Humboldt ' +
      'Akıntısı, bu iklim çeşitliliğinin başlıca belirleyicilerinden biridir.',
    hydrographyNoteTr:
      "Şili'nin dar yapısı nehirlerin genellikle kısa olmasına yol açar; neredeyse tamamı " +
      "And Dağları'nda doğup batıya, Pasifik Okyanusu'na akar. Ülkenin en uzun nehri, " +
      'kuzeyde Antofagasta bölgesinde U biçiminde bir yörünge izleyen 440 kilometrelik Loa ' +
      "Nehri'dir. Orta-güney kesimdeki 380 kilometrelik Biobío Nehri ise ülkenin en geniş " +
      'nehridir, ortalama genişliği 1 kilometreyi bulur.',
  },
  {
    isoCode: 'CO',
    isoCodeAlpha3: 'COL',
    nameTr: 'Kolombiya',
    nameEn: 'Colombia',
    slugTr: 'kolombiya',
    slugEn: 'colombia',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 53_425_635,
    populationYear: null,
    areaKm2: 1_109_500,
    capitalNameTr: 'Bogota',
    capitalNameEn: 'Bogotá',
    capitalLatitude: 4.711,
    capitalLongitude: -74.0721,
    neighborIsoCodes: ['PA', 'VE', 'BR', 'PE', 'EC'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Kolombiya Pesosu',
    currencyCode: 'COP',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "20 Temmuz 1810'da İspanya'ya karşı mücadele başladı (resmî millî gün); tam bağımsızlık 1819.",
    introTr:
      "And Dağları, Ekvador sınırından Kolombiya'ya girer girmez üçe ayrılır — kıtadaki " +
      "hiçbir başka ülkede görülmeyen bu yapı, Kolombiya'nın coğrafyasını baştan sona " +
      "şekillendirir. Ülke, kuzeyde Karayip Denizi'ne, batıda ise Büyük Okyanus'a kıyısı " +
      'olan tek Güney Amerika ülkesidir.',
    landformNoteTr:
      'And Dağları, Kolombiya sınırları içinde Batı, Orta ve Doğu Kordilyera olmak üzere üç ' +
      "paralel sıradağa ayrılır; bunların en yükseği Orta Kordilyera'dır. Magdalena ve " +
      'Cauca nehirlerinin vadileri, bu üç sıradağı birbirinden ayırır. Doğuda, Orinoco ' +
      "Havzası'nın bir parçası olan Llanos düzlükleri geniş bir savan örtüsüyle uzanır; " +
      'güneyde ise Amazon yağmur ormanı başlar. Batı kıyısındaki Chocó bölgesi, yılda ' +
      '7.000 ila 13.000 milimetre arasında yağış alarak dünyanın en yağışlı yerlerinden ' +
      'biri sayılır.',
    climateNoteTr:
      "Ekvator'a yakınlığı nedeniyle Kolombiya'da mevsimsel sıcaklık farkı azdır; iklimi " +
      'büyük ölçüde rakım belirler. Deniz seviyesinden 900 metreye kadar tierra caliente ' +
      'kuşağında sıcak ve nemli bir iklim görülür. 900-1.980 metre arasındaki tierra ' +
      "templada'da ılıman koşullar hakimdir — Medellín bu kuşaktadır. 1.980-3.500 metre " +
      'arasındaki tierra fría serindir; 2.640 metre yükseklikteki başkent Bogotá bu ' +
      'kuşağın içinde yer alır. 3.000 metrenin üzerinde başlayan páramo kuşağında ise ' +
      'sıcaklık 10 santigrat derecenin altına düşer, kar yağışı sık görülür.',
    hydrographyNoteTr:
      "Ülkenin ana nehri Magdalena, And Dağları'nda doğar ve yaklaşık 1.528 kilometre " +
      "boyunca kuzeye akarak Karayip Denizi'ne dökülür; kolu Cauca ile birlikte Batı ve " +
      "Orta Kordilyera arasındaki vadiyi oluşturur. Pasifik kıyısında, Chocó'nun yoğun " +
      'yağmur ormanından geçen Atrato ve San Juan nehirleri kısa ama hızlı akışlıdır. ' +
      "Güneyde ise Putumayo ve Caquetá nehirleri, Kolombiya topraklarını Amazon Havzası'na " +
      'bağlar.',
  },
  {
    isoCode: 'EC',
    isoCodeAlpha3: 'ECU',
    nameTr: 'Ekvador',
    nameEn: 'Ecuador',
    slugTr: 'ekvador',
    slugEn: 'ecuador',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 18_289_896,
    populationYear: null,
    areaKm2: 248_360,
    capitalNameTr: 'Kito',
    capitalNameEn: 'Quito',
    capitalLatitude: -0.1807,
    capitalLongitude: -78.4678,
    neighborIsoCodes: ['CO', 'PE'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "24 Mayıs 1822'de İspanya'dan bağımsız oldu; Büyük Kolombiya'dan ayrılış 1830.",
    introTr:
      'Ekvador, adını üzerinden geçtiği ekvator çizgisinden alır; başkent Kito, ekvatora ' +
      'dünyanın en yakın başkentlerinden biridir. Kuzeyde Kolombiya, güney ve doğuda Peru ' +
      'ile komşu olan ülkenin batısında Büyük Okyanus kıyısı uzanır. And Dağları, ülke ' +
      'topraklarını kuzeyden güneye boydan boya keserek üç farklı bölgeye ayırır: dar bir ' +
      'kıyı ovası olan Costa, volkanik And sırtı Sierra ve doğuda Amazon ormanına açılan ' +
      'Oriente. Kıyıdan yaklaşık 1.000 kilometre açıktaki Galápagos Adaları da ülke ' +
      'topraklarının bir parçasıdır.',
    landformNoteTr:
      "And Dağları, Ekvador'da iki paralel sırt halinde uzanır ve aralarındaki vadi, " +
      'onlarca yüksek volkanik zirve barındırdığı için "Volkanlar Bulvarı" olarak anılır. ' +
      "Bu bulvarın en yükseği, 6.263 metrelik Chimborazo'dur; ekvatora yakınlığı ve " +
      "Dünya'nın ekvator çevresindeki şişkinliği nedeniyle zirvesi, gezegen merkezinden en " +
      'uzak nokta kabul edilir. Hâlâ etkin bir volkan olan Cotopaxi, 5.897 metreyle ülkenin ' +
      "ikinci yüksek zirvesidir. Batıda, And Dağları'ndan Büyük Okyanus'a inen dar Costa " +
      "ovası tarımsal açıdan verimlidir; doğuda ise Oriente, Amazon Havzası'nın bir parçası " +
      'olan alçak ve yoğun yağmur ormanıyla kaplıdır.',
    climateNoteTr:
      "Kıyı boyunca esen soğuk Humboldt Akıntısı, Ekvador'un güney ve orta Pasifik " +
      'kıyısında serin ve nispeten kurak bir iklim yaratır; bazı güneybatı kesimlerinde ' +
      'yıllık yağış 250 milimetrenin altına iner. Kuzey kıyıda akıntının etkisi zayıflar ve ' +
      "yağış Kolombiya sınırına yaklaştıkça 3.000 milimetreyi aşabilir. And Dağları'ndaki " +
      'Sierra bölgesinde iklimi büyük ölçüde rakım belirler; Kito gibi yüksek vadilerde ' +
      'gündüz ile gece sıcaklığı arasındaki fark, mevsimler arasındaki farktan daha ' +
      "belirgindir. Doğudaki Oriente'de ise yıl boyunca sıcak, nemli ve yağışlı tropikal " +
      'bir iklim hakimdir.',
    hydrographyNoteTr:
      'Kıyı bölgesinin en büyük akarsu sistemi, Daule ve Babahoyo nehirlerinin Guayaquil ' +
      "yakınında birleşmesiyle oluşan Guayas Nehri'dir; bu nehir Guayaquil Körfezi'ne " +
      "dökülür ve havzası kıyı ovasının tarımsal can damarıdır. Doğuda, And Dağları'ndan " +
      "inen Napo Nehri, Oriente'yi boydan boya geçerek Peru topraklarında Amazon Nehri'ne " +
      "katılır. Sierra'daki yüksek vadilerde ise nehirler kısa ve dik yataklıdır, çoğu " +
      'zaman derin kanyonlar oyar.',
  },
  {
    isoCode: 'GY',
    isoCodeAlpha3: 'GUY',
    nameTr: 'Guyana',
    nameEn: 'Guyana',
    slugTr: 'guyana',
    slugEn: 'guyana',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 835_986,
    populationYear: null,
    areaKm2: 211_140,
    capitalNameTr: 'Georgetown',
    capitalNameEn: 'Georgetown',
    capitalLatitude: 6.8013,
    capitalLongitude: -58.1551,
    neighborIsoCodes: ['VE', 'BR', 'SR'],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Guyana Doları',
    currencyCode: 'GYD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "26 Mayıs 1966'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'PY',
    isoCodeAlpha3: 'PRY',
    nameTr: 'Paraguay',
    nameEn: 'Paraguay',
    slugTr: 'paraguay',
    slugEn: 'paraguay',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 7_013_078,
    populationYear: null,
    areaKm2: 396_012,
    capitalNameTr: 'Asuncion',
    capitalNameEn: 'Asunción',
    capitalLatitude: -25.2637,
    capitalLongitude: -57.5759,
    neighborIsoCodes: ['BO', 'BR', 'AR'],
    officialLanguagesTr: ['İspanyolca', 'Guarani'],
    currencyNameTr: 'Paraguay Guaranisi',
    currencyCode: 'PYG',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr: "14-15 Mayıs 1811'de İspanya'dan bağımsız oldu.",
    introTr:
      'Paraguay Nehri, ülke topraklarını iki farklı bölgeye ayırır: doğuda daha yoğun ' +
      'nüfuslu, ova ve tepelerden oluşan Región Oriental; batıda ise ülke yüzölçümünün ' +
      "yaklaşık %60'ını kaplayan ama nüfusun çok küçük bir bölümünü barındıran Gran " +
      "Chaco'nun bir parçası, Región Occidental. Kuzeyde Bolivya, doğu ve güneyde Brezilya " +
      "ile Arjantin ile komşu olan Paraguay, Bolivya ile birlikte Güney Amerika'nın denize " +
      'kıyısı olmayan iki ülkesinden biridir. Oğlak Dönencesi ülkenin ortasından geçer; bu ' +
      "nedenle Región Oriental'in büyük bölümü subtropikal, kuzeydeki Chaco Boreal ise " +
      'tropikale yakın bir iklim kuşağında kalır.',
    landformNoteTr:
      'Región Oriental, platolar, dalgalı tepeler ve verimli vadilerden oluşan bir arazi ' +
      'yapısına sahiptir; ülkenin en yüksek noktası da bu bölgede, Ybytyruzú sıradağı ' +
      "üzerindeki 842 metrelik Cerro Tres Kandú'dur. Región Occidental ise Gran Chaco'nun " +
      'doğu ucunu oluşturur — Bolivya ve Arjantin topraklarına da yayılan, neredeyse düz, ' +
      'ağaçlık ve çalılık bitki örtüsüyle kaplı geniş bir alüvyal düzlüktür; arazi Paraguay ' +
      "Nehri'ne doğru hafifçe eğimlidir. Chaco'nun toprağı, mevsimsel taşkınlar ve yeraltı " +
      'suyunun tuzluluğu nedeniyle tarıma Región Oriental kadar elverişli değildir.',
    climateNoteTr:
      "Región Oriental'de subtropikal nemli bir iklim hakimdir; yağış yıl boyunca dağılır " +
      've belirgin bir kurak mevsim yoktur, yıllık ortalama 1.400-1.800 milimetre arasında ' +
      "değişir. Batıya doğru yağış hızla azalır — Chaco'nun kuzey kesimi olan Chaco " +
      "Boreal'de yıllık yağış 500-1.000 milimetreye kadar düşer, bu da bölgeyi ülkenin en " +
      'kurak kesimi haline getirir. Yaz ayları ülkenin büyük bölümünde sıcak ve nemli ' +
      'geçer, sıcaklıklar sık sık 35 santigrat dereceyi aşar; kışın ise güneyden esen soğuk ' +
      'pampero rüzgarı, sıcaklığı birkaç gün içinde keskin biçimde düşürebilir.',
    hydrographyNoteTr:
      "Paraguay Nehri, kuzeyden güneye ülkeyi ikiye bölerek başkent Asunción'un yanından " +
      "geçer ve güneyde Paraná Nehri'yle birleşir. Paraná, ülkenin doğu ve güney sınırının " +
      'büyük bölümünü çizer; Brezilya sınırındaki bu nehir üzerinde kurulu Itaipu Barajı, ' +
      "yıllık ortalama enerji üretimi bakımından Çin'deki Üç Boğaz Barajı'ndan sonra " +
      "dünyanın ikinci büyük hidroelektrik santralidir. Batıda, Gran Chaco'yu And " +
      "Dağları'ndan güneydoğuya kat eden Pilcomayo Nehri, ülkenin Arjantin ile olan " +
      "sınırının bir bölümünü oluşturarak Paraguay Nehri'ne katılır.",
  },
  {
    isoCode: 'PE',
    isoCodeAlpha3: 'PER',
    nameTr: 'Peru',
    nameEn: 'Peru',
    slugTr: 'peru',
    slugEn: 'peru',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 34_576_665,
    populationYear: null,
    areaKm2: 1_280_000,
    capitalNameTr: 'Lima',
    capitalNameEn: 'Lima',
    capitalLatitude: -12.0464,
    capitalLongitude: -77.0428,
    neighborIsoCodes: ['EC', 'CO', 'BR', 'BO', 'CL'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Peru Solü',
    currencyCode: 'PEN',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr: "28 Temmuz 1821'de İspanya'dan bağımsızlığını ilan etti.",
    introTr:
      'Peru, birbirinden çok farklı üç boylamsal bölgeye ayrılır: batıda kurak kıyı ' +
      '(Costa), ortada And Dağları (Sierra), doğuda ise Amazon ormanı (Selva). Bu üç bölge ' +
      "içinde en büyüğü Selva'dır — ülke topraklarının %60'ından fazlasını kaplar, ama " +
      "nüfusun büyük kısmı Costa ve Sierra'da yaşar.",
    landformNoteTr:
      'And Dağları, Peru topraklarını kuzeyden güneye boydan boya kat eder; ülkenin en ' +
      "yüksek noktası, 6.768 metrelik Huascarán'dır. And Dağları'nın içinde, Bolivya ile " +
      'paylaşılan Titicaca Gölü yer alır — 3.812 metre yükseklikteki bu göl, dünyanın ' +
      'seyrüsefere elverişli en yüksek gölüdür. Kıyı boyunca dar bir çöl şeridi uzanır; ' +
      "And Dağları'ndan inen birkaç nehrin oluşturduğu vadiler bu kurak şeritte tarıma " +
      "elverişli cepler yaratır. Doğuda başlayan Selva, Amazon Havzası'nın bir parçasıdır " +
      've alçak, yoğun ormanla kaplıdır.',
    climateNoteTr:
      "Kıyı boyunca, soğuk Humboldt Akıntısı'nın etkisiyle nemli ama neredeyse yağışsız bir " +
      'çöl iklimi hakimdir; başkent Lima yılda ortalama yalnızca 10 milimetre yağış alır ' +
      "ve Mayıs-Kasım arasında sık sık yoğun sis (garúa) örter. And Dağları'nda rakım " +
      'arttıkça sıcaklık düşer; Mayıs-Eylül arasındaki kuru mevsimde gökyüzü açık ve ' +
      'geceler soğuk geçerken, Ekim-Nisan yağışlı mevsiminde öğleden sonraları sağanak ' +
      "yağış görülür. Doğudaki Selva'da ise yıl boyunca sıcak ve nemli, yılda 2.000-3.000 " +
      'milimetre yağış alan tropikal bir iklim egemendir.',
    hydrographyNoteTr:
      "Amazon Nehri'nin en uzak kaynağı, onlarca yıl boyunca Peru'daki Apurímac Nehri'nin " +
      "başlangıç noktası olarak kabul edildi; 2014'te yapılan bir çalışma bu kaynağı, yine " +
      "Peru'da bulunan Cordillera Rumi Cruz'daki Mantaro Nehri'nin başlangıcına taşıdı — " +
      "Mantaro, Apurímac'tan yaklaşık 75 kilometre daha uzun çıktı. Doğuda, Marañón ve " +
      "Ucayali nehirleri Peru topraklarında birleşerek Amazon'un ana gövdesini başlatır.",
  },
  {
    isoCode: 'SR',
    isoCodeAlpha3: 'SUR',
    nameTr: 'Surinam',
    nameEn: 'Suriname',
    slugTr: 'surinam',
    slugEn: 'suriname',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 639_850,
    populationYear: null,
    areaKm2: 160_508,
    capitalNameTr: 'Paramaribo',
    capitalNameEn: 'Paramaribo',
    capitalLatitude: 5.852,
    capitalLongitude: -55.2038,
    neighborIsoCodes: ['GY', 'BR', 'FR'],
    officialLanguagesTr: ['Hollandaca'],
    currencyNameTr: 'Surinam Doları',
    currencyCode: 'SRD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "25 Kasım 1975'te Hollanda'dan bağımsız oldu.",
  },
  {
    isoCode: 'UY',
    isoCodeAlpha3: 'URY',
    nameTr: 'Uruguay',
    nameEn: 'Uruguay',
    slugTr: 'uruguay',
    slugEn: 'uruguay',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 3_384_688,
    populationYear: null,
    areaKm2: 175_020,
    capitalNameTr: 'Montevideo',
    capitalNameEn: 'Montevideo',
    capitalLatitude: -34.9011,
    capitalLongitude: -56.1645,
    neighborIsoCodes: ['BR', 'AR'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Uruguay Pesosu',
    currencyCode: 'UYU',
    governmentFormTr: 'Üniter başkanlık cumhuriyeti',
    independenceNoteTr:
      "25 Ağustos 1825'te bağımsızlığını ilan etti; uluslararası tanınma 1828 Montevideo Antlaşması ile.",
    introTr:
      "Güney Amerika'nın (Surinam'dan sonra) yüzölçümce en küçük ikinci ülkesi olan " +
      'Uruguay, kuzeyde ve doğuda Brezilya, batıda Arjantin ile komşudur; güneyde Río de la ' +
      "Plata halici, güneydoğuda ise doğrudan Atlas Okyanusu'na kıyısı vardır. Ülke " +
      "toprakları, kıtanın büyük çayır kuşağı Pampalar'ın doğu ucunu oluşturur ve neredeyse " +
      "hiç dağ barındırmaz — Güney Amerika'nın en düz ülkelerinden biridir. Yüzölçümünün " +
      'büyük bölümü, tarım ve hayvancılığa elverişli dalgalı otlaklardan oluşur.',
    landformNoteTr:
      "Uruguay'ın iç kesimlerinde, kuzeyden güneye uzanan alçak ve yumuşak tepe sıraları — " +
      'cuchillalar — araziye hafif bir dalgalanma katar; bunların en belirgini, ülkeyi ' +
      "ortadan geçen Cuchilla Grande'dir, ona batıda paralel uzanan Cuchilla de Haedo eşlik " +
      'eder. Bu sıralar gerçek dağ zincirleri oluşturmaz, çimenli tepelerin art arda ' +
      'dizilmesinden ibarettir; aralarında Cerro Pan de Azúcar ve Cerro Arequita gibi tek ' +
      'başına yükselen tepeler bulunur. Ülkenin en yüksek noktası, Maldonado bölgesindeki ' +
      "Sierra Carapé'de yer alan 513,66 metrelik Cerro Catedral'dir — Güney Amerika'nın en " +
      'alçak ulusal zirvelerinden biri. Güney ve güneybatı kıyı şeridi boyunca, Río de la ' +
      "Plata'nın kenarında alçak ve düz kıyı ovaları uzanır.",
    climateNoteTr:
      'Uruguay, ülke genelinde oldukça tekdüze bir nemli subtropikal iklime (Köppen Cfa) ' +
      'sahiptir; belirgin bir kurak mevsim yoktur, yağış kışın soğuk cephelerle, yazın ise ' +
      'gök gürültülü sağanaklarla yıl boyunca dağılır. Yıllık yağış güneyden kuzeye artar — ' +
      'Montevideo çevresinde 1.100-1.200 milimetre iken, ülkenin kuzeyinde 1.600 ' +
      'milimetreye ulaşabilir. Mevsimler belirgin biçimde ayrışır: ilkbahar nemli ve ' +
      'rüzgarlı, yaz ılık, sonbahar mutedil, kış ise nemli ve serin geçer.',
    hydrographyNoteTr:
      'Batı sınırı boyunca, güney Brezilya dağlarından doğan Río Uruguay güneye akar ve ' +
      '1.800 kilometreden fazla bir mesafenin ardından Río de la Plata halicine ulaşır. Río ' +
      "de la Plata, Uruguay ve Paraná nehirlerinin birleşerek Atlas Okyanusu'na açıldığı " +
      'huni biçimli bir halic olup dünyanın en geniş nehir ağızlarından biridir. Ülke ' +
      "içinde ise Río Negro doğudan batıya akarak Río Uruguay'a katılır; üzerindeki Rincón " +
      "del Bonete Barajı'nın oluşturduğu gölet, ülkenin en büyük tatlı su kütlesidir ve Río " +
      "Negro üzerindeki üç büyük baraj birlikte Uruguay'ın elektriğinin yaklaşık %60'ını " +
      'üretir.',
  },
  {
    isoCode: 'VE',
    isoCodeAlpha3: 'VEN',
    nameTr: 'Venezuela',
    nameEn: 'Venezuela',
    slugTr: 'venezuela',
    slugEn: 'venezuela',
    continent: Continent.SouthAmerica,
    unSubregionTr: 'Güney Amerika',
    population: 28_516_896,
    populationYear: null,
    areaKm2: 882_050,
    capitalNameTr: 'Karakas',
    capitalNameEn: 'Caracas',
    capitalLatitude: 10.4806,
    capitalLongitude: -66.9036,
    neighborIsoCodes: ['CO', 'BR', 'GY'],
    officialLanguagesTr: ['İspanyolca'],
    currencyNameTr: 'Venezuela Bolivarı',
    currencyCode: 'VES',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr: "5 Temmuz 1811'de İspanya'dan bağımsızlığını ilan etti.",
    introTr:
      "Venezuela, kuzeyde Karayip Denizi'ne kıyısı olan ve dört farklı coğrafi bölgeye " +
      "ayrılan bir ülkedir: kuzeybatıda Maracaibo alçak arazisi, kuzeyde And Dağları'nın " +
      'uzantısı olan kıyı sıradağları, orta kesimde geniş Orinoco düzlükleri (Llanos) ve ' +
      'güneydoğuda Guyana Yaylası.',
    landformNoteTr:
      "And Dağları'nın Venezuela'ya uzanan kolu, ülkenin kuzeybatısını kaplar; en yüksek " +
      "noktası, Mérida yakınlarındaki 4.978 metrelik Pico Bolívar'dır. Maracaibo Gölü, " +
      "Karayip Denizi'ne açık olduğu için teknik olarak bir göl sayılmasa da, Güney " +
      "Amerika'nın en büyük iç su kütlesi kabul edilir. Ülkenin yaklaşık üçte birini " +
      'kaplayan Llanos, Orinoco Nehri havzasının parçası olan geniş bir çayır-savan ' +
      "düzlüğüdür. Güneydoğuda ise Guyana Yaylası'nda, dik yamaçlı ve düz tepeli tepui'ler " +
      "yükselir; bunlardan Auyán-tepui'nin kenarından dökülen Angel Şelalesi, 979 metre " +
      'yükseklikle dünyanın en yüksek şelalesidir.',
    climateNoteTr:
      "Llanos'ta, belirgin yağışlı ve kurak dönemleri olan tropikal savan iklimi hakimdir. " +
      'Maracaibo Gölü çevresi ise ülkenin en sıcak bölgesidir; bazı yerleşimlerde sıcaklık ' +
      "46-47 santigrat dereceye kadar çıkabilir. And Dağları'nın yüksek vadilerinde, Mérida " +
      've Karakas çevresinde ise ılıman bir dağ iklimi görülür — Mérida eyaletindeki en ' +
      'yüksek kesimlerde sıcaklık eksi 11 santigrat dereceye kadar düşebilir.',
    hydrographyNoteTr:
      "Debi bakımından Güney Amerika'da Amazon'dan sonra en büyük, dünya genelinde ise " +
      "üçüncü büyük nehir olan Orinoco, Guyana Yaylası'nda doğar ve yaklaşık 2.140 " +
      "kilometre sonra Atlantik Okyanusu'na ulaşır. Guyana Yaylası'ndan inen Caroní Nehri " +
      "de Orinoco'ya katılır; güzergahı boyunca Angel Şelalesi dahil çok sayıda şelale " +
      'barındırır.',
  },
];
