import { Continent } from '../../../common/continent.enum';
import type { CountrySeed } from '../country.seed-data';

/**
 * Asya (pilotun 6 komşusu hariç) — dünya haritası base-data seed (38 ülke). Structured fields only; the
 * narrative prose fields (introTr/landformNoteTr/climateNoteTr/hydrographyNoteTr) are
 * seeded null and filled in later regional content waves. populationYear is null across
 * the board (world-scale ruling, DEC 2026-07-13). Source of record:
 * Owner's Inbox/dunya-haritasi-base-data/. Every value hand-curated from the approved
 * research; slugs generated by an ASCII/Turkish-fold rule (matches the pilot).
 */
export const ASIA_COUNTRIES: readonly CountrySeed[] = [
  {
    isoCode: 'CN',
    isoCodeAlpha3: 'CHN',
    nameTr: 'Çin',
    nameEn: 'China',
    slugTr: 'cin',
    slugEn: 'china',
    continent: Continent.Asia,
    unSubregionTr: 'Doğu Asya',
    population: 1_406_585_000,
    populationYear: null,
    areaKm2: 9_388_210,
    capitalNameTr: 'Pekin',
    capitalNameEn: 'Beijing',
    capitalLatitude: 39.9042,
    capitalLongitude: 116.4074,
    neighborIsoCodes: [
      'AF',
      'BT',
      'IN',
      'KZ',
      'KG',
      'LA',
      'MN',
      'MM',
      'NP',
      'KP',
      'PK',
      'RU',
      'TJ',
      'VN',
    ],
    officialLanguagesTr: ['Mandarin Çincesi'],
    currencyNameTr: 'Yuan (Renminbi)',
    currencyCode: 'CNY',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr: null,
    introTr:
      'Batıda dünyanın en yüksek platosundan doğuda Pasifik kıyısına uzanan Çin, nüfus ' +
      'bakımından dünyanın en kalabalık ülkelerinden biridir ve on dört ülkeyle kara sınırı ' +
      "paylaşarak Rusya'yla birlikte dünyanın en fazla kara komşusuna sahip ülkesi unvanını " +
      'taşır.',
    landformNoteTr:
      'Ülkenin batısını, dünyanın en büyük ve en yüksek platosu olan Tibet Platosu kaplar — bu ' +
      'yükseklik nedeniyle "dünyanın çatısı" olarak da anılır. Platonun güneyinde yükselen ' +
      "Himalayalar'da, Nepal sınırındaki 8.848 metrelik Everest Dağı, hem Çin'in hem dünyanın " +
      'en yüksek noktasıdır; Pakistan sınırındaki K2 (8.611 m) dünyanın ikinci en yüksek ' +
      "zirvesidir. Dünyanın en yüksek 17 zirvesinden 11'i Çin'in batı sınırlarında yer alır." +
      '\n\n' +
      "Kuzeybatıda, Himalayalar'ın yağış gölgesinde kalan Taklamakan Çölü, dünyanın en büyük " +
      'ikinci hareketli kum çölüdür. Doğuya doğru inildikçe arazi alçalır; ülkenin ' +
      "kuzeydoğusunda Mançurya Ovası, güneydoğusunda ise Yangtze ve Sarı Nehir'in taşıdığı " +
      'alüvyonlarla oluşan geniş ve verimli Kuzey Çin Ovası uzanır — ülkenin en yoğun nüfuslu ' +
      'kesimleri bu düzlüklerdedir.',
    climateNoteTr:
      'Kuzey-güney doğrultusunda geniş bir enlem açıklığı ve doğu-batı yönünde okyanustan iç ' +
      "kesimlere uzanan devasa bir derinlik, Çin'i dünyanın en çok iklim çeşitliliğine sahip " +
      "ülkelerinden biri yapar. Güneydoğu kıyıları ve Hainan Adası'nda tropikal ve subtropikal " +
      'muson iklimi egemendir, yazlar sıcak ve yağışlı geçer. Kuzeye doğru bu muson etkisi ' +
      'zayıflar, Pekin ve çevresinde karasal bir iklim görülür, kışlar soğuk ve kurak geçer. ' +
      'Kuzeybatıda, Taklamakan ve çevresinde nemden büyük ölçüde yoksun kurak bir iç Asya ' +
      "iklimi hakimdir. Tibet Platosu'nda ise yükseklik belirleyicidir — kısa ve serin yazlar, " +
      'uzun ve sert kışlarla karakterize soğuk bir yayla iklimi egemendir, kış sıcaklıkları sık ' +
      'sık eksi 10 derecenin altına iner.',
    hydrographyNoteTr:
      "Çin'in en uzun nehri, dünyanın üçüncü en uzun nehri olan 6.300 kilometrelik Yangtze'dir " +
      "(Chang Jiang); kaynağı Tibet Platosu'ndaki Qinghai bölgesindedir, ülkeyi batıdan doğuya " +
      "kat ederek Şangay yakınlarında Doğu Çin Denizi'ne dökülür. Sarı Nehir (Huang He), 5.464 " +
      'kilometreyle ülkenin ikinci en uzun nehridir, adını taşıdığı sarımsı alüvyonlardan alır ' +
      "ve Kuzey Çin Ovası'nın oluşumunda belirleyici rol oynamıştır." +
      '\n\n' +
      "Ülkenin en büyük tatlı su gölü Poyang Gölü, Yangtze'nin orta-alt havzasında yer alır; " +
      "Tibet Platosu'ndaki Qinghai Gölü ise Çin'in en büyük tuzlu su gölüdür.",
  },
  {
    isoCode: 'JP',
    isoCodeAlpha3: 'JPN',
    nameTr: 'Japonya',
    nameEn: 'Japan',
    slugTr: 'japonya',
    slugEn: 'japan',
    continent: Continent.Asia,
    unSubregionTr: 'Doğu Asya',
    population: 123_366_734,
    populationYear: null,
    areaKm2: 364_569,
    capitalNameTr: 'Tokyo',
    capitalNameEn: 'Tokyo',
    capitalLatitude: 35.6762,
    capitalLongitude: 139.6503,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Japonca'],
    currencyNameTr: 'Yen',
    currencyCode: 'JPY',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: null,
    introTr:
      'Kuzeydoğu Asya kıyısı boyunca kuzeyden güneye yaklaşık 3.000 kilometre uzanan Japonya, ' +
      'dört ana ada — Hokkaido, Honshu, Şikoku ve Kyushu — ile bunlara bağlı binlerce küçük ' +
      "adadan oluşan bir takımadadır; kara sınırı yoktur. Batıda Japon Denizi'ne, doğuda " +
      "Büyük Okyanus'a kıyısı vardır. Bu geniş enlem açıklığı, kuzeyde subarktik Hokkaido'dan " +
      "güneyde subtropikal Ryukyu Adaları'na kadar uzanan gerçek bir iklim çeşitliliğine yol " +
      'açar.',
    landformNoteTr:
      "Japonya topraklarının yaklaşık %73'ü dağlıktır. Honshu'nun ortasında yükselen Hida, " +
      "Kiso ve Akaishi sıradağları birlikte Japon Alpleri'ni oluşturur; bu üçlünün en yüksek " +
      "noktası, Akaishi sıradağına ait 3.193 metrelik Kita Dağı'dır. Ülkenin en yüksek noktası " +
      "ise Şizuoka ve Yamanaşi illeri sınırında yükselen 3.776 metrelik Fuji Dağı'dır " +
      "(Fujisan); 1707'den bu yana patlamamış olsa da jeologlar onu hâlâ aktif bir " +
      'stratovolkan olarak sınıflandırır.' +
      '\n\n' +
      'Japon Takımadaları, Pasifik, Filipin Denizi, Avrasya ve Kuzey Amerika levhalarının ' +
      'kesiştiği noktada yer alır; bu levha hareketleri ülkeyi dünyanın en depremsel ' +
      "bölgelerinden birine dönüştürür, yılda 1.500'e yakın deprem kaydedilir. Aynı levha " +
      'sınırları, dünyadaki aktif volkanların yaklaşık onda birini Japonya topraklarında ' +
      'toplar.',
    climateNoteTr:
      'Hokkaido, uzun ve çok soğuk kışlarla ılık yazların görüldüğü nemli karasal bir iklime ' +
      'sahiptir; kışın Sibirya kaynaklı soğuk rüzgârlar Japon Denizi üzerinden nem toplayarak ' +
      "Sapporo gibi kentlere yoğun kar yağışı taşır. Honshu, Şikoku ve Kyushu'nun büyük " +
      'bölümünde nemli subtropikal iklim egemendir; yazlar sıcak ve nemlidir, Haziran-Ekim ' +
      'arasında tayfunlar kıyı kesimlerini etkiler. Bu adaların kendi içinde bile Japon Denizi ' +
      'kıyısı ile Büyük Okyanus kıyısı farklı bir kış yaşar: Japon Denizi tarafı kalın kar ' +
      'örtüsüyle kaplanırken, Büyük Okyanus tarafı görece kuru ve güneşli geçer. Güneyde, ' +
      "Ryukyu Adaları'nda kışlar ılık geçer; subtropikal iklimde nem ve sıcaklık yıl boyunca " +
      'yüksek kalır.',
    hydrographyNoteTr:
      "Japonya'nın dağlık topografyası nehirlerin kısa ve dik akmasına yol açar; ülkenin en " +
      "uzun nehri bile 367 kilometrelik Şinano Nehri'dir — Japon Alpleri'nde doğar, Nagano'daki " +
      "üst akımında Chikuma adıyla anılır ve Niigata yakınlarında Japon Denizi'ne dökülür. " +
      "Ülkenin en büyük gölü, Şiga ilinde, Kyoto'nun kuzeydoğusunda yer alan Biwa Gölü'dür; " +
      '670 kilometrekarelik yüzölçümüyle ve dört milyon yıldan uzun jeolojik geçmişiyle ' +
      'dünyanın en eski göllerinden sayılır.',
  },
  {
    isoCode: 'MN',
    isoCodeAlpha3: 'MNG',
    nameTr: 'Moğolistan',
    nameEn: 'Mongolia',
    slugTr: 'mogolistan',
    slugEn: 'mongolia',
    continent: Continent.Asia,
    unSubregionTr: 'Doğu Asya',
    population: 3_568_978,
    populationYear: null,
    areaKm2: 1_558_500,
    capitalNameTr: 'Ulan Batur',
    capitalNameEn: 'Ulaanbaatar',
    capitalLatitude: 47.8864,
    capitalLongitude: 106.9057,
    neighborIsoCodes: ['RU', 'CN'],
    officialLanguagesTr: ['Moğolca'],
    currencyNameTr: 'Tugrik',
    currencyCode: 'MNT',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "1921'de Çin'den fiili bağımsızlık kazandı; 1945 referandumunun ardından uluslararası tanınma geldi.",
    introTr:
      'Kuzeyde Rusya, güneyde Çin ile komşu olan Moğolistan, denize kıyısı olmayan bir iç ' +
      'Asya ülkesidir; ortalama 1.580 metre yükseklikteki geniş bir plato üzerinde yer alır. ' +
      'Toprakların büyük bölümünü step (bozkır) örtüsü kaplar; batıda yüksek dağlar, güneyde ' +
      'ise Gobi Çölü ülkenin manzarasını belirler.',
    landformNoteTr:
      'Ülkenin batısında, kuzeybatı-güneydoğu doğrultusunda uzanan Altay Dağları yükselir; ' +
      'bu sıradağın Moğolistan sınırları içindeki en yüksek noktası 4.374 metrelik Höyten ' +
      "Zirvesi'dir (Khüiten). Altay Tavan Bogd bölgesi, ülkedeki tek güncel buzullaşmanın " +
      'görüldüğü kesimdir. Daha doğuda, orta kesimde yükselen Hangay Dağları geniş bir step ' +
      'kuşağıyla çevrilidir. Güneyde, ülke yüzölçümünün yaklaşık üçte birini kaplayan Gobi ' +
      'Çölü uzanır. Gobi, kum tepelerinden çok kayalık ve sarp arazi ile kaplıdır; kum ' +
      'tepeleri yalnızca güney kesimlerinde belirginleşir.',
    climateNoteTr:
      "Uzun ve çok soğuk kışlar, kısa yazlarla birlikte Moğolistan'a aşırı karasal bir iklim " +
      'kazandırır; yıllık yağışın büyük bölümü bu kısa yaz döneminde düşer. Başkent Ulan ' +
      'Batur, yıllık ortalama sıcaklığı eksi 1,3 santigrat derece ile dünyanın en soğuk ' +
      'başkenti kabul edilir; kış geceleri sıklıkla eksi 35 santigrat derecenin altına iner. ' +
      "Yağış kuzeyde yılda 200-350 milimetreye ulaşırken güneydeki Gobi Çölü'nde 100-200 " +
      'milimetreye kadar düşer. Şiddetli kış koşullarının hayvancılığı vurduğu bu duruma ' +
      'Moğolca "zud" denir ve ülkenin kırsal ekonomisini düzenli aralıklarla sarsar.',
    hydrographyNoteTr:
      "Moğolistan sınırları içinde tamamen akan en uzun nehir, Hangay Dağları'nda doğan ve " +
      "1.124 kilometre sonra Selenge Nehri'ne katılan Orkun Nehri'dir. Selenge, Orkun'un da " +
      "içinde bulunduğu kolları toplayarak kuzeye, Rusya topraklarındaki Baykal Gölü'ne akar. " +
      'Ülkenin en büyük tatlı su gölü, kuzeyde Rusya sınırına yakın yer alan Hövsgöl ' +
      "Gölü'dür; 262 metreye varan derinliğiyle Moğolistan'ın tatlı su rezervinin yaklaşık " +
      "%70'ini tek başına barındırır.",
  },
  {
    isoCode: 'KR',
    isoCodeAlpha3: 'KOR',
    nameTr: 'Güney Kore',
    nameEn: 'South Korea',
    slugTr: 'guney-kore',
    slugEn: 'south-korea',
    continent: Continent.Asia,
    unSubregionTr: 'Doğu Asya',
    population: 51_684_564,
    populationYear: null,
    areaKm2: 97_600,
    capitalNameTr: 'Seul',
    capitalNameEn: 'Seoul',
    capitalLatitude: 37.5665,
    capitalLongitude: 126.978,
    neighborIsoCodes: ['KP'],
    officialLanguagesTr: ['Korece'],
    currencyNameTr: 'Won',
    currencyCode: 'KRW',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "Japon işgalinden kurtuluş 15 Ağustos 1945'te gerçekleşti (resmî olarak kutlanır); Kore Cumhuriyeti 15 Ağustos 1948'de ilan edildi.",
    introTr:
      "Kore Yarımadası'nın güney yarısını kaplayan Güney Kore, batıda Sarı Deniz'e, doğuda " +
      "Japon Denizi'ne, güneyde ise Japonya'yı ayıran Kore Boğazı'na kıyısı vardır. Tek kara " +
      'sınırı, kuzeyde Kuzey Kore ile paylaştığı hattır. Dağlar ve tepeler, ülke topraklarının ' +
      'yaklaşık dörtte üçünü oluşturur.',
    landformNoteTr:
      'Ülkenin doğu kıyısı boyunca, yaklaşık 500 kilometre uzunluğunda bir sırt oluşturan ' +
      "Taebaek Dağları uzanır; bu sıradağın doğu yamacı Japon Denizi'ne dik bir fay hattıyla " +
      'iner, batı yamacı ise çok daha kademelidir. Seorak Dağı (1.708 m) bu sıradağın en ' +
      'tanınmış zirvelerindendir. Ülkenin en yüksek noktası ise anakaradan ayrı, Kore ' +
      "Boğazı'ndaki Jeju Adası'nı oluşturan bir kalkan volkanı olan 1.950 metrelik Halla " +
      "Dağı'dır (Hallasan). Batı ve güney kıyılarında, nüfusun ve tarımın yoğunlaştığı geniş " +
      've alçak ovalar yer alır.',
    climateNoteTr:
      "Seul'ün de içinde bulunduğu orta ve kuzey kesimde, kışın kuru ve soğuk, yazın sıcak ve " +
      "nemli geçtiği nemli karasal iklim görülür. Güney kıyısı ve Jeju Adası'nda ise kışları " +
      'daha ılıman, nemli subtropikal iklim egemendir. Ülke genelinde dört mevsim belirgindir; ' +
      'Haziran sonu ile Temmuz sonu arasında Doğu Asya musonunun getirdiği yoğun yağışlı ' +
      'döneme "jangma" denir, yaz sonuna doğru ise tayfunlar etkili olur.',
    hydrographyNoteTr:
      "Güney Kore'nin en uzun nehri, Taebaek Dağları'ndan doğup Kore Boğazı'na dökülen 506 " +
      "kilometrelik Nakdong Nehri'dir; Daegu ve Busan kentlerinden geçer. Kollarından biri " +
      "Taebaek Dağları'na yakın bir kaynaktan doğan 494 kilometrelik Han Nehri ise başkent " +
      "Seul'ün içinden akarak Sarı Deniz'e ulaşır.",
  },
  {
    isoCode: 'KP',
    isoCodeAlpha3: 'PRK',
    nameTr: 'Kuzey Kore',
    nameEn: 'North Korea',
    slugTr: 'kuzey-kore',
    slugEn: 'north-korea',
    continent: Continent.Asia,
    unSubregionTr: 'Doğu Asya',
    population: 26_571_036,
    populationYear: null,
    areaKm2: 120_410,
    capitalNameTr: 'Pyongyang',
    capitalNameEn: 'Pyongyang',
    capitalLatitude: 39.0392,
    capitalLongitude: 125.7625,
    neighborIsoCodes: ['CN', 'RU', 'KR'],
    officialLanguagesTr: ['Korece'],
    currencyNameTr: 'Kuzey Kore Wonu',
    currencyCode: 'KPW',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr: "9 Eylül 1948'de kuruldu (Japon işgalinden kurtuluş 1945).",
    introTr:
      "Kore Yarımadası'nın kuzey yarısını kaplayan Kuzey Kore, kuzeybatıda Yalu Nehri boyunca " +
      "Çin'e, kuzeydoğuda kısa bir hatta Tuman Nehri boyunca Rusya'ya komşudur; güneyde ise " +
      'Güney Kore ile 250 kilometre uzunluğunda, yaklaşık 4 kilometre genişliğindeki ' +
      "askerden arındırılmış bölge (DMZ) ile ayrılır — 1953 Kore Ateşkes Anlaşması'yla " +
      "kurulan bu hat, 38. paralele açılı biçimde kesişir. Batıda Kore Körfezi'ne (Sarı " +
      "Deniz'in bir kolu), doğuda Japon Denizi'ne kıyısı vardır. Yüzölçümünün yaklaşık %80'i " +
      'dağlık ve tepeliktir.',
    landformNoteTr:
      'Ülkenin en yüksek noktası, Çin sınırında yükselen aktif bir stratovolkan olan 2.744 ' +
      "metrelik Paektu Dağı'dır (Baekdu); zirvesindeki kalderada, Songhua, Tuman ve Yalu " +
      "nehirlerinin kaynağını oluşturan Cennet Gölü yer alır. Paektu'nun güneyinde, Kore'nin " +
      'en geniş yaylası olan ve "Kore\'nin çatısı" diye anılan Kaema Platosu uzanır; 700-2.000 ' +
      'metre yükseklikte, yaklaşık 40.000 kilometrekarelik bir alanı kaplar. Platonun batısını, ' +
      'ülkenin ortasından kuzey-güney doğrultusunda uzanan ve yarımadanın doğu ve batı ' +
      'yamaçlarını birbirinden ayıran Rangnim Dağları (güney lehçesinde Nangnim olarak da ' +
      'telaffuz edilir) çevreler; doğusunu ise Hamgyong Dağları sınırlar. Kıyı ovaları ' +
      "dardır; en geniş düzlükler batıda, Sarı Deniz'e bakan kesimdedir.",
    climateNoteTr:
      "Kuzey Kore'de yazları ılık, kışları soğuk ve kurak geçen nemli karasal iklim egemendir. " +
      'Sibirya kaynaklı kuzey ve kuzeybatı rüzgârları kışın uzun süreli soğuk dalgaları ' +
      'getirir; kış sıcaklıkları güneyde yaklaşık eksi 7, Kaema Platosu gibi yüksek kuzey ' +
      'kesimlerinde ise eksi 23 santigrat dereceye kadar düşebilir. Yaz yağışlarının büyük ' +
      'bölümü Haziran-Eylül arasında, Doğu Asya musonuyla birlikte gelir.',
    hydrographyNoteTr:
      "Çin sınırını çizen Yalu Nehri (Amnok), Paektu Dağı'nda doğar ve yaklaşık 790 kilometre " +
      "sonra Kore Körfezi'ne dökülür; kışın dört ay boyunca donarak gemi trafiğine kapanır. " +
      'Rusya sınırının bir bölümünü oluşturan 521 kilometrelik Tuman Nehri de kaynağını ' +
      "Paektu'nun eteklerinden alır ve Japon Denizi'ne ulaşır. Ülke sınırları içinde tamamen " +
      "akan en önemli nehir, Rangnim Dağları'nda doğup başkent Pyongyang'ın içinden geçerek " +
      "Nampo'da Kore Körfezi'ne dökülen 439 kilometrelik Taedong Nehri'dir; derinliği " +
      'sayesinde iç kesimlere kadar gemi taşımacılığına elverişlidir.',
  },
  {
    isoCode: 'KZ',
    isoCodeAlpha3: 'KAZ',
    nameTr: 'Kazakistan',
    nameEn: 'Kazakhstan',
    slugTr: 'kazakistan',
    slugEn: 'kazakhstan',
    continent: Continent.Asia,
    unSubregionTr: 'Orta Asya',
    population: 20_843_754,
    populationYear: null,
    areaKm2: 2_699_700,
    capitalNameTr: 'Astana',
    capitalNameEn: 'Astana',
    capitalLatitude: 51.1694,
    capitalLongitude: 71.4491,
    neighborIsoCodes: ['RU', 'CN', 'KG', 'UZ', 'TM'],
    officialLanguagesTr: ['Kazakça'],
    currencyNameTr: 'Tenge',
    currencyCode: 'KZT',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "16 Aralık 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'KG',
    isoCodeAlpha3: 'KGZ',
    nameTr: 'Kırgızistan',
    nameEn: 'Kyrgyzstan',
    slugTr: 'kirgizistan',
    slugEn: 'kyrgyzstan',
    continent: Continent.Asia,
    unSubregionTr: 'Orta Asya',
    population: 7_343_064,
    populationYear: null,
    areaKm2: 191_800,
    capitalNameTr: 'Bişkek',
    capitalNameEn: 'Bishkek',
    capitalLatitude: 42.8746,
    capitalLongitude: 74.5698,
    neighborIsoCodes: ['KZ', 'UZ', 'TJ', 'CN'],
    officialLanguagesTr: ['Kırgızca', 'Rusça'],
    currencyNameTr: 'Som',
    currencyCode: 'KGS',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "31 Ağustos 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'TJ',
    isoCodeAlpha3: 'TJK',
    nameTr: 'Tacikistan',
    nameEn: 'Tajikistan',
    slugTr: 'tacikistan',
    slugEn: 'tajikistan',
    continent: Continent.Asia,
    unSubregionTr: 'Orta Asya',
    population: 10_786_734,
    populationYear: null,
    areaKm2: 138_790,
    capitalNameTr: 'Duşanbe',
    capitalNameEn: 'Dushanbe',
    capitalLatitude: 38.5598,
    capitalLongitude: 68.787,
    neighborIsoCodes: ['KG', 'UZ', 'AF', 'CN'],
    officialLanguagesTr: ['Tacikçe'],
    currencyNameTr: 'Somoni',
    currencyCode: 'TJS',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "9 Eylül 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'TM',
    isoCodeAlpha3: 'TKM',
    nameTr: 'Türkmenistan',
    nameEn: 'Turkmenistan',
    slugTr: 'turkmenistan',
    slugEn: 'turkmenistan',
    continent: Continent.Asia,
    unSubregionTr: 'Orta Asya',
    population: 7_618_847,
    populationYear: null,
    areaKm2: 469_930,
    capitalNameTr: 'Aşkabat',
    capitalNameEn: 'Ashgabat',
    capitalLatitude: 37.9601,
    capitalLongitude: 58.3261,
    neighborIsoCodes: ['KZ', 'UZ', 'AF', 'IR'],
    officialLanguagesTr: ['Türkmence'],
    currencyNameTr: 'Manat',
    currencyCode: 'TMT',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "27 Ekim 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'UZ',
    isoCodeAlpha3: 'UZB',
    nameTr: 'Özbekistan',
    nameEn: 'Uzbekistan',
    slugTr: 'ozbekistan',
    slugEn: 'uzbekistan',
    continent: Continent.Asia,
    unSubregionTr: 'Orta Asya',
    population: 37_053_428,
    populationYear: null,
    areaKm2: 440_650,
    capitalNameTr: 'Taşkent',
    capitalNameEn: 'Tashkent',
    capitalLatitude: 41.2995,
    capitalLongitude: 69.2401,
    neighborIsoCodes: ['KZ', 'KG', 'TJ', 'TM', 'AF'],
    officialLanguagesTr: ['Özbekçe'],
    currencyNameTr: 'Som',
    currencyCode: 'UZS',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "1 Eylül 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'BN',
    isoCodeAlpha3: 'BRN',
    nameTr: 'Brunei',
    nameEn: 'Brunei',
    slugTr: 'brunei',
    slugEn: 'brunei',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 466_330,
    populationYear: null,
    areaKm2: 5_270,
    capitalNameTr: 'Bender Seri Begavan',
    capitalNameEn: 'Bandar Seri Begawan',
    capitalLatitude: 4.9031,
    capitalLongitude: 114.9398,
    neighborIsoCodes: ['MY'],
    officialLanguagesTr: ['Malayca'],
    currencyNameTr: 'Brunei Doları',
    currencyCode: 'BND',
    governmentFormTr: 'Mutlak monarşi (Sultanlık)',
    independenceNoteTr: "1 Ocak 1984'te İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'KH',
    isoCodeAlpha3: 'KHM',
    nameTr: 'Kamboçya',
    nameEn: 'Cambodia',
    slugTr: 'kambocya',
    slugEn: 'cambodia',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 17_847_982,
    populationYear: null,
    areaKm2: 176_520,
    capitalNameTr: 'Phnom Penh',
    capitalNameEn: 'Phnom Penh',
    capitalLatitude: 11.5564,
    capitalLongitude: 104.9282,
    neighborIsoCodes: ['TH', 'LA', 'VN'],
    officialLanguagesTr: ['Khmerce'],
    currencyNameTr: 'Riel',
    currencyCode: 'KHR',
    governmentFormTr: 'Parlamenter monarşi',
    independenceNoteTr: "9 Kasım 1953'te Fransa'dan bağımsız oldu.",
  },
  {
    isoCode: 'ID',
    isoCodeAlpha3: 'IDN',
    nameTr: 'Endonezya',
    nameEn: 'Indonesia',
    slugTr: 'endonezya',
    slugEn: 'indonesia',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 285_721_236,
    populationYear: null,
    areaKm2: 1_892_555,
    capitalNameTr: 'Cakarta',
    capitalNameEn: 'Jakarta',
    capitalLatitude: -6.2088,
    capitalLongitude: 106.8456,
    neighborIsoCodes: ['MY', 'PG', 'TL'],
    officialLanguagesTr: ['Endonezce'],
    currencyNameTr: 'Rupiah',
    currencyCode: 'IDR',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "17 Ağustos 1945'te bağımsızlığını ilan etti (Hollanda'nın resmî tanıması 27 Aralık 1949); ülke 17 Ağustos'u Bağımsızlık Günü olarak kutlar.",
  },
  {
    isoCode: 'LA',
    isoCodeAlpha3: 'LAO',
    nameTr: 'Laos',
    nameEn: 'Laos',
    slugTr: 'laos',
    slugEn: 'laos',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 7_873_046,
    populationYear: null,
    areaKm2: 230_800,
    capitalNameTr: 'Vientiane',
    capitalNameEn: 'Vientiane',
    capitalLatitude: 17.9757,
    capitalLongitude: 102.6331,
    neighborIsoCodes: ['CN', 'MM', 'TH', 'KH', 'VN'],
    officialLanguagesTr: ['Laoca'],
    currencyNameTr: 'Kip',
    currencyCode: 'LAK',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr:
      "22 Ekim 1953'te Fransa'dan tam bağımsızlığını kazandı (1949'da kısmi özerklik tanınmıştı).",
  },
  {
    isoCode: 'MY',
    isoCodeAlpha3: 'MYS',
    nameTr: 'Malezya',
    nameEn: 'Malaysia',
    slugTr: 'malezya',
    slugEn: 'malaysia',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 35_977_838,
    populationYear: null,
    areaKm2: 328_550,
    capitalNameTr: 'Kuala Lumpur',
    capitalNameEn: 'Kuala Lumpur',
    capitalLatitude: 3.139,
    capitalLongitude: 101.6869,
    neighborIsoCodes: ['TH', 'ID', 'BN'],
    officialLanguagesTr: ['Malayca'],
    currencyNameTr: 'Ringgit',
    currencyCode: 'MYR',
    governmentFormTr: 'Federal parlamenter seçimli monarşi',
    independenceNoteTr:
      "31 Ağustos 1957'de Malaya Federasyonu İngiltere'den bağımsız oldu; bugünkü Malezya Federasyonu 16 Eylül 1963'te kuruldu.",
  },
  {
    isoCode: 'MM',
    isoCodeAlpha3: 'MMR',
    nameTr: 'Myanmar',
    nameEn: 'Myanmar',
    slugTr: 'myanmar',
    slugEn: 'myanmar',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 54_850_648,
    populationYear: null,
    areaKm2: 652_670,
    capitalNameTr: 'Naypyidaw',
    capitalNameEn: 'Naypyidaw',
    capitalLatitude: 19.7633,
    capitalLongitude: 96.0785,
    neighborIsoCodes: ['CN', 'IN', 'BD', 'TH', 'LA'],
    officialLanguagesTr: ['Birmanca'],
    currencyNameTr: 'Kyat',
    currencyCode: 'MMK',
    governmentFormTr: null,
    independenceNoteTr: "4 Ocak 1948'de İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'PH',
    isoCodeAlpha3: 'PHL',
    nameTr: 'Filipinler',
    nameEn: 'Philippines',
    slugTr: 'filipinler',
    slugEn: 'philippines',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 116_786_962,
    populationYear: null,
    areaKm2: 298_170,
    capitalNameTr: 'Manila',
    capitalNameEn: 'Manila',
    capitalLatitude: 14.5995,
    capitalLongitude: 120.9842,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Filipince', 'İngilizce'],
    currencyNameTr: 'Peso',
    currencyCode: 'PHP',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "12 Haziran 1898'de İspanya'dan bağımsızlık ilan edildi (resmî kutlanan tarih); ABD'den fiilî egemenlik devri 4 Temmuz 1946'da gerçekleşti.",
  },
  {
    isoCode: 'SG',
    isoCodeAlpha3: 'SGP',
    nameTr: 'Singapur',
    nameEn: 'Singapore',
    slugTr: 'singapur',
    slugEn: 'singapore',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 6_111_175,
    populationYear: null,
    areaKm2: 718,
    capitalNameTr: 'Singapur',
    capitalNameEn: 'Singapore',
    capitalLatitude: 1.3521,
    capitalLongitude: 103.8198,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Malayca', 'Mandarin Çincesi', 'Tamilce', 'İngilizce'],
    currencyNameTr: 'Singapur Doları',
    currencyCode: 'SGD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "9 Ağustos 1965'te Malezya Federasyonu'ndan ayrılarak bağımsız oldu.",
  },
  {
    isoCode: 'TH',
    isoCodeAlpha3: 'THA',
    nameTr: 'Tayland',
    nameEn: 'Thailand',
    slugTr: 'tayland',
    slugEn: 'thailand',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 71_619_863,
    populationYear: null,
    areaKm2: 510_890,
    capitalNameTr: 'Bangkok',
    capitalNameEn: 'Bangkok',
    capitalLatitude: 13.7563,
    capitalLongitude: 100.5018,
    neighborIsoCodes: ['MM', 'LA', 'KH', 'MY'],
    officialLanguagesTr: ['Tayca'],
    currencyNameTr: 'Baht',
    currencyCode: 'THB',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: null,
  },
  {
    isoCode: 'TL',
    isoCodeAlpha3: 'TLS',
    nameTr: 'Doğu Timor',
    nameEn: 'Timor-Leste',
    slugTr: 'dogu-timor',
    slugEn: 'timor-leste',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 1_418_517,
    populationYear: null,
    areaKm2: 14_870,
    capitalNameTr: 'Dili',
    capitalNameEn: 'Dili',
    capitalLatitude: -8.5569,
    capitalLongitude: 125.5603,
    neighborIsoCodes: ['ID'],
    officialLanguagesTr: ['Tetum', 'Portekizce'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Yarı-başkanlık cumhuriyeti',
    independenceNoteTr:
      "28 Kasım 1975'te Portekiz'den bağımsızlık ilan edildi; fiilî bağımsızlık, BM geçici yönetiminin ardından 20 Mayıs 2002'de gerçekleşti.",
  },
  {
    isoCode: 'VN',
    isoCodeAlpha3: 'VNM',
    nameTr: 'Vietnam',
    nameEn: 'Vietnam',
    slugTr: 'vietnam',
    slugEn: 'vietnam',
    continent: Continent.Asia,
    unSubregionTr: 'Güneydoğu Asya',
    population: 101_598_527,
    populationYear: null,
    areaKm2: 313_429,
    capitalNameTr: 'Hanoi',
    capitalNameEn: 'Hanoi',
    capitalLatitude: 21.0285,
    capitalLongitude: 105.8542,
    neighborIsoCodes: ['CN', 'LA', 'KH'],
    officialLanguagesTr: ['Vietnamca'],
    currencyNameTr: 'Dong',
    currencyCode: 'VND',
    governmentFormTr: 'Tek parti sosyalist cumhuriyet',
    independenceNoteTr: "2 Eylül 1945'te bağımsızlığını ilan etti (kuzey-güney birleşme 1976).",
  },
  {
    isoCode: 'AF',
    isoCodeAlpha3: 'AFG',
    nameTr: 'Afganistan',
    nameEn: 'Afghanistan',
    slugTr: 'afganistan',
    slugEn: 'afghanistan',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 43_844_111,
    populationYear: null,
    areaKm2: 652_230,
    capitalNameTr: 'Kabil',
    capitalNameEn: 'Kabul',
    capitalLatitude: 34.5553,
    capitalLongitude: 69.2075,
    neighborIsoCodes: ['CN', 'PK', 'IR', 'TM', 'UZ', 'TJ'],
    officialLanguagesTr: ['Peştuca', 'Deri'],
    currencyNameTr: 'Afgani',
    currencyCode: 'AFN',
    governmentFormTr: null,
    independenceNoteTr:
      "19 Ağustos 1919'da İngiltere'den bağımsız oldu (III. Anglo-Afgan Savaşı sonrası).",
  },
  {
    isoCode: 'BD',
    isoCodeAlpha3: 'BGD',
    nameTr: 'Bangladeş',
    nameEn: 'Bangladesh',
    slugTr: 'banglades',
    slugEn: 'bangladesh',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 175_686_899,
    populationYear: null,
    areaKm2: 129_980,
    capitalNameTr: 'Dakka',
    capitalNameEn: 'Dhaka',
    capitalLatitude: 23.8103,
    capitalLongitude: 90.4125,
    neighborIsoCodes: ['IN', 'MM'],
    officialLanguagesTr: ['Bengalce'],
    currencyNameTr: 'Taka',
    currencyCode: 'BDT',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "26 Mart 1971'de Pakistan'dan bağımsızlığını ilan etti (Bangladeş Kurtuluş Savaşı).",
  },
  {
    isoCode: 'BT',
    isoCodeAlpha3: 'BTN',
    nameTr: 'Bhutan',
    nameEn: 'Bhutan',
    slugTr: 'bhutan',
    slugEn: 'bhutan',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 796_682,
    populationYear: null,
    areaKm2: 38_140,
    capitalNameTr: 'Thimphu',
    capitalNameEn: 'Thimphu',
    capitalLatitude: 27.4712,
    capitalLongitude: 89.6339,
    neighborIsoCodes: ['CN', 'IN'],
    officialLanguagesTr: ['Dzongkha'],
    currencyNameTr: 'Ngultrum',
    currencyCode: 'BTN',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: null,
  },
  {
    isoCode: 'IN',
    isoCodeAlpha3: 'IND',
    nameTr: 'Hindistan',
    nameEn: 'India',
    slugTr: 'hindistan',
    slugEn: 'india',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 1_463_865_525,
    populationYear: null,
    areaKm2: 2_973_190,
    capitalNameTr: 'Yeni Delhi',
    capitalNameEn: 'New Delhi',
    capitalLatitude: 28.6139,
    capitalLongitude: 77.209,
    neighborIsoCodes: ['PK', 'CN', 'NP', 'BT', 'BD', 'MM'],
    officialLanguagesTr: ['Hintçe', 'İngilizce'],
    currencyNameTr: 'Hindistan Rupisi',
    currencyCode: 'INR',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    independenceNoteTr: "15 Ağustos 1947'de İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'MV',
    isoCodeAlpha3: 'MDV',
    nameTr: 'Maldivler',
    nameEn: 'Maldives',
    slugTr: 'maldivler',
    slugEn: 'maldives',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 529_676,
    populationYear: null,
    areaKm2: 298,
    capitalNameTr: 'Male',
    capitalNameEn: 'Malé',
    capitalLatitude: 4.1755,
    capitalLongitude: 73.5093,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Divehi'],
    currencyNameTr: 'Rufiyaa',
    currencyCode: 'MVR',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "26 Temmuz 1965'te İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'NP',
    isoCodeAlpha3: 'NPL',
    nameTr: 'Nepal',
    nameEn: 'Nepal',
    slugTr: 'nepal',
    slugEn: 'nepal',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 29_618_118,
    populationYear: null,
    areaKm2: 143_350,
    capitalNameTr: 'Katmandu',
    capitalNameEn: 'Kathmandu',
    capitalLatitude: 27.7172,
    capitalLongitude: 85.324,
    neighborIsoCodes: ['CN', 'IN'],
    officialLanguagesTr: ['Nepalce'],
    currencyNameTr: 'Nepal Rupisi',
    currencyCode: 'NPR',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    independenceNoteTr: null,
  },
  {
    isoCode: 'PK',
    isoCodeAlpha3: 'PAK',
    nameTr: 'Pakistan',
    nameEn: 'Pakistan',
    slugTr: 'pakistan',
    slugEn: 'pakistan',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 255_219_554,
    populationYear: null,
    areaKm2: 770_880,
    capitalNameTr: 'İslamabad',
    capitalNameEn: 'Islamabad',
    capitalLatitude: 33.6844,
    capitalLongitude: 73.0479,
    neighborIsoCodes: ['IN', 'CN', 'AF', 'IR'],
    officialLanguagesTr: ['Urduca', 'İngilizce'],
    currencyNameTr: 'Pakistan Rupisi',
    currencyCode: 'PKR',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    independenceNoteTr:
      "14 Ağustos 1947'de İngiltere'den bağımsız oldu (Hindistan'ın bölünmesiyle).",
  },
  {
    isoCode: 'LK',
    isoCodeAlpha3: 'LKA',
    nameTr: 'Sri Lanka',
    nameEn: 'Sri Lanka',
    slugTr: 'sri-lanka',
    slugEn: 'sri-lanka',
    continent: Continent.Asia,
    unSubregionTr: 'Güney Asya',
    population: 21_756_000,
    populationYear: null,
    areaKm2: 61_860,
    capitalNameTr: 'Sri Jayewardenepura Kotte',
    capitalNameEn: 'Sri Jayewardenepura Kotte',
    capitalLatitude: 6.9008,
    capitalLongitude: 79.9553,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Sinhalaca', 'Tamilce'],
    currencyNameTr: 'Sri Lanka Rupisi',
    currencyCode: 'LKR',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "4 Şubat 1948'de İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'BH',
    isoCodeAlpha3: 'BHR',
    nameTr: 'Bahreyn',
    nameEn: 'Bahrain',
    slugTr: 'bahreyn',
    slugEn: 'bahrain',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 1_600_366,
    populationYear: null,
    areaKm2: 800,
    capitalNameTr: 'Manama',
    capitalNameEn: 'Manama',
    capitalLatitude: 26.2285,
    capitalLongitude: 50.586,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Bahreyn Dinarı',
    currencyCode: 'BHD',
    governmentFormTr: 'Anayasal monarşi',
    independenceNoteTr: "15 Ağustos 1971'de İngiltere'den bağımsız oldu.",
  },
  {
    isoCode: 'JO',
    isoCodeAlpha3: 'JOR',
    nameTr: 'Ürdün',
    nameEn: 'Jordan',
    slugTr: 'urdun',
    slugEn: 'jordan',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 11_520_684,
    populationYear: null,
    areaKm2: 88_794,
    capitalNameTr: 'Amman',
    capitalNameEn: 'Amman',
    capitalLatitude: 31.9454,
    capitalLongitude: 35.9284,
    neighborIsoCodes: ['SY', 'IQ', 'SA', 'IL'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Ürdün Dinarı',
    currencyCode: 'JOD',
    governmentFormTr: 'Üniter parlamenter anayasal monarşi',
    independenceNoteTr: "25 Mayıs 1946'da İngiliz manda yönetiminden bağımsız oldu.",
    introTr:
      "Ürdün Çöküntü Vadisi'nin doğu yamacında kurulu Ürdün, denize yalnızca güneybatı " +
      'ucundaki Akabe Körfezi üzerinden kısa bir şeritle açılır. Kuzeyde Suriye, doğuda ' +
      'Irak, güneyde ve doğuda Suudi Arabistan, batıda İsrail ile komşudur.',
    landformNoteTr:
      'Ülkenin batı sınırını, Büyük Rift Vadisi sisteminin bir parçası olan Ürdün Çöküntü ' +
      'Vadisi çizer; bu derin çöküntü, çevresindeki platolardan 1.200-2.000 metre aşağıda ' +
      "kalır ve dip noktasında, Dünya'nın kara yüzeyindeki en alçak noktası olan Ölü " +
      "Deniz'e ulaşır. Ölü Deniz'in su seviyesi yılda yaklaşık 1 metre düşmeye devam ediyor; " +
      'bugün deniz seviyesinin yaklaşık 440 metre altındadır.' +
      '\n\n' +
      'Çöküntü vadisinin doğusunda, 600-1.000 metre rakımlı kıvrımlı kireçtaşı sırtlardan ' +
      'oluşan Aclun ve Belka yaylaları yükselir; Vadi Mucib ve Vadi Hasa gibi vadiler bu ' +
      'yaylaları derin kanyonlarla yarar. Ülkenin en yüksek noktası, güneydeki ıssız bir ' +
      "kesimde yer alan 1.854 metrelik Jabal Umm ad-Dami'dir. Doğuda, Suudi Arabistan ve " +
      'Irak sınırlarına kadar uzanan Bâdiye, yaylalara yakın kesimde 900 metreden sınıra ' +
      'doğru 600 metreye alçalan, yer yer bazalt kütleleriyle kaplı bir çöl platosudur.',
    climateNoteTr:
      'Çöküntü vadisinin batısındaki yaylalarda Akdeniz iklimi görülür; yıllık yağış ' +
      'kuzeyde 500 milimetreyi bulurken güneye doğru 300 milimetreye iner. Ölü Deniz ve ' +
      'Ürdün Nehri çevresindeki çöküntü vadisi tabanında, yaz sıcaklarının ve düşük rakımın ' +
      '(deniz seviyesinin altında) birleşiminden doğan subtropikal bir iklim hakimdir, ' +
      "yıllık yağış yaklaşık 200 milimetredir. Ülkenin yaklaşık %90'ını oluşturan doğu ve " +
      'güney kesimlerinde ise yıllık yağış 100 milimetrenin altına düşen bir çöl iklimi ' +
      'egemendir.',
    hydrographyNoteTr:
      'Ülkenin batı sınırını izleyen Ürdün Nehri, Yarmuk ve Zerka nehirlerinden beslenir; ' +
      'Suriye-Ürdün sınırının bir bölümünü çizen Yarmuk, nehrin en büyük kolu ve Ürdün ' +
      "Vadisi'ndeki tarımın ana su kaynağıdır. Amman yakınlarındaki kaynaklardan doğan " +
      "Zerka, derin bir vadiden geçerek Ürdün Nehri'ne katılır. Nehir, güneyde kapalı bir " +
      "havza olan Ölü Deniz'de son bulur; yukarı havzadaki yoğun su kullanımı nedeniyle " +
      'nehrin yıllık debisi geçmiş dönemlere kıyasla büyük ölçüde azalmıştır.',
  },
  {
    isoCode: 'KW',
    isoCodeAlpha3: 'KWT',
    nameTr: 'Kuveyt',
    nameEn: 'Kuwait',
    slugTr: 'kuveyt',
    slugEn: 'kuwait',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 4_865_298,
    populationYear: null,
    areaKm2: 17_820,
    capitalNameTr: 'Kuveyt Şehri',
    capitalNameEn: 'Kuwait City',
    capitalLatitude: 29.3759,
    capitalLongitude: 47.9774,
    neighborIsoCodes: ['IQ', 'SA'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Kuveyt Dinarı',
    currencyCode: 'KWD',
    governmentFormTr: 'Anayasal monarşi (Emirlik)',
    independenceNoteTr: "19 Haziran 1961'de İngiltere'den bağımsız oldu.",
    introTr:
      "Basra Körfezi'nin kuzeybatı köşesinde, kıyısını Kuveyt Körfezi'nin derin bir " +
      'girintisiyle paylaşan Kuveyt, neredeyse tamamen düz bir çöl ülkesidir. Kuzeyde ve ' +
      'batıda Irak, güneyde Suudi Arabistan ile komşudur.',
    landformNoteTr:
      'Ülke arazisi, Basra Körfezi kıyısındaki deniz seviyesinden kuzeybatıdaki Mutla ' +
      "Sırtı'na kadar kademeli olarak yükselir; ülkenin en yüksek noktası olan bu sırt 306 " +
      "metreye ulaşır. Kuveyt Körfezi'nin kuzey kıyısına hakim Cal ez-Zor sırtı 145 " +
      'metreyi, güneydeki Ahmedi tepesi ise 137 metreyi bulur — bunların dışında arazi ' +
      'büyük ölçüde düzdür.' +
      '\n\n' +
      'Kuveyt Körfezi, kıyı şeridine yaklaşık 40 kilometre sokularak ülkenin 195 ' +
      'kilometrelik toplam kıyı uzunluğunun yaklaşık üçte birini oluşturur; başkent Kuveyt ' +
      "Şehri'nin limanını doğal olarak korur. Ülkeye bağlı dokuz adadan en büyüğü, 863 " +
      "kilometrekarelik yüzölçümüyle Kuveyt topraklarının yaklaşık %5'ini oluşturan " +
      "Bubiyan'dır — tuz düzlükleri, gelgit çamurları ve mangrovlarla kaplı bu bataklık ada, " +
      'askeri bir köprüyle karaya bağlıdır.',
    climateNoteTr:
      'Kuveyt, beş aydan uzun süren yazlarında sıcaklığın sık sık 50 santigrat dereceyi ' +
      "aştığı, aşırı kurak bir çöl iklimine sahiptir. 2016'da Mitriba'da ölçülen 54,0 " +
      'santigrat derece, Asya kıtasında ölçülmüş en yüksek sıcaklık kaydıdır. Kışlar kısa ve ' +
      'ılımlıdır; sınırlı ve düzensiz yağış Kasım-Şubat arasına yoğunlaşır, toz fırtınaları ' +
      'yılın büyük bölümünde görülür.',
    hydrographyNoteTr:
      'Ülkede doğal göl ya da nehir yoktur; tek yerel su kaynağı, denize yakınlığı ve aşırı ' +
      'çekim nedeniyle giderek tuzlanan acı yeraltı sularıdır. Kuveyt, tatlı su ihtiyacının ' +
      'büyük bölümünü deniz suyu arıtma tesislerinden karşılar — 2023 yılında 0,8 milyar ' +
      'metreküp arıtılmış su üretildi.',
  },
  {
    isoCode: 'LB',
    isoCodeAlpha3: 'LBN',
    nameTr: 'Lübnan',
    nameEn: 'Lebanon',
    slugTr: 'lubnan',
    slugEn: 'lebanon',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 5_849_421,
    populationYear: null,
    areaKm2: 10_230,
    capitalNameTr: 'Beyrut',
    capitalNameEn: 'Beirut',
    capitalLatitude: 33.8938,
    capitalLongitude: 35.5018,
    neighborIsoCodes: ['SY', 'IL'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Lübnan Lirası',
    currencyCode: 'LBP',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "22 Kasım 1943'te Fransız manda yönetiminden bağımsız oldu.",
    introTr:
      'Lübnan, kıyıdan iç kesime doğru birbirine paralel dört kuşaktan oluşur: dar bir kıyı ' +
      'ovası, Lübnan Dağları, Bekaa Vadisi ve Anti-Lübnan Dağları. Küçük yüzölçümüne karşın ' +
      'bu dört kuşak arasında büyük bir rakım farkı vardır. Kuzeyde ve doğuda Suriye, ' +
      'güneyde İsrail ile komşudur.',
    landformNoteTr:
      'Akdeniz kıyısına paralel uzanan Lübnan Dağları, yaklaşık 170 kilometre boyunca ' +
      'ülkeyi kuzeyden güneye kat eder; genişliği Trablus yakınında 56,5 kilometreye ' +
      'ulaşırken güneyde 9,5 kilometreye kadar daralır. Sıradağın en yüksek noktası, 3.088 ' +
      "metrelik Kurnet es Sevda'dır." +
      '\n\n' +
      "Lübnan Dağları'nın doğusunda, Doğu Afrika Rift Sistemi'nin bir uzantısı sayılan Bekaa " +
      'Vadisi yer alır; 800-1.100 metre rakımlı, yaklaşık 120 kilometre uzunluğunda ve ' +
      '10-20 kilometre genişliğindeki bu çöküntü, kalın alüvyon dolgusuyla ülkenin en verimli ' +
      "tarım alanını oluşturur. Vadinin doğusunda, Lübnan Dağları'na paralel uzanan " +
      'Anti-Lübnan Dağları, güney ucunda 2.814 metreye kadar yükselir.',
    climateNoteTr:
      'Kıyı şeridinde sıcak-kurak yaz ve ılık-yağışlı kışın görüldüğü tipik bir Akdeniz ' +
      "iklimi hakimdir. Lübnan Dağları'nın yüksek kesimleri kışın kalıcı kar örtüsüyle " +
      'kaplanır; bu yükseklik, kıyıdan yalnızca birkaç saat mesafede kayak turizmine imkan ' +
      'tanır. Bekaa Vadisi, iki paralel sıradağ arasında kaldığı için deniz etkisinden büyük ' +
      'ölçüde uzaktır — kışları daha soğuk, yazları ise daha sıcak ve kurak bir karasal iklim ' +
      'burada egemendir.',
    hydrographyNoteTr:
      "Tamamen Lübnan sınırları içinde akan en uzun nehir, Bekaa Vadisi'nde Baalbek'in " +
      "batısından doğan ve Sur kentinin kuzeyinde Akdeniz'e dökülen 140 kilometreden uzun " +
      "Litani'dir; 2.110 kilometrekarelik havzası ülke topraklarının yaklaşık beşte birini " +
      'kaplar ve ülkenin toplam akarsu debisinin yaklaşık üçte birini sağlar, sulama ve ' +
      "hidroelektrik üretiminde kullanılır. Kuzey Bekaa'da, Hermel yakınlarında doğan Asi " +
      "(Orontes) Nehri ise kuzeye, Suriye üzerinden Türkiye'ye akarak Akdeniz'e ulaşır. " +
      "Ülkede toplam 40 nehir sayılır, bunlardan 16'sı yıl boyu akar.",
  },
  {
    isoCode: 'OM',
    isoCodeAlpha3: 'OMN',
    nameTr: 'Umman',
    nameEn: 'Oman',
    slugTr: 'umman',
    slugEn: 'oman',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 5_494_691,
    populationYear: null,
    areaKm2: 309_500,
    capitalNameTr: 'Maskat',
    capitalNameEn: 'Muscat',
    capitalLatitude: 23.588,
    capitalLongitude: 58.3829,
    neighborIsoCodes: ['SA', 'AE', 'YE'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Umman Riyali',
    currencyCode: 'OMR',
    governmentFormTr: 'Mutlak monarşi (Sultanlık)',
    independenceNoteTr: null,
    introTr:
      'Arap Denizi ve Umman Körfezi boyunca 3.000 kilometreyi aşan kıyı şeridiyle Umman, ' +
      'kümedeki sekiz ülke arasında kıyısı en uzun olanıdır. Ülkenin kuzeyindeki Musandam ' +
      'Yarımadası, Birleşik Arap Emirlikleri topraklarıyla ana kara parçasından ayrılmış bir ' +
      'eksklavdır. Suudi Arabistan, BAE ve Yemen ile komşudur.',
    landformNoteTr:
      "Musandam'dan ülkenin doğu kıyısına kadar yaklaşık 700 kilometre uzanan Hacer " +
      "Dağları, Arap Yarımadası'nın en yüksek sıradağlarından biridir; yaklaşık 100 " +
      'kilometre genişliğindeki bu kuşağın en yüksek noktası, Jabal Ahdar kütlesinin bir ' +
      "parçası olan 3.009 metrelik Jabal Şems'tir. Ülke topraklarının yaklaşık %82'sini " +
      "vadiler ve çöl, %15'ini dağlar, yalnızca %3'ünü ise dar kıyı ovası (Batına) " +
      'oluşturur.' +
      '\n\n' +
      "Batıda ve iç kesimde ülke toprakları, dünyanın en büyük kum çölü olan Rubalhali'nin " +
      "bir uzantısıyla birleşir. Musandam Yarımadası'nın kıyısı ise ülkenin geri kalanından " +
      "tamamen farklı bir karakter taşır: Arap Levhası'nın bu kesimde Avrasya Levhası'nın " +
      'altına dalması nedeniyle kıyı çizgisi çöküyor, bu da "Arabistan\'ın Norveç\'i" olarak ' +
      'anılan fiyort benzeri girintili bir kıyı oluşturuyor.',
    climateNoteTr:
      "Jabal Ahdar'ın 2.000 metreyi aşan kesimleri dışında, ülke genelinde sıcak ve kurak " +
      'bir çöl iklimi hakimdir. Bu yükseklerde iklim tamamen değişir: yıllık yağış 500 ' +
      'milimetreye ulaşır, serin hava gül bahçelerinin ve meyve teraslarının yetişmesine ' +
      'imkan tanır — Nisan ayındaki gül hasadı, bu serin yükseklik sayesinde mümkün olur. ' +
      "Güneydeki Zufar bölgesi ise Umman'a özgü bir başka iklim istisnasıdır: Haziran-Eylül " +
      'arasında Hint Okyanusu\'ndan gelen "khareef" musonu, Salalah çevresindeki kahverengi ' +
      'tepeleri yemyeşile çevirir ve mevsimlik şelaleler oluşturur.',
    hydrographyNoteTr:
      "Umman'da kalıcı akan bir nehir yoktur; yağış sonrası dolan vadiler ülkenin başlıca " +
      'yüzey suyu kaynağıdır. Yüzyıllardır kullanılan eflec sulama kanalları, yeraltı suyunu ' +
      'yükseklerden yerçekimiyle taşıyarak özellikle Jabal Ahdar ve Batına kıyısındaki ' +
      'teraslı tarımı besler. Zufar bölgesi ise musonun etkisiyle yıl boyu akan derelere ' +
      'sahiptir — bu özellik, bölgeyi ülkenin en verimli tarım alanı haline getirir.',
  },
  {
    isoCode: 'QA',
    isoCodeAlpha3: 'QAT',
    nameTr: 'Katar',
    nameEn: 'Qatar',
    slugTr: 'katar',
    slugEn: 'qatar',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 2_972_215,
    populationYear: null,
    areaKm2: 11_490,
    capitalNameTr: 'Doha',
    capitalNameEn: 'Doha',
    capitalLatitude: 25.2854,
    capitalLongitude: 51.531,
    neighborIsoCodes: ['SA'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Katar Riyali',
    currencyCode: 'QAR',
    governmentFormTr: 'Mutlak monarşi (Emirlik)',
    independenceNoteTr: "3 Eylül 1971'de İngiltere'den bağımsız oldu.",
    introTr:
      "Arap Yarımadası'ndan Basra Körfezi'ne yaklaşık 160 kilometre boyunca uzanan dar bir " +
      'yarımada üzerinde kurulu Katar, kara sınırında yalnızca Suudi Arabistan ile komşudur; ' +
      'kümedeki sekiz ülke arasında tek kara komşusu bulunan tek ülkesidir.',
    landformNoteTr:
      'Yarımadanın genişliği 55 ile 90 kilometre arasında değişir, arazi genel olarak ' +
      'düzdür. Doğu kesiminde ince kum ve tozla kaplı geniş düzlükler, güney ve güneybatıda ' +
      'ise kum tepeleri ve sebha adı verilen tuz düzlükleri yer alır; bu özellik özellikle ' +
      'Mesaid ve Hor el-Adid çevresinde belirginleşir. Ülkenin arazisine serpilmiş, yatay ' +
      'tabakalı ve sert kayaçla kaplı düz tepeli tepecikler ile daha geniş mesa benzeri ' +
      'yükseltiler de görülür.' +
      '\n\n' +
      "Ülkenin en yüksek noktası, güneydeki Kurayn Ebü'l-Bevl'dir ve deniz seviyesinden " +
      "yalnızca 103 metre yükseklikte kalır. Abu Samra'dan Hor el-Adid'e kadar yaklaşık " +
      '650 kilometre uzanan kıyı şeridi, "İç Deniz" olarak da bilinen Hor el-Adid gelgit ' +
      'koyuyla güneyde sona erer.',
    climateNoteTr:
      "Katar, Basra Körfezi'nin sığ ve sıcak sularının etkisiyle yaz aylarında hem " +
      'sıcaklığın hem de nemin aynı anda çok yüksek seyrettiği bir çöl iklimine sahiptir; bu ' +
      'birleşim, kıyı kesimlerinde hissedilen sıcaklığı ölçülen değerin belirgin biçimde ' +
      'üzerine çıkarır. Yıllık yağış oldukça düşüktür ve neredeyse tamamı kış aylarındaki ' +
      'kısa, düzensiz sağanaklardan oluşur.',
    hydrographyNoteTr:
      "Katar'da kalıcı nehir ya da doğal tatlı su gölü bulunmaz; sınırlı yeraltı suyu " +
      'kaynakları aşırı çekim nedeniyle tükenme eğilimindedir. İçme suyunun neredeyse tamamı ' +
      "deniz suyu arıtmasıyla karşılanıyor; 2023'te üretilen 0,7 milyar metreküp arıtılmış " +
      'su, bu bağımlılığın ölçüsünü gösteriyor. Güneydeki Hor el-Adid, çölün ortasında ' +
      'denizle birleşen gelgit koyu yapısıyla ülkenin en ayırt edici su kütlesidir.',
  },
  {
    isoCode: 'SA',
    isoCodeAlpha3: 'SAU',
    nameTr: 'Suudi Arabistan',
    nameEn: 'Saudi Arabia',
    slugTr: 'suudi-arabistan',
    slugEn: 'saudi-arabia',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 36_973_555,
    populationYear: null,
    areaKm2: 2_149_690,
    capitalNameTr: 'Riyad',
    capitalNameEn: 'Riyadh',
    capitalLatitude: 24.7136,
    capitalLongitude: 46.6753,
    neighborIsoCodes: ['JO', 'IQ', 'KW', 'QA', 'AE', 'OM', 'YE'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Suudi Arabistan Riyali',
    currencyCode: 'SAR',
    governmentFormTr: 'Mutlak monarşi',
    independenceNoteTr: null,
    introTr:
      "Arap Yarımadası'nın büyük bölümünü kaplayan Suudi Arabistan, batıda Kızıldeniz'e, " +
      "doğuda ise Basra Körfezi'ne kıyısı olan bir ülkedir. Ürdün, Irak, Kuveyt, Katar, " +
      'Birleşik Arap Emirlikleri, Umman ve Yemen ile toplam yedi ülkeyle kara sınırı ' +
      'paylaşır — bu kümedeki en fazla kara komşusuna sahip ülkedir.',
    landformNoteTr:
      'Ülkenin batısında, Kızıldeniz kıyısı boyunca kuzeyde Hicaz, güneyde ise Asir dağları ' +
      "uzanır; bu dağlık kuşak dar bir kıyı ovasının hemen ardından yükselir. Asir'de, Ebha " +
      'yakınlarında yükselen, resmi olarak 3.015 metre kabul edilen Jabal Sawda, ülkenin en ' +
      'yüksek noktasıdır. Dağların doğusunda, ülkenin ortasını geniş bir plato olan Necid ' +
      'kaplar.' +
      '\n\n' +
      "Necid'in kuzeyinde An-Nefud, güneyinde ise dünyanın en büyük kum çölü olan Rubalhali " +
      "uzanır; Rubalhali'nin 650.000 kilometrekarelik alanı Suudi Arabistan'ın yanı sıra " +
      'Umman, BAE ve Yemen topraklarına da taşar, kimi kum tepeleri 250 metreyi bulur. İki ' +
      'çölü birbirine bağlayan Ed-Dehna kum koridoru, ülkenin doğu-batı ekseninde bir hilal ' +
      'çizer.',
    climateNoteTr:
      'Ülkenin büyük bölümünde, yıllık yağışın 100 milimetrenin altında kaldığı tam kurak ' +
      'bir çöl iklimi egemendir; yazlar aşırı sıcak, kışlar iç kesimlerde soğuk geçer. Asir ' +
      'dağları bu genel tabloyu bozan tek bölgedir: Hint Okyanusu kaynaklı yaz musonunun ' +
      'etkisiyle, yükseklere doğru yıllık yağış 600-1.000 milimetreye çıkar, bulutlu ve serin ' +
      'bir dağ iklimi oluşur. Bu nem, teraslanmış tarım alanlarını ve dağ ormanlarını besler ' +
      '— ülkenin geri kalanında görülmeyen bir yeşillik kuşağıdır.',
    hydrographyNoteTr:
      "Suudi Arabistan'da kalıcı akan bir nehir yoktur; yüzey suyu, nadir yağmurlarda dolan " +
      "vadilerle taşınır. En uzun vadi, Nefud Çölü'nden Dibdibe ovasına kadar " +
      "yaklaşık 600 kilometre uzanan Vadi er-Rumme'dir; Riyad'ı kuzeybatıdan güneydoğuya kat " +
      'eden 120 kilometrelik Vadi Hanife ise başkentin coğrafi omurgasını oluşturur. Tatlı ' +
      'su ihtiyacının büyük bölümü, vadi yataklarındaki yeraltı akiferlerinden ve kıyı ' +
      'kentlerinde deniz suyu arıtma tesislerinden karşılanır.',
  },
  {
    isoCode: 'AE',
    isoCodeAlpha3: 'ARE',
    nameTr: 'Birleşik Arap Emirlikleri',
    nameEn: 'United Arab Emirates',
    slugTr: 'birlesik-arap-emirlikleri',
    slugEn: 'united-arab-emirates',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 11_513_149,
    populationYear: null,
    areaKm2: 71_020,
    capitalNameTr: 'Abu Dabi',
    capitalNameEn: 'Abu Dhabi',
    capitalLatitude: 24.4539,
    capitalLongitude: 54.3773,
    neighborIsoCodes: ['SA', 'OM'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'BAE Dirhemi',
    currencyCode: 'AED',
    governmentFormTr: 'Federal mutlak monarşi',
    independenceNoteTr: "2 Aralık 1971'de İngiltere'den bağımsız oldu (7 emirliğin federasyonu).",
    introTr:
      'Yedi emirliğin federasyonu olan Birleşik Arap Emirlikleri, batıda uzun bir Basra ' +
      "Körfezi kıyısına, doğuda ise Umman Körfezi'ne açılan kısa bir şeride sahiptir. Kara " +
      'sınırında yalnızca Suudi Arabistan ve Umman ile komşudur.',
    landformNoteTr:
      "Ülkenin doğusunda, Ras Al Khaimah'tan Fujayra'ya uzanan Batı Hacer Dağları yükselir; " +
      'bu sıradağ ülkeyi kıyı kesimi ile iç kesimden ayırır. Sıradağın en yüksek noktası ' +
      "olarak anılan 1.934 metrelik Jebel Jais, Ras Al Khaimah'ta yer alır." +
      '\n\n' +
      'Ülke topraklarının büyük bölümünü kaplayan çölde, Liva vahası çevresindeki kum ' +
      "tepeleri dünyanın en büyüklerinden sayılır — bu bölge, güneyde Rubalhali'nin bir " +
      'uzantısıdır. Basra Körfezi kıyısı, çok sayıda koy ve adayla girintili-çıkıntılıdır; ' +
      "Umman Körfezi'ndeki Batina kıyısı ise dar bir şerit halinde yaklaşık 90 kilometre " +
      'uzanır.',
    climateNoteTr:
      'Ülke genelinde, yazın 45 santigrat dereceyi aşan sıcaklıklarla tam kurak bir çöl ' +
      'iklimi görülür. Basra Körfezi kıyısında sıcaklığa yüksek nem eşlik eder; iç ' +
      'kesimlerde ve çölde ise hava daha kuru, gece-gündüz sıcaklık farkı daha belirgindir. ' +
      "Hacer Dağları'nın yüksek kesimlerinde rakım etkisiyle sıcaklıklar bir ölçüde düşer.",
    hydrographyNoteTr:
      "Ülkede kalıcı akan bir nehir ya da doğal göl yoktur; Hacer Dağları'nın eteklerinde " +
      'yer yer yağmur sonrası dolan vadiler bulunur. Yüzyıllardır kullanılan eflec sistemi, ' +
      'yeraltı suyunu yükseklerden yerçekimiyle kilometrelerce taşıyarak vaha tarımını ' +
      'besler. Bugün Al Ain ve Liva gibi iç vahaların içme suyu ihtiyacı tamamen deniz suyu ' +
      'arıtma tesislerinden karşılanıyor.',
  },
  {
    isoCode: 'YE',
    isoCodeAlpha3: 'YEM',
    nameTr: 'Yemen',
    nameEn: 'Yemen',
    slugTr: 'yemen',
    slugEn: 'yemen',
    continent: Continent.Asia,
    unSubregionTr: 'Batı Asya',
    population: 41_773_878,
    populationYear: null,
    areaKm2: 527_970,
    capitalNameTr: 'Sana',
    capitalNameEn: 'Sanaa',
    capitalLatitude: 15.3694,
    capitalLongitude: 44.191,
    neighborIsoCodes: ['SA', 'OM'],
    officialLanguagesTr: ['Arapça'],
    currencyNameTr: 'Yemen Riyali',
    currencyCode: 'YER',
    governmentFormTr: null,
    independenceNoteTr:
      "22 Mayıs 1990'da Kuzey ve Güney Yemen birleşerek Yemen Cumhuriyeti'ni kurdu.",
    introTr:
      "Arap Yarımadası'nın güneybatı köşesinde yer alan Yemen, batıda Kızıldeniz'e, güneyde " +
      "ise Aden Körfezi ve Arap Denizi'ne kıyısı olan dağlık bir ülkedir. Hint " +
      "Okyanusu'nda, ana kara parçasından yaklaşık 380 kilometre güneyde yer alan Sokotra " +
      'Adası da ülke topraklarına dahildir. Kuzeyde Suudi Arabistan, doğuda Umman ile ' +
      'komşudur.',
    landformNoteTr:
      'Kızıldeniz kıyısı boyunca dar bir kıyı ovası olan Tihame uzanır; bu ova, iç kesime ' +
      'doğru dik bir yamaçla merkezi yaylalara yükselir. 2.000-3.200 metre rakımlı bu yayla, ' +
      'tepeler ve küçük dağlardan oluşur; yaylanın üzerinde yükselen 3.666 metrelik Jabal ' +
      "en-Nebi Şuayb, hem Yemen'in hem de tüm Arap Yarımadası'nın en yüksek noktasıdır. " +
      "Yaylalar doğuya doğru alçalarak ülkenin kuzeydoğusunda Rubalhali'nin bir uzantısına " +
      'dönüşür.' +
      '\n\n' +
      'Ülkenin doğusunda, üst kesimi alüvyal toprak ve sel sularıyla beslenen, alt kesimi ' +
      'ise ıssız ve çorak Vadi Hadramut yer alır — bölgenin en büyük vadi sistemidir. Hint ' +
      "Okyanusu'ndaki Sokotra Adası'nın iç kesimini Hacir Dağları kaplar; kuzeyde dar, " +
      'güneyde ise daha geniş kıyı ovaları bulunur, kıyı çizgisi kumsallar, kayalık burunlar ' +
      've korunaklı lagünler arasında değişir.',
    climateNoteTr:
      'Kızıldeniz kıyısındaki Tihame ovası, yıl boyu yüksek sıcaklık ve nemin bir arada ' +
      "görüldüğü sıcak bir iklime sahiptir. Yaklaşık 2.200 metre rakımlı başkent Sana'a " +
      'başta olmak üzere merkezi yaylalarda iklim belirgin biçimde serinler; yazın gündüz ' +
      'sıcaklıkları 20 santigrat derece civarında kalır, kışın gece sıcaklıkları eksiye ' +
      'düşer. Bu serinlik, yüzyıllardır süren teraslı buğday, arpa, kahve ve kat tarımını ' +
      'mümkün kılar. Doğudaki Hadramut ve kuzeydoğudaki çöl kesimlerinde ise yıl boyu sıcak ' +
      've kurak bir iklim egemendir, kimi bölgelerde yıllarca yağış düşmez.',
    hydrographyNoteTr:
      "Yemen'de kalıcı akan bir nehir yoktur; yaylalardan inen mevsimsel vadiler, yağmur " +
      'sonrası kısa süreliğine dolar. Tarım, büyük ölçüde bu vadi tabanlarına, yamaçlara ve ' +
      'akarsu kanallarına bitişik teraslara yoğunlaşmıştır. Ülkenin doğusundaki Vadi ' +
      'Hadramut, tarih boyunca yerleşimin ve tarımın yoğunlaştığı en geniş vadi sistemidir.',
  },
];
