import { Continent } from '../../../common/continent.enum';
import type { CountrySeed } from '../country.seed-data';

/**
 * Avrupa + Okyanusya — dünya haritası base-data seed (55 ülke). Structured fields only; the
 * narrative prose fields (introTr/landformNoteTr/climateNoteTr/hydrographyNoteTr) are
 * seeded null and filled in later regional content waves. populationYear is null across
 * the board (world-scale ruling, DEC 2026-07-13). Source of record:
 * Owner's Inbox/dunya-haritasi-base-data/europe-oceania.md. Every value transcribed from
 * the approved research; slugs generated by an ASCII/Turkish-fold rule (matches the pilot).
 *
 * Avusturya (AT) — NOVA backfilled the source block (Section 3.1, Tier-1 MFA-verified) after
 *   the first sweep omitted it; seeded here with real data. Its independence field uses the
 *   own-national-day rule (26 Ekim 1955 Nationalfeiertag, other dates woven as context).
 *
 * ROUTED ELSEWHERE — Kıbrıs (CY) and Kosova (XK) are in europe-oceania.md but are handled
 *   in the separate sovereignty seed lane (owner-ruled sensitive content), not here.
 *
 * NEIGHBOUR RECIPROCITY (corrected, → DEC 2026-07-13 "CORRECTION: Gibraltar"): the
 *   exclave-inclusive rule applies ONLY to a fully constitutionally-integrated territory
 *   (DROM-equivalent / oblast / autonomous republic) — e.g. France↔Brazil via French Guiana
 *   (a DROM) and Russia↔Lithuania/Poland via Kaliningrad (an oblast) DO count. Gibraltar is a
 *   British Overseas Territory (NOT integrated UK territory), so the ES↔GB land border at
 *   La Línea does NOT propagate to either state's list — GB and ES do NOT carry each other
 *   (an earlier ruling wrongly added them; reversed here). İtalya still carries VA (Vatikan):
 *   that is a genuine bilateral border with a sovereign enclave state, a separate case from
 *   the Gibraltar one. VA is not seeded yet (benign dangling ref, like TR).
 *
 * areaKm2 is whole km² (entity is integer); decimal source values are rounded to nearest
 *   (e.g. İsviçre 39.509,63 → 39_510, Portekiz 91.605,6 → 91_606, Slovenya 20.134,5 →
 *   20_135). Sub-1 km² micro-states round to their nearest whole km².
 */
export const EUROPE_OCEANIA_COUNTRIES: readonly CountrySeed[] = [
  {
    isoCode: 'DK',
    isoCodeAlpha3: 'DNK',
    nameTr: 'Danimarka',
    nameEn: 'Denmark',
    slugTr: 'danimarka',
    slugEn: 'denmark',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 6_009_169,
    populationYear: null,
    areaKm2: 40_000,
    capitalNameTr: 'Kopenhag',
    capitalNameEn: 'Copenhagen',
    capitalLatitude: 55.6761,
    capitalLongitude: 12.5683,
    neighborIsoCodes: ['DE', 'CA'],
    officialLanguagesTr: ['Danca'],
    currencyNameTr: 'Danimarka Kronu',
    currencyCode: 'DKK',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: null,
  },
  {
    isoCode: 'EE',
    isoCodeAlpha3: 'EST',
    nameTr: 'Estonya',
    nameEn: 'Estonia',
    slugTr: 'estonya',
    slugEn: 'estonia',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 1_366_475,
    populationYear: null,
    areaKm2: 42_730,
    capitalNameTr: 'Tallin',
    capitalNameEn: 'Tallinn',
    capitalLatitude: 59.437,
    capitalLongitude: 24.7536,
    neighborIsoCodes: ['LV', 'RU'],
    officialLanguagesTr: ['Estonca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "20 Ağustos 1991'de Sovyetler Birliği'nden bağımsızlığını yeniden kazandı (ilk bağımsızlık 24 Şubat 1918).",
  },
  {
    isoCode: 'FI',
    isoCodeAlpha3: 'FIN',
    nameTr: 'Finlandiya',
    nameEn: 'Finland',
    slugTr: 'finlandiya',
    slugEn: 'finland',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 5_646_436,
    populationYear: null,
    areaKm2: 303_960,
    capitalNameTr: 'Helsinki',
    capitalNameEn: 'Helsinki',
    capitalLatitude: 60.1699,
    capitalLongitude: 24.9384,
    neighborIsoCodes: ['SE', 'NO', 'RU'],
    officialLanguagesTr: ['Fince', 'İsveççe'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "6 Aralık 1917'de Rusya'dan bağımsız oldu.",
  },
  {
    isoCode: 'IS',
    isoCodeAlpha3: 'ISL',
    nameTr: 'İzlanda',
    nameEn: 'Iceland',
    slugTr: 'izlanda',
    slugEn: 'iceland',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 392_404,
    populationYear: null,
    areaKm2: 100_830,
    capitalNameTr: 'Reykjavik',
    capitalNameEn: 'Reykjavik',
    capitalLatitude: 64.1466,
    capitalLongitude: -21.9426,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İzlandaca'],
    currencyNameTr: 'İzlanda Kronası',
    currencyCode: 'ISK',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "17 Haziran 1944'te Danimarka'dan tam bağımsızlığını kazanarak cumhuriyet ilan etti.",
  },
  {
    isoCode: 'IE',
    isoCodeAlpha3: 'IRL',
    nameTr: 'İrlanda',
    nameEn: 'Ireland',
    slugTr: 'irlanda',
    slugEn: 'ireland',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 5_484_367,
    populationYear: null,
    areaKm2: 68_890,
    capitalNameTr: 'Dublin',
    capitalNameEn: 'Dublin',
    capitalLatitude: 53.3498,
    capitalLongitude: -6.2603,
    neighborIsoCodes: ['GB'],
    officialLanguagesTr: ['İrlandaca', 'İngilizce'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "6 Aralık 1922'de İrlanda Serbest Devleti kuruldu (Cumhuriyet ilanı 1949).",
  },
  {
    isoCode: 'LV',
    isoCodeAlpha3: 'LVA',
    nameTr: 'Letonya',
    nameEn: 'Latvia',
    slugTr: 'letonya',
    slugEn: 'latvia',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 1_847_785,
    populationYear: null,
    areaKm2: 62_230,
    capitalNameTr: 'Riga',
    capitalNameEn: 'Riga',
    capitalLatitude: 56.9496,
    capitalLongitude: 24.1052,
    neighborIsoCodes: ['EE', 'LT', 'BY', 'RU'],
    officialLanguagesTr: ['Letonca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "21 Ağustos 1991'de Sovyetler Birliği'nden bağımsızlığını yeniden kazandı (ilk bağımsızlık 18 Kasım 1918).",
  },
  {
    isoCode: 'LT',
    isoCodeAlpha3: 'LTU',
    nameTr: 'Litvanya',
    nameEn: 'Lithuania',
    slugTr: 'litvanya',
    slugEn: 'lithuania',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 2_888_774,
    populationYear: null,
    areaKm2: 62_600,
    capitalNameTr: 'Vilnius',
    capitalNameEn: 'Vilnius',
    capitalLatitude: 54.6872,
    capitalLongitude: 25.2797,
    neighborIsoCodes: ['LV', 'BY', 'PL', 'RU'],
    officialLanguagesTr: ['Litvanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "11 Mart 1990'da Sovyetler Birliği'nden ayrılan ilk cumhuriyet oldu (ilk bağımsızlık 16 Şubat 1918).",
  },
  {
    isoCode: 'NO',
    isoCodeAlpha3: 'NOR',
    nameTr: 'Norveç',
    nameEn: 'Norway',
    slugTr: 'norvec',
    slugEn: 'norway',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 5_610_870,
    populationYear: null,
    areaKm2: 364_270,
    capitalNameTr: 'Oslo',
    capitalNameEn: 'Oslo',
    capitalLatitude: 59.9139,
    capitalLongitude: 10.7522,
    neighborIsoCodes: ['SE', 'FI', 'RU'],
    officialLanguagesTr: ['Norveççe'],
    currencyNameTr: 'Norveç Kronu',
    currencyCode: 'NOK',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: "7 Haziran 1905'te İsveç ile birliğin feshiyle bağımsız oldu.",
    introTr:
      "Norveç, İskandinav Dağları'nın batı yamacı boyunca kuzeye doğru uzanan, dünyanın en " +
      'girintili çıkıntılı kıyı şeritlerinden birine sahip dar bir ülkedir. Buzul çağından kalma ' +
      'fiyortlar kıyı şeridini içeri doğru derinlemesine yarar ve ülkenin coğrafyasını tanımlayan ' +
      'temel unsuru oluşturur. Kuzeyde Rusya ve Finlandiya, doğuda ise İsveç ile kara sınırı ' +
      'paylaşır.',
    landformNoteTr:
      "Orta Norveç'teki Jotunheimen sırası, ülkenin en sarp arazisini barındırır; sıradaki " +
      "Galdhøpiggen 2.469 metreye yükselir — bu yükseklik yalnızca Norveç'te değil, tüm Kuzey " +
      "Avrupa'da aşılmamıştır. Aynı bölgedeki Jostedalsbreen, yaklaşık 460 km²'lik yüzölçümüyle " +
      'Avrupa anakarasının en büyük buzuludur. Batı kıyısında, dağların denizle buluştuğu hat ' +
      'boyunca sayısız fiyort açılır; bunların en uzunu ve en derini olan Sognefjord, 205 ' +
      "kilometre iç kesimlere uzanır ve 1.300 metreyi aşan noktalarıyla Avrupa'nın en derin " +
      'fiyordudur.',
    climateNoteTr:
      'Norveç, bulunduğu enleme göre beklenenden çok daha ılıman bir iklime sahiptir; bunun ' +
      "nedeni, kıyı boyunca kuzeye taşınan sıcak Golfstrim sularıdır. Kutup Dairesi'nin çok " +
      'üzerindeki limanlar bile bu etki sayesinde yıl boyunca donmaz. İç kesimlerde ve yüksek ' +
      'dağlarda deniz etkisi zayıflar, kışlar belirgin biçimde daha soğuk ve karlı geçer. En ' +
      'kuzeydeki bölgelerde yazın gece güneşi, kışın ise kutup gecesi yaşanır.',
    hydrographyNoteTr:
      "Norveç'in kıyı şeridi, anakara ve fiyortlarla birlikte yaklaşık 29.000 kilometre, binlerce " +
      "adayı da içine katan ölçümlerde ise 100.000 kilometreyi aşar — dünyanın Kanada'dan sonra " +
      'en uzun ikinci kıyı şeridi. Dağlık arazi nedeniyle ülkedeki nehirler genellikle kısa ve ' +
      'akışı hızlıdır; bu özellik, akarsuların hidroelektrik üretimi için yoğun biçimde ' +
      'kullanılmasını kolaylaştırır. Binlerce buzul gölü ve buzuldan beslenen akarsu, İskandinav ' +
      "Dağları'nın su ağını besler.",
  },
  {
    isoCode: 'SE',
    isoCodeAlpha3: 'SWE',
    nameTr: 'İsveç',
    nameEn: 'Sweden',
    slugTr: 'isvec',
    slugEn: 'sweden',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 10_596_620,
    populationYear: null,
    areaKm2: 407_270,
    capitalNameTr: 'Stokholm',
    capitalNameEn: 'Stockholm',
    capitalLatitude: 59.3293,
    capitalLongitude: 18.0686,
    neighborIsoCodes: ['NO', 'FI'],
    officialLanguagesTr: ['İsveççe'],
    currencyNameTr: 'İsveç Kronu',
    currencyCode: 'SEK',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr:
      "Modern devlet geleneksel olarak 6 Haziran 1523'e (Gustav Vasa'nın seçimi) dayanır; eski, kesintisiz bir devlettir.",
    introTr:
      'İsveç, kuzey-güney doğrultusunda yaklaşık 1.570 kilometre uzanan, Norveç sınırındaki ' +
      "İskandinav Dağları'ndan Baltık Denizi kıyısına doğru alçalan bir topografyaya sahiptir. " +
      'Ülkenin büyük bölümünü ormanlarla kaplı düzlükler ve binlerce göl oluşturur; kıyı şeridi ' +
      'ise Stockholm çevresinde yoğunlaşan geniş takımadalarla parçalanmıştır. Batısında Norveç, ' +
      'kuzeydoğusunda ise Finlandiya yer alır.',
    landformNoteTr:
      "Kuzeydeki Kebnekaise, İsveç'in en yüksek dağıdır; kuzey doruğu 2.097 metreye ulaşır. Bir " +
      'zamanlar daha yüksek olan buzullu güney doruk, son elli yılda belirgin biçimde erimiş ve ' +
      "artık kuzey doruğun gerisinde kalmıştır. İskandinav Dağları'nın doğusunda arazi kademeli " +
      "olarak alçalır ve orta ile güney İsveç'in büyük bölümünü kaplayan, göllerle noktalanmış " +
      "ormanlık platoya bağlanır. Vänern (5.650 km²), Avrupa'nın üçüncü büyük gölü olarak bu " +
      "platonun güneyinde yer alır; hemen doğusundaki Vättern ise İsveç'in ikinci büyük gölüdür.",
    climateNoteTr:
      "İsveç'in kuzey yarısı, Kutup Dairesi'nin de içinden geçtiği subarktik bir iklime sahiptir; " +
      'kışlar uzun ve karanlık, yazlar kısa geçer, yaz aylarında güneş ufkun altına inmez. Güney ' +
      "İsveç'te iklim ılıman kıta karakterine yaklaşır, dört mevsim daha belirgin biçimde " +
      "ayrışır. İskandinav Dağları, Atlas Okyanusu'ndan gelen nemli hava kütlelerini büyük ölçüde " +
      'batı yamaçlarında tutar; bu nedenle İsveç, dağların doğusunda kalan konumu itibarıyla ' +
      'nispeten kurak bir iklime sahiptir.',
    hydrographyNoteTr:
      'İsveç topraklarında 95 binin üzerinde göl bulunur; bunların en büyüğü olan Vänern, ' +
      "Rusya'daki Ladoga ve Onega göllerinin ardından Avrupa'nın üçüncü büyük gölüdür. Çoğu " +
      "nehir, İskandinav Dağları'ndan doğup güneydoğu yönünde akarak Botni Körfezi ile Baltık " +
      "Denizi'ne dökülür. Stockholm kıyısındaki takımada, 24 bini aşkın ada, adacık ve kayalıktan " +
      "oluşur ve İsveç'in Baltık kıyı şeridinin karakteristik bir parçasıdır.",
  },
  {
    isoCode: 'GB',
    isoCodeAlpha3: 'GBR',
    nameTr: 'Birleşik Krallık',
    nameEn: 'United Kingdom',
    slugTr: 'birlesik-krallik',
    slugEn: 'united-kingdom',
    continent: Continent.Europe,
    unSubregionTr: 'Kuzey Avrupa',
    population: 69_487_000,
    populationYear: null,
    areaKm2: 241_930,
    capitalNameTr: 'Londra',
    capitalNameEn: 'London',
    capitalLatitude: 51.5074,
    capitalLongitude: -0.1278,
    neighborIsoCodes: ['IE'],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Sterlin',
    currencyCode: 'GBP',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: null,
    introTr:
      'Büyük Britanya adasının tamamını ve İrlanda adasının kuzeydoğu köşesini kaplayan ' +
      "Birleşik Krallık, kıtasal Avrupa'yla kara sınırı olmayan bir ada ülkesidir; egemen " +
      "devlet olarak tek kara komşusu İrlanda'dır. (Birleşik Krallık'a bağlı ama ayrı bir " +
      'denizaşırı toprak olan Cebelitarık, İspanya ile kendi kara sınırına sahiptir — bu, ' +
      "Birleşik Krallık'ın kendisinin bir kara komşusu sayılmaz, çünkü Cebelitarık'ın kendi " +
      "anayasası ve yönetimi vardır, Westminster'da temsil edilmez.)",
    landformNoteTr:
      "İskoçya, Birleşik Krallık'ın en dağlık parçasıdır; Highland Sınır Fayı, ülkeyi " +
      "kuzeybatıdaki dağlık Highlands ile güneydoğudaki Lowlands'e ayırır. Highlands'teki Ben " +
      "Nevis, 1.345 metreyle Birleşik Krallık'ın en yüksek noktasıdır." +
      '\n\n' +
      'İngiltere, büyük ölçüde alçak arazilerden oluşur; dağlık kesimler yalnızca kuzeybatıda, ' +
      "Pennine Dağları ile Göller Bölgesi'nde görülür — bu bölgedeki Scafell Pike, 978 metreyle " +
      "İngiltere'nin en yüksek noktasıdır. Galler'de ise Snowdonia'daki Snowdon (Yr Wyddfa), " +
      '1.085 metreyle bölgenin en yüksek zirvesidir.',
    climateNoteTr:
      "Batı kesimler — İskoçya'nın batı Highlands'i, Galler ve İngiltere'nin batısı — Atlas " +
      "Okyanusu'na en yakın, en yağışlı ve en rüzgarlı bölgelerdir; İskoçya'nın batı " +
      "Highlands'inde yıllık yağış 3.000 milimetreyi aşarken, doğu kıyısında 800 milimetrenin " +
      'altına iner. Kuzey bölgeler genelde daha serin ve daha yağışlıyken, güney bölgeler daha ' +
      'ılık ve daha kuru geçer. Tüm ülke, kışları göreceli ılık, yazları serin geçen nemli ' +
      'ılıman bir deniz ikliminin etkisi altındadır.',
    hydrographyNoteTr:
      "Birleşik Krallık'ın en uzun nehri, Galler'deki Cambrian Dağları'nda doğup Bristol " +
      "Körfezi'ne dökülen 354 kilometrelik Severn'dir. Thames, güney İngiltere'yi kat ederek " +
      "Londra'nın içinden geçer, uzunluğu 346 kilometredir." +
      '\n\n' +
      "İskoçya'daki en büyük göl olan Loch Lomond'un yanı sıra, İngiltere'nin en büyük gölü " +
      "Windermere de Göller Bölgesi'nin başlıca su kütleleridir.",
  },
  {
    isoCode: 'AT',
    isoCodeAlpha3: 'AUT',
    nameTr: 'Avusturya',
    nameEn: 'Austria',
    slugTr: 'avusturya',
    slugEn: 'austria',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 9_178_482,
    populationYear: null,
    areaKm2: 82_520,
    capitalNameTr: 'Viyana',
    capitalNameEn: 'Vienna',
    capitalLatitude: 48.2082,
    capitalLongitude: 16.3738,
    neighborIsoCodes: ['DE', 'CZ', 'SK', 'HU', 'SI', 'IT', 'CH', 'LI'],
    officialLanguagesTr: ['Almanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    // Çok-adaylı bağımsızlık tarihi → ülkenin KENDİ resmî millî günü esas alındı, diğer
    //   tarihler bağlam olarak dokundu (DEC 2026-07-13 resolution rule, Yunanistan emsali).
    independenceNoteTr:
      "Avusturya, kalıcı tarafsızlığını anayasal kanunla ilan ettiği 26 Ekim 1955'i resmî " +
      'Millî Gün (Nationalfeiertag) olarak kutlar; modern devletin diğer dönüm noktaları ' +
      "arasında 12 Kasım 1918 (I. Cumhuriyet'in ilanı) ve 15 Mayıs 1955 Avusturya Devlet " +
      'Antlaşması (işgal rejiminin sona ermesi) yer alır.',
    introTr:
      "Avusturya toprağının yaklaşık %60'ını Doğu Alpleri kaplar; ülkenin kuzey ve doğu kesimleri " +
      "ise Tuna Nehri vadisi ve Panonya Ovası'na açılan alçak arazilerden oluşur. Kıyısı olmayan " +
      'ülke, Almanya, Çekya, Slovakya, Macaristan, Slovenya, İtalya, İsviçre ve Lihtenştayn ile ' +
      "sınır komşusudur. Viyana, Tuna'nın Alpler'den ovaya çıktığı noktada, ülkenin kuzeydoğu " +
      'ucunda kuruludur.',
    landformNoteTr:
      'Ülke sınırları içinde 3.000 metrenin üzerinde yüzlerce zirve yükselir; bunların en ' +
      "yükseği, Hohe Tauern sırasındaki Grossglockner'dir — 3.798 metrelik bu dağ, aynı zamanda " +
      "ünlü Grossglockner Yüksek Alp Yolu'nun geçtiği güzergahtır. Kuzeyde, Tuna vadisi boyunca " +
      "uzanan şerit ile Tuna'nın kuzeyinde kalan, jeolojik olarak Alp sistemine değil çok daha " +
      "eski Bohemya Masifi'ne ait Waldviertel ve Mühlviertel platoları, ülkenin nispeten alçak " +
      "kesimlerini oluşturur. Doğuda, Viyana Havzası'nın ötesinde arazi Panonya Ovası'na doğru " +
      "alçalır — Avusturya'nın Alpler dışındaki tek geniş düzlük burasıdır.",
    climateNoteTr:
      "Avusturya'da Atlantik ve kıta iklimleri arasında bir geçiş yaşanır. Batıda yağış daha bol " +
      've deniz etkisi daha belirgindir; doğuya gidildikçe yazlar daha sıcak, kışlar daha kurak ' +
      'hale gelir. Alp kesimlerinde rakımla birlikte sıcaklık hızla düşer, yüksek vadilerde kar ' +
      "örtüsü aylarca yerde kalır. Viyana çevresindeki düzlükler, Panonya Ovası'nın ılıman-kıta " +
      'karakterinden etkilenir.',
    hydrographyNoteTr:
      'Tuna Nehri, Avusturya topraklarını batıdan doğuya yaklaşık 357 kilometre boyunca kat eder ' +
      "ve Viyana'dan geçerek Slovakya sınırına ulaşır. İnn, Enns ve Traun gibi büyük kolları, " +
      "Alpler'deki buzul ve kar erimesinden beslenerek Tuna'ya katılır. Ülke yüzölçümünün " +
      "neredeyse tamamı Tuna havzası içinde kalır — Avusturya'nın kıyısı olmasa da su ağı " +
      "doğrudan Karadeniz'e bağlıdır.",
  },
  {
    isoCode: 'DE',
    isoCodeAlpha3: 'DEU',
    nameTr: 'Almanya',
    nameEn: 'Germany',
    slugTr: 'almanya',
    slugEn: 'germany',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 83_491_249,
    populationYear: null,
    areaKm2: 349_430,
    capitalNameTr: 'Berlin',
    capitalNameEn: 'Berlin',
    capitalLatitude: 52.52,
    capitalLongitude: 13.405,
    neighborIsoCodes: ['DK', 'PL', 'CZ', 'AT', 'CH', 'FR', 'LU', 'BE', 'NL'],
    officialLanguagesTr: ['Almanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    independenceNoteTr:
      "Modern Federal Cumhuriyet 1949'da kuruldu; 3 Ekim 1990'da Doğu ve Batı Almanya birleşti (bugünkü resmî millî gün).",
    introTr:
      "Orta Avrupa'da yer alan Almanya, kuzeyde Kuzey Denizi ve Baltık Denizi kıyısından " +
      'güneyde Alp dağlarına kadar üç farklı yer şekli kuşağını bir arada barındıran bir ' +
      'ülkedir. Dokuz ülkeyle kara sınırı paylaşır — Danimarka, Polonya, Çekya, Avusturya, ' +
      'İsviçre, Fransa, Lüksemburg, Belçika ve Hollanda.',
    landformNoteTr:
      "Almanya'nın kuzey üçte biri, buzul çağından kalma kumlu topraklar ve sığ göllerle kaplı, " +
      'çoğunlukla 100 metrenin altında kalan düz bir kıyı ovasıdır — Kuzey Almanya Ovası. Elbe, ' +
      'Ems, Weser ve Oder nehirleri bu ovayı kuzeye doğru kat eder; kuzeydoğuda Mecklenburg ' +
      'Göller Bölgesi, aynı buzul kökenli yüzlerce gölü barındırır.' +
      '\n\n' +
      'Ülkenin ortası, Eifel, Taunus, Vogelsberg, Rhön ve Thüringen Ormanı gibi alçak dağlık ' +
      "kütlelerden oluşan Orta Almanya Yaylaları'yla kaplıdır; bu bölge 1.500 metreyi nadiren " +
      'aşar ama geniş bir alana yayılır. Güneyde, Bavyera sınırında yükselen Alp dağları, ' +
      "ülkenin en yüksek noktası olan 2.962 metrelik Zugspitze'yi barındırır.",
    climateNoteTr:
      'Kuzey Denizi ve Baltık Denizi kıyısında ılıman, yağışlı bir deniz iklimi egemendir; ' +
      'yaz-kış sıcaklık farkı sınırlı kalır. Orta ve doğu kesimlerde bu deniz etkisi zayıflar, ' +
      'karasal bir karaktere geçilir — kışlar daha soğuk, yazlar daha sıcak geçer. Güneydeki ' +
      'Alp eteklerinde ise yükseklik belirleyici olur, kışlar karlı ve sert geçer, yaz-kış ' +
      'sıcaklık farkı en belirgin haline ulaşır.',
    hydrographyNoteTr:
      "Almanya'nın en uzun akarsuyu, ülke sınırları içinde 865 kilometre uzunluğundaki Ren'dir; " +
      "İsviçre'de doğar, ülkeyi güneyden kuzeye kat ederek Hollanda üzerinden Kuzey Denizi'ne " +
      "ulaşır ve tarih boyunca ülkenin başlıca ticaret yoludur. Elbe, Çekya'daki dağlardan " +
      "doğup Hamburg üzerinden Kuzey Denizi'ne dökülür; Almanya'dan geçen bölümü yaklaşık 727 " +
      "kilometredir. Tuna Nehri, Karaorman'da doğup ülkeden güneydoğuya akarak dokuz ülkeden " +
      'geçen uzun yolculuğuna başlar.' +
      '\n\n' +
      "Ülke genelinde 3.000'i aşkın göl bulunur; sınırları tamamen Almanya içinde kalan en " +
      "büyüğü, kuzeydoğudaki buzul kökenli Müritz Gölü'dür. Almanya'nın mutlak anlamda en büyük " +
      "gölü ise güneydeki Bodensee'dir (Constance Gölü) — ama bu göl İsviçre ve Avusturya ile " +
      'paylaşıldığı için "tamamen Almanya\'da" sayılmaz, yüzölçümü Müritz\'in yaklaşık 4,6 ' +
      'katıdır.',
  },
  {
    isoCode: 'BE',
    isoCodeAlpha3: 'BEL',
    nameTr: 'Belçika',
    nameEn: 'Belgium',
    slugTr: 'belcika',
    slugEn: 'belgium',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 11_941_781,
    populationYear: null,
    areaKm2: 30_494,
    capitalNameTr: 'Brüksel',
    capitalNameEn: 'Brussels',
    capitalLatitude: 50.8503,
    capitalLongitude: 4.3517,
    neighborIsoCodes: ['FR', 'LU', 'DE', 'NL'],
    officialLanguagesTr: ['Felemenkçe (Flamanca)', 'Fransızca', 'Almanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Federal anayasal monarşi (parlamenter)',
    independenceNoteTr: "4 Ekim 1830'da Hollanda'dan bağımsız oldu.",
    introTr:
      'Belçika toprakları kuzeyden güneye üç farklı doğal bölgeye ayrılır: kuzeybatıdaki kıyı ' +
      'ovası, ülkenin ortasını kaplayan alçak plato ve güneydoğudaki ormanlık Ardenler yaylası. ' +
      'Kıyı şeridindeki dar kesim dışında ülkenin büyük bölümü 200 metrenin altında kalır. Kara ' +
      'sınırları dört komşuya açılır: güneyde Fransa, güneydoğuda Lüksemburg, doğuda Almanya, ' +
      'kuzeyde ise Hollanda.',
    landformNoteTr:
      'Kıyı boyunca dar bir kumul şeridi uzanır; hemen gerisinde, geçmişte bataklık olan ve bugün ' +
      'tarım amacıyla kullanılan düz polder arazileri yer alır. Bu düzlük, güneye doğru yavaşça ' +
      'yükselerek ortadaki verimli, dalgalı platoya bağlanır. Sambre ve Maas nehirlerinin çizdiği ' +
      "vadi, ülkeyi kuzeydeki düzlüklerden güneydeki Ardenler'den ayıran belirgin bir hat " +
      'oluşturur.' +
      '\n\n' +
      'Ardenler, Devon ve Kambriyen dönemine ait eski kayaçlardan oluşan, sık ormanlarla kaplı ' +
      'bir plato yaylasıdır. Bu yaylanın ve ülkenin en yüksek noktası olan 694 metrelik Signal de ' +
      'Botrange, Hautes Fagnes adı verilen geniş bir turbalık alanda yer alır.',
    climateNoteTr:
      "Belçika'da ılıman deniz iklimi görülür; kıyı ve orta kesimlerde kışlar yumuşak, yazlar " +
      "serin geçer. Ardenler'in yüksek platosunda rakımın etkisiyle sıcaklıklar birkaç derece " +
      'daha düşük seyreder, kar örtüsü kıyıya göre daha uzun sürer. Ardenler aynı zamanda ülkenin ' +
      'en yağışlı bölgesidir.',
    hydrographyNoteTr:
      "Fransa'dan gelen Schelde (Escaut) Nehri, ülkenin kuzeybatısından geçerek Antwerp limanını " +
      "besler ve Hollanda topraklarında Kuzey Denizi'ne ulaşır. Maas Nehri ise güneydoğudan girip " +
      "Ardenler'i dar ve derin bir vadi boyunca kat eder; Namur yakınlarında Sambre'ı alarak " +
      "Liège üzerinden kuzeye yönelir. Antwerp Limanı, Schelde'nin gelgit etkisindeki geniş " +
      "ağzında konumlanmasıyla Avrupa'nın en büyük limanlarından biri haline gelmiştir.",
  },
  {
    isoCode: 'FR',
    isoCodeAlpha3: 'FRA',
    nameTr: 'Fransa',
    nameEn: 'France',
    slugTr: 'fransa',
    slugEn: 'france',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 68_720_337,
    populationYear: null,
    areaKm2: 538_950,
    capitalNameTr: 'Paris',
    capitalNameEn: 'Paris',
    capitalLatitude: 48.8566,
    capitalLongitude: 2.3522,
    neighborIsoCodes: ['BE', 'LU', 'DE', 'CH', 'IT', 'MC', 'ES', 'AD', 'BR', 'SR'],
    officialLanguagesTr: ['Fransızca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Yarı-başkanlık cumhuriyeti (üniter)',
    independenceNoteTr: null,
    introTr:
      "Fransa, Avrupa'daki sekiz kara komşusunun yanı sıra, Güney Amerika'daki Fransız Guyanası " +
      "toprağı üzerinden Brezilya ve Surinam'la da kara sınırı paylaşır — bir Avrupa ülkesinin " +
      "Güney Amerika'da kara komşusu olması, kıtalar arası nadir bir örnektir. Anakara Fransa, " +
      "La Manş, Atlas Okyanusu ve Akdeniz'e kıyısı olan, altıgen biçimiyle tanınan bir ülkedir.",
    landformNoteTr:
      "Fransa'nın güneydoğu sınırını Alpler, güneybatı sınırını ise Pireneler çizer. " +
      "Alpler'deki Mont Blanc, 4.810 metreyle hem Fransa'nın hem Avrupa'nın en yüksek " +
      "noktasıdır ve İtalya sınırında yükselir. Pireneler, İspanya'yla arada yaklaşık 490 " +
      'kilometre uzunluğunda doğal bir set oluşturur. Ülkenin güney-orta kesiminde, eski ve ' +
      'aşınmış bir volkanik plato olan Merkez Masifi uzanır; en yüksek noktası 1.886 metrelik ' +
      "Puy de Sancy'dir, günümüzden yaklaşık 6.000 yıl önce sönmüş Chaîne des Puys volkanik " +
      'zinciri bu platonun en genç jeolojik izidir.' +
      '\n\n' +
      'Ülkenin kuzeyini geniş ve sığ bir çöküntü alanı olan Paris Havzası, güneybatısını ise ' +
      'Akitanya Havzası kaplar; bu iki alçak ova, Fransa topraklarının büyük bölümünü ' +
      'oluşturur.',
    climateNoteTr:
      'Batı kıyısında (Bretanya, Normandiya, Atlantik Loire) ılıman, yıl boyu yağışlı bir ' +
      'okyanus iklimi egemendir, sıcaklık farkları sınırlıdır. Ülkenin ortasında ve doğusunda ' +
      '(Şampanya, Burgonya, Alsace) karasal bir iklim görülür, kışlar soğuk yazlar sıcak geçer. ' +
      "Güneyde, Provence, Korsika ve Côte d'Azur'da sıcak-kurak yaz ve ılık-yağışlı kışın " +
      "görüldüğü Akdeniz iklimi hakimdir. Alpler ve Pireneler'in yüksek kesimlerinde ise dağ " +
      'iklimi egemendir, 900 metrenin üzerinde kar örtüsü aralık-nisan arasında kalıcıdır.',
    hydrographyNoteTr:
      "Fransa'nın en uzun nehri, Merkez Masifi'nde doğup batıya akarak Atlas Okyanusu'na " +
      "dökülen 1.013 kilometrelik Loire'dır. Sen Nehri, kuzeybatı yönünde Paris'in içinden " +
      "geçerek La Manş'a ulaşır, uzunluğu 776 kilometredir. Rhône, İsviçre'de doğar ve Fransa " +
      "içindeki 545 kilometrelik bölümüyle güneye, Akdeniz'e akar. Garonne, ülkenin " +
      "güneybatısındaki başlıca nehirdir ve Bordeaux üzerinden Atlas Okyanusu'na ulaşır.",
  },
  {
    isoCode: 'LI',
    isoCodeAlpha3: 'LIE',
    nameTr: 'Lihtenştayn',
    nameEn: 'Liechtenstein',
    slugTr: 'lihtenstayn',
    slugEn: 'liechtenstein',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 41_024,
    populationYear: null,
    areaKm2: 160,
    capitalNameTr: 'Vaduz',
    capitalNameEn: 'Vaduz',
    capitalLatitude: 47.141,
    capitalLongitude: 9.5209,
    neighborIsoCodes: ['CH', 'AT'],
    officialLanguagesTr: ['Almanca'],
    currencyNameTr: 'İsviçre Frangı',
    currencyCode: 'CHF',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: "23 Ocak 1719'da prenslik kuruldu; tam egemenlik 1806.",
  },
  {
    isoCode: 'LU',
    isoCodeAlpha3: 'LUX',
    nameTr: 'Lüksemburg',
    nameEn: 'Luxembourg',
    slugTr: 'luksemburg',
    slugEn: 'luxembourg',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 686_970,
    populationYear: null,
    areaKm2: 2_574,
    capitalNameTr: 'Lüksemburg',
    capitalNameEn: 'Luxembourg',
    capitalLatitude: 49.6116,
    capitalLongitude: 6.1319,
    neighborIsoCodes: ['BE', 'FR', 'DE'],
    officialLanguagesTr: ['Lüksemburgca', 'Fransızca', 'Almanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Anayasal monarşi (parlamenter, Büyük Dükalık)',
    independenceNoteTr: "1839 Londra Antlaşması ile bağımsızlığı tanındı (1867'de pekiştirildi).",
  },
  {
    isoCode: 'MC',
    isoCodeAlpha3: 'MCO',
    nameTr: 'Monako',
    nameEn: 'Monaco',
    slugTr: 'monako',
    slugEn: 'monaco',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 38_341,
    populationYear: null,
    areaKm2: 2,
    capitalNameTr: 'Monako',
    capitalNameEn: 'Monaco',
    capitalLatitude: 43.7384,
    capitalLongitude: 7.4246,
    neighborIsoCodes: ['FR'],
    officialLanguagesTr: ['Fransızca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Anayasal monarşi (parlamenter prenslik)',
    independenceNoteTr: null,
  },
  {
    isoCode: 'NL',
    isoCodeAlpha3: 'NLD',
    nameTr: 'Hollanda',
    nameEn: 'Netherlands',
    slugTr: 'hollanda',
    slugEn: 'netherlands',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 18_087_633,
    populationYear: null,
    areaKm2: 33_670,
    capitalNameTr: 'Amsterdam',
    capitalNameEn: 'Amsterdam',
    capitalLatitude: 52.3676,
    capitalLongitude: 4.9041,
    neighborIsoCodes: ['DE', 'BE'],
    officialLanguagesTr: ['Felemenkçe (Hollandaca)'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: null,
    introTr:
      "Hollanda, Ren, Maas ve Schelde nehirlerinin Kuzey Denizi'ne döküldüğü büyük bir deltanın " +
      'üzerinde kuruludur. Ülke topraklarının yaklaşık dörtte biri deniz seviyesinin altındadır; ' +
      'bu alanların büyük bölümü, yüzyıllar boyunca bentlerle çevrilip pompalarla kurutulan eski ' +
      'göl ve bataklık yataklarından oluşan polderlerdir. Almanya ve Belçika ile kara sınırı ' +
      'paylaşır.',
    landformNoteTr:
      'Kıyı şeridi boyunca uzanan kumullar, denizin doğrudan içeri girmesini engelleyen doğal bir ' +
      'bariyer oluşturur; bu kumulların gerisinde kalan alanlar, bentlerle çevrilip pompalarla ' +
      'kurutulan polderlerdir. Ülkenin en alçak noktası, Rotterdam yakınlarındaki ' +
      "Zuidplaspolder'de deniz seviyesinin yaklaşık 6,76 metre altındadır. En yüksek nokta ise " +
      "ülkenin güneydoğu ucunda, Almanya ve Belçika ile üçlü sınırın kesiştiği Vaalserberg'de 322 " +
      'metreye ulaşır — ülkenin geri kalanından topografik olarak tamamen kopuk, tek gerçek ' +
      'tepelik nokta.' +
      '\n\n' +
      "1953'teki büyük Kuzey Denizi taşkınının ardından inşa edilen Delta Projesi, güneybatıdaki " +
      'Ren-Maas-Schelde deltasını bir dizi dev bariyer ve setle korumaya yöneliktir; dünyanın en ' +
      'kapsamlı su mühendisliği çalışmalarından biri sayılır.',
    climateNoteTr:
      "Hollanda'da ılıman deniz iklimi egemendir; Kuzey Denizi'nin etkisiyle kışlar hafif, yazlar " +
      'serin geçer. Yağış yıl boyunca düzenli dağılır, gökyüzü sık sık bulutludur. Ülkenin düz ' +
      'topografyası, batıdan esen rüzgarların iç kesimlere kadar güçlü biçimde ulaşmasına imkân ' +
      'tanır.',
    hydrographyNoteTr:
      'Ren, Maas ve Schelde nehirleri Hollanda topraklarında birbirine yakın ağızlardan Kuzey ' +
      "Denizi'ne dökülür; bu üçlü delta, ülkenin güneybatısını oluşturan Zeeland ve Güney " +
      "Hollanda bölgelerinin fiziki temelidir. Kuzeyde, 1932'de tamamlanan Afsluitdijk bendi eski " +
      'Zuiderzee körfezini denizden ayırarak IJsselmeer adlı geniş bir tatlı su gölüne ' +
      'dönüştürdü. Ülke genelindeki binlerce kilometrelik kanal ağı, hem taşımacılık hem de su ' +
      'seviyesi kontrolü için kullanılır.',
  },
  {
    isoCode: 'CH',
    isoCodeAlpha3: 'CHE',
    nameTr: 'İsviçre',
    nameEn: 'Switzerland',
    slugTr: 'isvicre',
    slugEn: 'switzerland',
    continent: Continent.Europe,
    unSubregionTr: 'Batı Avrupa',
    population: 9_092_436,
    populationYear: null,
    areaKm2: 39_510,
    capitalNameTr: 'Bern',
    capitalNameEn: 'Bern',
    capitalLatitude: 46.948,
    capitalLongitude: 7.4474,
    neighborIsoCodes: ['DE', 'FR', 'IT', 'AT', 'LI'],
    officialLanguagesTr: ['Almanca', 'Fransızca', 'İtalyanca', 'Romanşça'],
    currencyNameTr: 'İsviçre Frangı',
    currencyCode: 'CHF',
    governmentFormTr: 'Federal cumhuriyet (direktoryal)',
    independenceNoteTr:
      'Konfederasyonun geleneksel kuruluşu 1 Ağustos 1291 (millî gün); uluslararası tanınma 1648 Vestfalya Barışı.',
    introTr:
      'İsviçre toprakları kuzeybatıdan güneydoğuya üç kuşağa ayrılır: Jura Dağları, ortadaki ' +
      "İsviçre Platosu (Mittelland) ve ülke yüzölçümünün yaklaşık %60'ını kaplayan Alpler. " +
      "Nüfusun büyük bölümü, iki dağ kuşağı arasında kalan ve göllerle noktalanan Mittelland'da " +
      'yaşar. Almanya, Fransa, İtalya, Avusturya ve Lihtenştayn ile kara sınırı paylaşan ülke, ' +
      'kıyısı olmayan bir iç Avrupa devletidir.',
    landformNoteTr:
      "Güneyde yükselen Alpler, İsviçre'nin en yüksek ve en sarp arazisini oluşturur; İtalya " +
      'sınırındaki Monte Rosa kütlesinin bir parçası olan Dufourspitze, 4.634 metreyle ülkenin en ' +
      'yüksek noktasıdır. Kuzeybatıda, Fransa sınırı boyunca uzanan Jura Dağları daha alçak ve ' +
      'yumuşak hatlı kireçtaşı sıradağlarından oluşur. İkisinin arasında kalan Mittelland, göller ' +
      've tepelerle kesintiye uğrayan verimli bir platodur; Zürih, Bern ve Cenevre gibi büyük ' +
      'şehirlerin çoğu burada yer alır.',
    climateNoteTr:
      "İsviçre'de iklim büyük ölçüde rakıma göre değişir: Mittelland'da ılıman kıta iklimi, " +
      'yüksek Alp vadilerinde ise sert kış koşulları görülür. Güneyden esen sıcak ve kuru föhn ' +
      'rüzgarı, kışın Alp vadilerinde ani sıcaklık artışlarına ve hızlı kar erimesine yol ' +
      "açabilir. Güney kantonlarında, İtalya'ya yakınlığın etkisiyle daha ılık kışlar yaşanır.",
    hydrographyNoteTr:
      'İsviçre, Ren, Ron, Ticino ve İnn nehirlerinin kaynağını Alp buzullarından alması nedeniyle ' +
      'Avrupa\'nın "su kulesi" olarak anılır; bu dört nehir sırasıyla Kuzey Denizi, Akdeniz, ' +
      "Adriyatik ve Karadeniz havzalarına ulaşır. Ren'in kaynağı, Graubünden kantonundaki Toma " +
      "Gölü'dür. Cenevre, Konstanz ve Lugano gölleri gibi büyük göllerin çoğu komşu ülkelerle " +
      'paylaşılır; hem enerji üretiminde hem de iç su taşımacılığında önemli rol oynar.',
  },
  {
    isoCode: 'AL',
    isoCodeAlpha3: 'ALB',
    nameTr: 'Arnavutluk',
    nameEn: 'Albania',
    slugTr: 'arnavutluk',
    slugEn: 'albania',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 2_349_580,
    populationYear: null,
    areaKm2: 27_400,
    capitalNameTr: 'Tiran',
    capitalNameEn: 'Tirana',
    capitalLatitude: 41.3275,
    capitalLongitude: 19.8187,
    neighborIsoCodes: ['ME', 'XK', 'MK', 'GR'],
    officialLanguagesTr: ['Arnavutça'],
    currencyNameTr: 'Arnavutluk Leki',
    currencyCode: 'ALL',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "28 Kasım 1912'de Osmanlı'dan bağımsız oldu.",
    introTr:
      'Adriyatik ve İyon denizlerine kıyısı olan Arnavutluk, topraklarının büyük bölümü dağlık ' +
      'bir Balkan ülkesidir. Kuzeyde Karadağ ve Kosova, doğuda Kuzey Makedonya, güneyde ' +
      'Yunanistan ile komşudur.',
    landformNoteTr:
      'Ülkenin kuzeyini, sarp ve derin vadilerle yarılmış Arnavut Alpleri (Prokletije) kaplar. ' +
      "Doğuda, Kuzey Makedonya sınırında yükselen 2.764 metrelik Korab, Arnavutluk'un en yüksek " +
      "noktasıdır — Avrupa'da bir zirvenin aynı anda iki ülkenin de en yüksek noktası olduğu " +
      "yalnızca iki örnekten biridir, diğeri Mont Blanc'tır." +
      '\n\n' +
      'Adriyatik kıyısı boyunca, kıyı çizgisinden içeri doğru yaklaşık 50 kilometreye kadar ' +
      'uzanan alçak ve verimli bir kıyı ovası yer alır; bu ova ülkenin batı kesiminin tarım ' +
      "alanlarını oluşturur. İyon kıyısı ise Adriyatik'in aksine sarp kayalıklar ve derin " +
      'koylarla şekillenmiş dik bir kıyı karakteri taşır.',
    climateNoteTr:
      'Kıyı ovaları ve İyon kıyısı, sıcak-kurak yaz ile ılık-yağışlı kışın görüldüğü Akdeniz ' +
      'iklimi altındadır. Doğuya, Arnavut Alpleri ve iç dağlık kesimlere doğru gidildikçe iklim ' +
      'karasallaşır; kışlar daha soğuk ve kar yağışlı, yaz-kış sıcaklık farkı daha belirgin ' +
      'hale gelir.',
    hydrographyNoteTr:
      "Ülkenin en uzun akarsuyu, kısmen Kosova'da doğup Arnavutluk topraklarından geçen " +
      "yaklaşık 280 kilometrelik Drin Nehri'dir. Seman, Shkumbin ve Vjosë nehirleri, batı " +
      'ovalarını sulayan diğer önemli akarsulardır.' +
      '\n\n' +
      "Arnavutluk'un üç büyük gölü sınır ötesi karakter taşır: Karadağ ile paylaşılan İşkodra " +
      'Gölü, Kuzey Makedonya ile paylaşılan Ohrid Gölü ve yine Kuzey Makedonya ile paylaşılan ' +
      'Prespa Gölü.',
  },
  {
    isoCode: 'AD',
    isoCodeAlpha3: 'AND',
    nameTr: 'Andorra',
    nameEn: 'Andorra',
    slugTr: 'andorra',
    slugEn: 'andorra',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 82_904,
    populationYear: null,
    areaKm2: 470,
    capitalNameTr: 'Andorra la Vella',
    capitalNameEn: 'Andorra la Vella',
    capitalLatitude: 42.5063,
    capitalLongitude: 1.5218,
    neighborIsoCodes: ['FR', 'ES'],
    officialLanguagesTr: ['Katalanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter eş-prenslik',
    independenceNoteTr: null,
  },
  {
    isoCode: 'BA',
    isoCodeAlpha3: 'BIH',
    nameTr: 'Bosna-Hersek',
    nameEn: 'Bosnia and Herzegovina',
    slugTr: 'bosna-hersek',
    slugEn: 'bosnia-and-herzegovina',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 3_140_095,
    populationYear: null,
    areaKm2: 51_200,
    capitalNameTr: 'Saraybosna',
    capitalNameEn: 'Sarajevo',
    capitalLatitude: 43.8563,
    capitalLongitude: 18.4131,
    neighborIsoCodes: ['HR', 'RS', 'ME'],
    officialLanguagesTr: ['Boşnakça', 'Hırvatça', 'Sırpça'],
    currencyNameTr: 'Konvertibl Marka',
    currencyCode: 'BAM',
    governmentFormTr: 'Federal parlamenter cumhuriyet',
    independenceNoteTr: "3 Mart 1992'de Yugoslavya'dan bağımsız oldu.",
    introTr:
      "Topraklarının üçte ikisi dağlık ve tepelik olan Bosna-Hersek, Adriyatik'e yalnızca Neum " +
      'kasabası çevresindeki dar bir şeritten kıyısı bulunan, neredeyse denizsiz sayılabilecek ' +
      'bir Balkan ülkesidir. Kuzeyde ve batıda Hırvatistan, doğuda Sırbistan, güneydoğuda ' +
      'Karadağ ile komşudur.',
    landformNoteTr:
      "Ülke topraklarının büyük bölümünü Dinar Alpleri'nin dağlık ve karstik arazisi kaplar; " +
      'Karadağ sınırındaki 2.386 metrelik Maglić, ülkenin en yüksek noktasıdır. Kuzeyde, Sava ' +
      "Nehri vadisi boyunca, doğudan batıya uzanan tepelik ama verimli Pannon Ovası'nın bir " +
      'kesimi yer alır.' +
      '\n\n' +
      "Ülkenin Adriyatik'e açılan tek noktası, Hersek bölgesindeki Neum kasabası çevresinde " +
      'yaklaşık 20 kilometrelik bir kıyı şerididir; bu dar şerit, Hırvatistan yarımadalarıyla ' +
      "çevrilidir ve Hırvatistan'ın kendi kıyı çizgisini ikiye böler.",
    climateNoteTr:
      'Ülkenin orta ve kuzey kesimleri, yükseklik nedeniyle soğuk kışlı ve serin yazlı bir ' +
      "karasal-dağlık iklime sahiptir. Neum çevresindeki güney şeridinde ise Adriyatik'in " +
      'etkisiyle çok daha ılıman bir Akdeniz iklimi görülür.',
    hydrographyNoteTr:
      'Ülkenin başlıca nehirleri Neretva, Sava, Vrbas, Bosna ve Sırbistan ile doğal sınır ' +
      "oluşturan Drina'dır. Bunlar arasında yalnızca Neretva güneye, Adriyatik'e doğru akar — " +
      'Hersek bölgesinin ana nehri olan Neretva, bu yönüyle ülkenin diğer büyük nehirlerinden ' +
      'ayrılır.',
  },
  {
    isoCode: 'HR',
    isoCodeAlpha3: 'HRV',
    nameTr: 'Hırvatistan',
    nameEn: 'Croatia',
    slugTr: 'hirvatistan',
    slugEn: 'croatia',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 3_876_200,
    populationYear: null,
    areaKm2: 55_960,
    capitalNameTr: 'Zagreb',
    capitalNameEn: 'Zagreb',
    capitalLatitude: 45.815,
    capitalLongitude: 15.9819,
    neighborIsoCodes: ['SI', 'HU', 'RS', 'BA', 'ME'],
    officialLanguagesTr: ['Hırvatça'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "25 Haziran 1991'de Yugoslavya'dan bağımsızlığını ilan etti.",
  },
  {
    isoCode: 'IT',
    isoCodeAlpha3: 'ITA',
    nameTr: 'İtalya',
    nameEn: 'Italy',
    slugTr: 'italya',
    slugEn: 'italy',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 58_915_656,
    populationYear: null,
    areaKm2: 295_720,
    capitalNameTr: 'Roma',
    capitalNameEn: 'Rome',
    capitalLatitude: 41.9028,
    capitalLongitude: 12.4964,
    neighborIsoCodes: ['FR', 'CH', 'AT', 'SI', 'SM', 'VA'],
    officialLanguagesTr: ['İtalyanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "İtalyan birleşmesi 17 Mart 1861'de tamamlandı; Cumhuriyet 2 Haziran 1946'da ilan edildi.",
    introTr:
      "Akdeniz'in ortasına çizme biçiminde uzanan İtalya, kuzeyde Alpler'le komşularından " +
      'ayrılır; ülke toprakları içinde iki bağımsız mikro-devlet, San Marino ve Vatikan, tam ' +
      'eksklav olarak yer alır.',
    landformNoteTr:
      'Ülkenin kuzey sınırını yaklaşık 1.000 kilometre boyunca çizen Alpler, İtalya ' +
      "topraklarının yaklaşık %40'ını kaplayan dağlık kesimin kuzey ayağıdır; Fransa " +
      "sınırındaki Mont Blanc, 4.810 metreyle hem İtalya'nın hem Avrupa Birliği'nin en yüksek " +
      "noktasıdır. Po Ovası'nın güneyinden başlayan Apenin Dağları, yarımadanın omurgasını " +
      "oluşturarak Liguria'dan Calabria'ya, oradan kuzey Sicilya'ya kadar 1.350 kilometre " +
      'boyunca uzanır ve Tiren ile Adriyatik-İyon kıyıları arasında bir su ayrım hattı ' +
      'oluşturur.' +
      '\n\n' +
      "Ülkenin en geniş ve en verimli ovası olan Po Ovası, İtalya'nın toplam düzlük alanının " +
      "büyük bölümünü oluşturur; adını, ülkenin en uzun nehri olan Po'dan alır.",
    climateNoteTr:
      "Kuzeydeki Po Ovası'nda (Milano, Torino, Bologna, Venedik) karasal bir iklim görülür, " +
      'yazlar sıcak ve nemli, kışlar soğuk ve sisli geçer. Kıyı kesimler ve güney, tipik ' +
      'Akdeniz iklimi altındadır — serin kışlar, sıcak ve kurak yazlar egemendir. Kuzeydeki Alp ' +
      'kesimlerinde ise dağ iklimi hakimdir, kışın sıcaklıklar sıfırın belirgin altına düşer, ' +
      'yıllık yağış 2.000 milimetreyi aşabilir.',
    hydrographyNoteTr:
      "İtalya'nın en uzun ve en önemli nehri, Fransa sınırındaki Kotya Alpleri'nde doğup Po " +
      "Ovası'nı kat ederek Adriyatik Denizi'ne geniş bir deltayla dökülen 652 kilometrelik " +
      "Po'dur. Tiber Nehri, Apenin Dağları'nda doğar, Roma'nın içinden geçerek Tiren Denizi'ne " +
      "ulaşır; uzunluğu 405 kilometredir. Arno Nehri, Floransa ve Pisa'dan geçerek Ligurya " +
      "Denizi'ne dökülür." +
      '\n\n' +
      "Ülkenin en büyük gölü olan Garda Gölü'nün yanı sıra Maggiore, Como ve Iseo gölleri, " +
      'kuzeydeki Alp eteklerinin başlıca doğal su kütleleridir.',
  },
  {
    isoCode: 'MT',
    isoCodeAlpha3: 'MLT',
    nameTr: 'Malta',
    nameEn: 'Malta',
    slugTr: 'malta',
    slugEn: 'malta',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 579_704,
    populationYear: null,
    areaKm2: 320,
    capitalNameTr: 'Valetta',
    capitalNameEn: 'Valletta',
    capitalLatitude: 35.8989,
    capitalLongitude: 14.5146,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Maltaca', 'İngilizce'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "21 Eylül 1964'te Birleşik Krallık'tan bağımsız oldu (Cumhuriyet 1974).",
  },
  {
    isoCode: 'ME',
    isoCodeAlpha3: 'MNE',
    nameTr: 'Karadağ',
    nameEn: 'Montenegro',
    slugTr: 'karadag',
    slugEn: 'montenegro',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 623_129,
    populationYear: null,
    areaKm2: 13_450,
    capitalNameTr: 'Podgoritsa',
    capitalNameEn: 'Podgorica',
    capitalLatitude: 42.4304,
    capitalLongitude: 19.2594,
    neighborIsoCodes: ['HR', 'BA', 'RS', 'XK', 'AL'],
    officialLanguagesTr: ['Karadağca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "3 Haziran 2006'da Sırbistan ile devlet birliğinden ayrılarak bağımsız oldu.",
    introTr:
      'Adı ("Kara Dağ") ülkenin karakterini özetleyen Karadağ, kuzeyde yüksek dağlarla başlayıp ' +
      'güneyde dar bir Adriyatik kıyı şeridiyle sona eren, küçük ama dikey olarak çok katmanlı ' +
      'bir ülkedir. Kuzeybatıda Bosna-Hersek, kuzeyde Sırbistan, doğuda Kosova, güneydoğuda ' +
      'Arnavutluk, batıda Hırvatistan ile komşudur.',
    landformNoteTr:
      'Ülkenin kuzeyi, 2.000 metrenin üzerinde 37 zirve barındıran yüksek dağlarla kaplıdır; ' +
      "bunların en tanınmışı, Durmitor kütlesinde yükselen 2.523 metrelik Bobotov Kuk'tur. Bu " +
      'dağlık kesimin güneyinde, çukurlar ve düzlüklerle bezeli bir karst platosu uzanır; ' +
      'platonun en alçak kesimini, Zeta ve aşağı Morača nehirlerinin oluşturduğu ' +
      'Zeta-Bjelopavlići Ovası oluşturur. En güneyde ise birkaç yüz metreden birkaç kilometreye ' +
      'kadar değişen genişlikte, yaklaşık 293 kilometre uzunluğunda dar bir Adriyatik kıyı ' +
      'ovası yer alır.',
    climateNoteTr:
      "Güneydeki kıyı şeridi ve Zeta-Bjelopavlići Ovası'nda uzun, sıcak ve kurak yazların, " +
      'ılıman ve yağışlı kışların görüldüğü Akdeniz iklimi hakimdir. Orta ve kuzey kesimlerde ' +
      'Akdeniz etkisi hâlâ hissedilse de dağ iklimi karakteri öne çıkar. En kuzeydeki karasal ' +
      'kesimde ise gün içi ve mevsimler arası sıcaklık farkları büyüktür. Yıllık yağış, ülkenin ' +
      'en kuzeyinde yaklaşık 800 milimetreden en güneyinde 5.000 milimetreye kadar çıkabilir — ' +
      "bu, Avrupa'nın en yağışlı bölgelerinden birini oluşturur.",
    hydrographyNoteTr:
      "Kuzeydeki Tara Nehri'nin oyduğu Tara Kanyonu, yer yer 1.300 metreyi bulan derinliğiyle " +
      "Avrupa'nın en derin kanyonudur. Piva, Tara ve Lim nehirleri kuzeye doğru akarken, Morača " +
      "ve Zeta nehirleri güneye yönelir ve başkent Podgoritsa yakınlarında İşkodra Gölü'ne " +
      'dökülür. Arnavutluk ile paylaşılan İşkodra Gölü, mevsimlere göre 370 ile 530 ' +
      "kilometrekare arasında değişen yüzölçümüyle Balkan Yarımadası'nın en büyük gölüdür.",
  },
  {
    isoCode: 'MK',
    isoCodeAlpha3: 'MKD',
    nameTr: 'Kuzey Makedonya',
    nameEn: 'North Macedonia',
    slugTr: 'kuzey-makedonya',
    slugEn: 'north-macedonia',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 1_820_909,
    populationYear: null,
    areaKm2: 25_220,
    capitalNameTr: 'Üsküp',
    capitalNameEn: 'Skopje',
    capitalLatitude: 41.9981,
    capitalLongitude: 21.4254,
    neighborIsoCodes: ['XK', 'RS', 'BG', 'GR', 'AL'],
    officialLanguagesTr: ['Makedonca'],
    currencyNameTr: 'Makedon Dinarı',
    currencyCode: 'MKD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "8 Eylül 1991'de Yugoslavya'dan bağımsız oldu.",
    introTr:
      "Vardar Nehri'nin kestiği bir vadi üzerine kurulu Kuzey Makedonya, denize kıyısı " +
      'bulunmayan, dağlarla kuşatılmış bir Orta Balkan ülkesidir. Kuzeyde Kosova ve Sırbistan, ' +
      'doğuda Bulgaristan, güneyde Yunanistan, batıda Arnavutluk ile komşudur.',
    landformNoteTr:
      'Ülke topraklarını kuzeyden Kosova sınırındaki Şar Dağları, doğudan Osogovo, batıdan ise ' +
      'Arnavutluk sınırındaki Korab kütlesi çevreler. Arnavutluk ile paylaşılan 2.764 metrelik ' +
      "Korab, Kuzey Makedonya'nın da en yüksek noktasıdır." +
      '\n\n' +
      'Bu dağlık çerçevenin ortasında, ülkeyi kuzeyden güneye kat eden Vardar Vadisi uzanır; ' +
      'vadi tabanı ve güneybatıdaki Pelagonya Ovası, ülkenin en verimli tarım alanlarını ' +
      'oluşturur.',
    climateNoteTr:
      "Vardar Vadisi'nin ovalık alanlarında Akdeniz ve Karadeniz etkilerinin karıştığı, yazları " +
      "subtropikal sıcaklıklara ulaşabilen (bazı yıllar 40°C'yi aşan) bir iklim görülür. " +
      'Güneydeki dağlar sıcak hava kütlelerinin kuzeye ilerlemesini kısmen engellediği için bu ' +
      'karasal-subtropikal karışım daha da belirginleşir. Çevredeki yüksek dağlık kesimlerde ' +
      'ise soğuk kışlı, kısa yazlı bir dağ iklimi egemendir.',
    hydrographyNoteTr:
      "Ülkenin en uzun akarsuyu, topraklarının yaklaşık %80'ini drene eden ve Yunanistan " +
      "üzerinden Ege Denizi'ne dökülen Vardar Nehri'dir; Kuzey Makedonya sınırları içindeki " +
      'uzunluğu yaklaşık 312 kilometredir.' +
      '\n\n' +
      'Güneybatıdaki Ohrid Gölü, Arnavutluk ile paylaşılan, 288 metreyi bulan derinliğiyle ' +
      "Balkanlar'ın en derin gölü ve dünyanın en eski göllerinden biridir; 200'ün üzerinde " +
      'endemik türe ev sahipliği yapar. Yine Arnavutluk ile paylaşılan Prespa Gölü, bölgenin ' +
      'diğer önemli sınır-ötesi su kütlesidir.',
  },
  {
    isoCode: 'PT',
    isoCodeAlpha3: 'PRT',
    nameTr: 'Portekiz',
    nameEn: 'Portugal',
    slugTr: 'portekiz',
    slugEn: 'portugal',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 10_804_871,
    populationYear: null,
    areaKm2: 91_606,
    capitalNameTr: 'Lizbon',
    capitalNameEn: 'Lisbon',
    capitalLatitude: 38.7223,
    capitalLongitude: -9.1393,
    neighborIsoCodes: ['ES'],
    officialLanguagesTr: ['Portekizce'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Yarı-başkanlık parlamenter cumhuriyeti',
    independenceNoteTr:
      "1143'te kuruldu; 1 Aralık 1640'ta İspanya'dan bağımsızlığın restorasyonu (resmî millî günlerden biri).",
    introTr:
      "Portekiz, İber Yarımadası'nın batı kıyısı boyunca uzanan, tamamı Atlas Okyanusu'na bakan " +
      'bir ülkedir. Ülkeyi doğudan batıya kat eden Tejo (Tagus) Nehri, kabaca kuzeyin daha dağlık ' +
      "arazisini güneyin daha düz ovalarından ayırır. Anakaraya ek olarak, Atlas Okyanusu'ndaki " +
      "Azorlar ve Madeira takımadaları da Portekiz'in özerk bölgeleridir.",
    landformNoteTr:
      "Tejo'nun kuzeyinde arazi belirgin biçimde yükselir; bu bölgenin doruk noktası Serra da " +
      "Estrela'daki Torre'dir. 1.993 metreye ulaşan bu nokta, anakara Portekiz'in en yüksek " +
      'yeridir. Douro Nehri vadisi boyunca, üzüm bağları için taraçalanmış dik yamaçlar bu kuzey ' +
      'bölgesinin karakteristik görünümünü oluşturur.' +
      '\n\n' +
      "Tejo'nun güneyinde arazi alçalır; Alentejo'nun geniş, dalgalı ovaları ve en güneyde " +
      "Algarve'nin kıyı şeridi bu düzlüğü oluşturur.",
    climateNoteTr:
      "Portekiz'de Atlas Okyanusu etkisiyle yumuşatılmış bir Akdeniz iklimi görülür. Kuzey, " +
      'okyanusa açıklığı nedeniyle daha yağışlı ve serindir. Güneye inildikçe yazlar uzar ve ' +
      "kuraklaşır; Alentejo'da yaz ayları neredeyse yağışsız geçebilir. Azorlar tam okyanusal bir " +
      'iklime, Madeira ise ılıman-subtropikal bir iklime sahiptir.',
    hydrographyNoteTr:
      "Tejo, İber Yarımadası'nın en uzun akarsuyudur; İspanya'da doğar, 1.007 kilometre boyunca " +
      "batıya akar ve Lizbon'da geniş bir haliç oluşturarak Atlas Okyanusu'na dökülür. Kuzeyde de " +
      'İspanya kaynaklı olan Douro Nehri, Porto kentinden geçerek okyanusa ulaşır; ağzına yakın ' +
      'kesimindeki bağlar, dünyaca tanınan Porto şarabının kaynağıdır. Her iki nehir de sınır ' +
      'ötesi bir havzaya sahiptir ve İspanya ile su paylaşım anlaşmalarına konu olur.',
  },
  {
    isoCode: 'SM',
    isoCodeAlpha3: 'SMR',
    nameTr: 'San Marino',
    nameEn: 'San Marino',
    slugTr: 'san-marino',
    slugEn: 'san-marino',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 34_109,
    populationYear: null,
    areaKm2: 60,
    capitalNameTr: 'San Marino',
    capitalNameEn: 'San Marino',
    capitalLatitude: 43.9424,
    capitalLongitude: 12.4578,
    neighborIsoCodes: ['IT'],
    officialLanguagesTr: ['İtalyanca'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: null,
  },
  {
    isoCode: 'RS',
    isoCodeAlpha3: 'SRB',
    nameTr: 'Sırbistan',
    nameEn: 'Serbia',
    slugTr: 'sirbistan',
    slugEn: 'serbia',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 6_549_143,
    populationYear: null,
    areaKm2: 84_090,
    capitalNameTr: 'Belgrad',
    capitalNameEn: 'Belgrade',
    capitalLatitude: 44.7866,
    capitalLongitude: 20.4489,
    neighborIsoCodes: ['HU', 'RO', 'BG', 'MK', 'ME', 'BA', 'HR', 'XK'],
    officialLanguagesTr: ['Sırpça'],
    currencyNameTr: 'Sırp Dinarı',
    currencyCode: 'RSD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "5 Haziran 2006'da bugünkü Sırbistan Cumhuriyeti kuruldu (Karadağ'ın ayrılmasıyla); Osmanlı'dan tanınma 1878.",
    introTr:
      "Tuna ve Sava nehirlerinin kesiştiği bir konumda kurulu Sırbistan, Balkan Yarımadası'nın " +
      'iç kesiminde denize kıyısı olmayan bir ülkedir. Kuzeyde Macaristan, doğuda Romanya ve ' +
      'Bulgaristan, güneyde Kuzey Makedonya, güneybatıda Karadağ, batıda Bosna-Hersek ve ' +
      'Hırvatistan ile komşudur.',
    landformNoteTr:
      "Ülkenin kuzeyini oluşturan Voyvodina, Pannon Ovası'nın bir parçası olan alçak ve verimli " +
      'bir düzlüktür; rakımı genellikle 60-100 metre arasında kalır. Orta ve güney kesimlere ' +
      'inildikçe arazi tepelik ve dağlık bir karaktere bürünür — Dinar, Karpat ve Rodop ' +
      'sıradağlarının uzantıları, ülkenin güneyinde birbirine yaklaşır. Bulgaristan sınırındaki ' +
      "Stara Planina üzerinde yükselen 2.169 metrelik Midžor, Sırbistan'ın tartışmasız " +
      'toprakları içindeki en yüksek noktasıdır.',
    climateNoteTr:
      "Voyvodina'nın düzlüklerinde ölçülü-karasal bir iklim görülür; Temmuz ortalaması yaklaşık " +
      '22°C, Ocak ortalaması ise eksi 1°C civarındadır. Güneye ve dağlık kesimlere doğru ' +
      'gidildikçe yükseklik etkisiyle kışlar daha soğuk ve yağışlı, yazlar ise daha serin ' +
      'geçer.',
    hydrographyNoteTr:
      'Tuna Nehri, Hırvatistan ile kuzeybatı sınırının ve Romanya ile güneydoğu sınırının bir ' +
      'bölümünü çizerek Sırbistan topraklarından yaklaşık 588 kilometre boyunca geçer. Batıdan ' +
      'gelen Sava, kuzeyden gelen Tisa ve güneyden gelen, Bosna-Hersek ile doğal sınır ' +
      "oluşturan Drina, Tuna'nın başlıca kollarıdır. Bu nehirler arasında yalnızca Morava, " +
      'kaynağından ağzına kadar tamamen Sırbistan toprakları içinde akar.',
  },
  {
    isoCode: 'SI',
    isoCodeAlpha3: 'SVN',
    nameTr: 'Slovenya',
    nameEn: 'Slovenia',
    slugTr: 'slovenya',
    slugEn: 'slovenia',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 2_130_986,
    populationYear: null,
    areaKm2: 20_135,
    capitalNameTr: 'Lübliyana',
    capitalNameEn: 'Ljubljana',
    capitalLatitude: 46.0569,
    capitalLongitude: 14.5058,
    neighborIsoCodes: ['IT', 'AT', 'HU', 'HR'],
    officialLanguagesTr: ['Slovence'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "25 Haziran 1991'de Yugoslavya'dan bağımsız oldu.",
  },
  {
    isoCode: 'ES',
    isoCodeAlpha3: 'ESP',
    nameTr: 'İspanya',
    nameEn: 'Spain',
    slugTr: 'ispanya',
    slugEn: 'spain',
    continent: Continent.Europe,
    unSubregionTr: 'Güney Avrupa',
    population: 49_355_143,
    populationYear: null,
    areaKm2: 499_697,
    capitalNameTr: 'Madrid',
    capitalNameEn: 'Madrid',
    capitalLatitude: 40.4168,
    capitalLongitude: -3.7038,
    neighborIsoCodes: ['PT', 'FR', 'AD', 'MA'],
    officialLanguagesTr: ['İspanyolca (Kastilyaca)'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: null,
    introTr:
      "İber Yarımadası'nın büyük bölümünü kaplayan İspanya, İsviçre'den sonra Avrupa'nın en " +
      'dağlık ikinci ülkesidir; kıtadaki komşularının yanı sıra, Afrika kıyısındaki Ceuta ve ' +
      "Melilla eksklavları üzerinden Fas'la da kara sınırı paylaşır.",
    landformNoteTr:
      'Ülkenin kalbini, ortalama 600-700 metre yükseklikte, çevresi dağlarla çevrili geniş bir ' +
      'iç plato olan Meseta Central oluşturur; bu plato İspanya topraklarının önemli bir ' +
      'bölümünü kaplar.' +
      '\n\n' +
      "Meseta'nın kuzeydoğu sınırını, Fransa'yla aradaki doğal seti oluşturan ve yaklaşık 490 " +
      'kilometre boyunca uzanan Pireneler çizer, zirveleri 3.400 metreyi aşar. Güneydoğuda, ' +
      "Endülüs'teki Baetik Sistem'in bir parçası olan Sierra Nevada, İspanya anakarasının en " +
      "yüksek noktası olan yaklaşık 3.479 metrelik Mulhacén'i barındırır.",
    climateNoteTr:
      "Meseta'yı çevreleyen dağlar deniz etkisindeki nemli havayı iç kesimlerden büyük ölçüde " +
      "keser; bu nedenle Meseta'da sıcak yaz ve soğuk kışın görüldüğü karasal bir iklim " +
      'egemendir. Kuzeyde, Bask Bölgesi, Asturias ve Kantabria kıyısında Atlas Okyanusu etkili, ' +
      'yıl boyu yağışlı bir okyanus iklimi görülür. Güney ve doğuda, Endülüs ile Ebro ' +
      "Vadisi'nde sıcak yaz ve ılık kışın görüldüğü tipik Akdeniz iklimi hakimdir; güneydoğuda " +
      "Alicante-Murcia-Almería üçgeninde ise yarı-kurak bir iklim egemendir, İspanya'nın en az " +
      'yağış alan bölgesidir.',
    hydrographyNoteTr:
      "İspanya'nın en uzun nehri, 1.007 kilometrelik Tajo'dur (Tagus); ülke içindeki bölümü 816 " +
      "kilometredir, Madrid yakınlarından geçerek Portekiz üzerinden Atlas Okyanusu'na ulaşır. " +
      "Ebro, Kantabria Dağları'nda doğar ve 900 kilometreyi aşan uzunluğuyla Akdeniz'e geniş " +
      "bir deltayla dökülür — hacim olarak İspanya'nın en büyük nehridir. Duero, kuzeyden " +
      "batıya akarak Portekiz'e geçer; Guadalquivir ise tamamen İspanya sınırları içinde " +
      "kalarak Kurtuba ve Sevilla'dan geçip Cádiz Körfezi'ne ulaşır.",
  },
  {
    isoCode: 'BY',
    isoCodeAlpha3: 'BLR',
    nameTr: 'Belarus',
    nameEn: 'Belarus',
    slugTr: 'belarus',
    slugEn: 'belarus',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 9_085_991,
    populationYear: null,
    areaKm2: 202_983,
    capitalNameTr: 'Minsk',
    capitalNameEn: 'Minsk',
    capitalLatitude: 53.9006,
    capitalLongitude: 27.559,
    neighborIsoCodes: ['RU', 'UA', 'PL', 'LT', 'LV'],
    officialLanguagesTr: ['Belarusça', 'Rusça'],
    currencyNameTr: 'Belarus Rublesi',
    currencyCode: 'BYN',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "25 Ağustos 1991'de Sovyetler Birliği'nden bağımsız oldu.",
  },
  {
    isoCode: 'CZ',
    isoCodeAlpha3: 'CZE',
    nameTr: 'Çekya',
    nameEn: 'Czechia',
    slugTr: 'cekya',
    slugEn: 'czechia',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 10_886_878,
    populationYear: null,
    areaKm2: 77_167,
    capitalNameTr: 'Prag',
    capitalNameEn: 'Prague',
    capitalLatitude: 50.0755,
    capitalLongitude: 14.4378,
    neighborIsoCodes: ['DE', 'PL', 'SK', 'AT'],
    officialLanguagesTr: ['Çekçe'],
    currencyNameTr: 'Çek Korunası',
    currencyCode: 'CZK',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "1 Ocak 1993'te Çekoslovakya'nın ayrılmasıyla kuruldu.",
  },
  {
    isoCode: 'HU',
    isoCodeAlpha3: 'HUN',
    nameTr: 'Macaristan',
    nameEn: 'Hungary',
    slugTr: 'macaristan',
    slugEn: 'hungary',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 9_514_251,
    populationYear: null,
    areaKm2: 91_260,
    capitalNameTr: 'Budapeşte',
    capitalNameEn: 'Budapest',
    capitalLatitude: 47.4979,
    capitalLongitude: 19.0402,
    neighborIsoCodes: ['AT', 'SK', 'UA', 'RO', 'RS', 'HR', 'SI'],
    officialLanguagesTr: ['Macarca'],
    currencyNameTr: 'Macar Forinti',
    currencyCode: 'HUF',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "Eski krallık geleneği ~1000'e dayanır; modern Üçüncü Cumhuriyet 23 Ekim 1989'da ilan edildi.",
  },
  {
    isoCode: 'MD',
    isoCodeAlpha3: 'MDA',
    nameTr: 'Moldova',
    nameEn: 'Moldova',
    slugTr: 'moldova',
    slugEn: 'moldova',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 2_360_527,
    populationYear: null,
    areaKm2: 32_930,
    capitalNameTr: 'Kişinev',
    capitalNameEn: 'Chisinau',
    capitalLatitude: 47.0105,
    capitalLongitude: 28.8638,
    neighborIsoCodes: ['RO', 'UA'],
    officialLanguagesTr: ['Romence'],
    currencyNameTr: 'Moldova Leyi',
    currencyCode: 'MDL',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "27 Ağustos 1991'de Sovyetler Birliği'nden bağımsız oldu.",
    introTr:
      "Doğu Avrupa'nın iç kesiminde, Prut ve Dinyester nehirleri arasında kalan Moldova, kara " +
      'ile çevrili bir ülke olmasına karşın güneydoğu ucundaki Giurgiuleşti kasabası çevresinde ' +
      "Tuna Nehri'ne yalnızca birkaç yüz metrelik dar bir kıyısı bulunur. Kuzeyde, doğuda ve " +
      'güneyde Ukrayna, batıda Romanya ile komşudur.',
    landformNoteTr:
      "Moldova'nın arazisi büyük ölçüde tepelik bir platodan oluşur; ülkenin hiçbir noktası 430 " +
      "metre rakımı aşmaz, en yüksek nokta 429 metrelik Bălăneşti Tepesi'dir. Kuzeyde, ortalama " +
      '150-200 metre rakımlı düzlük bir alan olan Bălţi Bozkırı yer alır. Ülkenin orta ' +
      'kesimini, "Codri" (ormanlar) adıyla anılan ormanlık Merkezi Moldova Platosu kaplar; ' +
      'kuzeydoğuda Dinyester Tepeleri, güneyde ise daha alçak ve düz bir arazi uzanır.',
    climateNoteTr:
      "Moldova, Karadeniz'in yakınlığıyla yumuşayan, ölçülü-karasal bir iklime sahiptir. Yazlar " +
      "sıcak ve uzun geçer, ortalama sıcaklık yaklaşık 20°C'dir; kışlar nispeten ılıman ve " +
      'kurak geçer, Ocak ortalaması eksi 4°C civarındadır. Ülkenin doğal bitki örtüsü, çayır ' +
      'alanlarla orman parçalarının iç içe geçtiği orman-bozkır karakterindedir — bu geçiş ' +
      'kuşağı en belirgin biçimde merkezdeki Codri bölgesinde görülür.',
    hydrographyNoteTr:
      'Ülkenin ana akarsuyu olan Dinyester (Nistru), Moldova topraklarının neredeyse tamamı ' +
      'boyunca gemilerle ulaşılabilir niteliktedir ve ılık geçen kışlarda donmaz. Prut Nehri, ' +
      "Romanya ile olan batı sınırının tamamını çizer. Ülkenin güneydoğu ucunda, 1990'ların " +
      "sonunda Ukrayna ile yapılan bir sınır düzenlemesiyle Moldova'ya geçen dar bir şerit, " +
      "Giurgiuleşti kasabası çevresinde Tuna Nehri'ne birkaç yüz metrelik bir kıyı kazandırdı — " +
      'kara ile çevrili ülkeye Tuna-Karadeniz hattı üzerinden tek doğrudan açık deniz ' +
      'bağlantısını sağlayan Giurgiuleşti Limanı, bu dar şerit üzerinde kuruludur.',
  },
  {
    isoCode: 'PL',
    isoCodeAlpha3: 'POL',
    nameTr: 'Polonya',
    nameEn: 'Poland',
    slugTr: 'polonya',
    slugEn: 'poland',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 36_435_861,
    populationYear: null,
    areaKm2: 306_270,
    capitalNameTr: 'Varşova',
    capitalNameEn: 'Warsaw',
    capitalLatitude: 52.2297,
    capitalLongitude: 21.0122,
    neighborIsoCodes: ['DE', 'CZ', 'SK', 'UA', 'BY', 'LT', 'RU'],
    officialLanguagesTr: ['Lehçe (Polonyaca)'],
    currencyNameTr: 'Polonya Zlotisi',
    currencyCode: 'PLN',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "11 Kasım 1918'de modern devlet yeniden kuruldu.",
    introTr:
      "Polonya topraklarının büyük bölümü Kuzey Avrupa Ovası'nın bir parçasıdır; ülkenin ortalama " +
      'yükseltisi düşüktür ve dağlık arazi yalnızca güney sınırında görülür. Kuzeyde Baltık ' +
      'Denizi kıyısı, güneyde ise Sudetler ve Karpatlar sıradağları ülkeyi çevreler. Batıda ' +
      'Almanya, güneyde Çekya ve Slovakya, doğuda Ukrayna ve Belarus, kuzeyde ise Litvanya ve ' +
      "Rusya'nın Kaliningrad eksklavı bulunur.",
    landformNoteTr:
      'Baltık kıyısı boyunca kumul setleri ve lagünler uzanır; Vistül Kumsalı ve Hel Yarımadası ' +
      'bu kıyı biçimlerinin en belirgin örnekleridir. İç kesimlerde, buzul çağından kalma ' +
      'binlerce gölün bulunduğu Mazurya Göller Bölgesi ülkenin kuzeydoğusunu kaplar. Güney ' +
      "sınırındaki Tatra Dağları, Polonya'nın en yüksek arazisidir; Slovakya ile paylaşılan Rysy " +
      'zirvesi, 2.499 metreye ulaşan üç doruğuyla ülkenin çatısını oluşturur. Ülkenin güneybatı ' +
      "ucunda, Tatralar'dan çok daha eski ve ayrı bir jeolojik kütle olan Sudetler sıradağı ise " +
      'daha alçak ve yuvarlak hatlı bir topografya sergiler.',
    climateNoteTr:
      'Polonya, batıdaki ılıman deniz iklimiyle doğudaki daha sert kıta iklimi arasında bir geçiş ' +
      'kuşağında yer alır. Baltık kıyısına yakın bölgelerde kışlar nispeten yumuşaktır. Doğuya ve ' +
      'iç kesimlere gidildikçe yaz-kış sıcaklık farkı belirginleşir. Güneydeki dağlık kesimlerde ' +
      'rakımın etkisiyle kışlar daha uzun sürer, kar örtüsü aylarca yerde kalır.',
    hydrographyNoteTr:
      "Ülkenin en uzun akarsuyu olan Vistül (Wisła), güneydeki Karpatlar'dan doğar, Varşova ve " +
      "Kraków gibi büyük şehirlerden geçerek yaklaşık 1.047 kilometre sonra Baltık Denizi'ne " +
      'dökülür. Batıda ülke topraklarının büyük bölümünü boşaltan Oder (Odra) Nehri ise 840 ' +
      'kilometrelik toplam uzunluğunun önemli bir bölümünde Almanya ile sınırı çizer. Her iki ' +
      "nehir de kuzeye, Baltık Denizi'ne akar; aralarında kalan havza, Polonya'nın tarım " +
      'arazilerinin çoğunu sular.',
  },
  {
    isoCode: 'RO',
    isoCodeAlpha3: 'ROU',
    nameTr: 'Romanya',
    nameEn: 'Romania',
    slugTr: 'romanya',
    slugEn: 'romania',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 19_020_271,
    populationYear: null,
    areaKm2: 230_080,
    capitalNameTr: 'Bükreş',
    capitalNameEn: 'Bucharest',
    capitalLatitude: 44.4268,
    capitalLongitude: 26.1025,
    neighborIsoCodes: ['HU', 'UA', 'MD', 'BG', 'RS'],
    officialLanguagesTr: ['Romence'],
    currencyNameTr: 'Romanya Leyi',
    currencyCode: 'RON',
    governmentFormTr: 'Yarı-başkanlık parlamenter cumhuriyeti',
    independenceNoteTr:
      "1877'de Osmanlı'dan bağımsızlığını ilan etti, 1878 Berlin Antlaşması'yla tanındı.",
    introTr:
      "Karpat Dağları'nın bir yay gibi kestiği Romanya, bu yayın çevrelediği platolar, ovalar " +
      've tepelerden oluşan bir Balkan-Karadeniz ülkesidir. Kuzeybatıda Macaristan, kuzeydoğuda ' +
      'Ukrayna, doğuda Moldova, güneyde Bulgaristan, batıda Sırbistan ile komşudur.',
    landformNoteTr:
      'Karpat Dağları, ülkeyi kuzeyden güneybatıya doğru üç kola ayrılarak kat eder: Doğu ' +
      'Karpatlar, Transilvanya Alpleri olarak da bilinen Güney Karpatlar ve Batı Karpatlar. ' +
      "Güney Karpatlar'ın Făgăraş kesiminde yükselen 2.544 metrelik Moldoveanu Zirvesi, ülkenin " +
      'en yüksek noktasıdır.' +
      '\n\n' +
      'Karpat yayının içinde Transilvanya Platosu, dışında ise kuzeydoğuda Moldova Platosu ve ' +
      "güneyde Eflak Ovası uzanır; batıda ülke, Pannon Ovası'nın bir kesimini paylaşır. Ülke " +
      'topraklarının yaklaşık üçte biri dağlık, üçte biri tepelik-platoluk, üçte biri ise ' +
      'düzlüktür.',
    climateNoteTr:
      'Romanya, ılıman-karasal bir iklime sahiptir; yazlar sıcak, kışlar nispeten ılımlı geçer. ' +
      'Karpatlar, Atlas Okyanusu kaynaklı nemli hava kütlelerinin etkisini batı ve merkez ' +
      'kesimlerle sınırlayarak buralarda daha ılıman kışlar ve daha bol yağış sağlar. Aynı ' +
      "sıradağ, doğudaki Rus Ovası'ndan gelen karasal etkiyi de büyük ölçüde güney ve güneydoğu " +
      'kesimlere yönlendirir; bu bölgelerde kışlar daha sert, yağış ise daha azdır.',
    hydrographyNoteTr:
      "Romanya'nın hemen hemen tüm akarsuları Karpat Dağları'ndan doğar. Ülkenin güney ve " +
      'güneydoğu sınırının büyük bölümünü çizen Tuna Nehri, yaklaşık 3.000 kilometrelik ' +
      "yolculuğunun sonunda Karadeniz'e dökülmeden önce üç kola ayrılarak Tuna Deltası'nı " +
      'oluşturur; sazlık adacıklar, bataklıklar ve kumullardan oluşan bu delta, Volga ' +
      "Deltası'ndan sonra Avrupa'nın en büyük ikinci nehir deltasıdır ve kıtanın en iyi " +
      'korunmuş deltası kabul edilir.',
  },
  {
    isoCode: 'RU',
    isoCodeAlpha3: 'RUS',
    nameTr: 'Rusya',
    nameEn: 'Russia',
    slugTr: 'rusya',
    slugEn: 'russia',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 143_513_328,
    populationYear: null,
    areaKm2: 16_376_870,
    capitalNameTr: 'Moskova',
    capitalNameEn: 'Moscow',
    capitalLatitude: 55.7558,
    capitalLongitude: 37.6173,
    neighborIsoCodes: [
      'NO',
      'FI',
      'EE',
      'LV',
      'LT',
      'PL',
      'BY',
      'UA',
      'GE',
      'AZ',
      'KZ',
      'MN',
      'CN',
      'KP',
    ],
    officialLanguagesTr: ['Rusça'],
    currencyNameTr: 'Rus Rublesi',
    currencyCode: 'RUB',
    governmentFormTr: 'Federal yarı-başkanlık cumhuriyeti',
    independenceNoteTr: null,
    introTr:
      'Toprakları hem Avrupa hem Asya kıtasına yayılan Rusya, yüzölçümü bakımından dünyanın en ' +
      "büyük ülkesidir — ikinci sıradaki Kanada'nın neredeyse iki katı büyüklüğündedir — ve on " +
      "dört ülkeyle kara sınırı paylaşarak Çin'le birlikte dünyanın en fazla kara komşusuna " +
      'sahip ülkesi unvanını taşır.',
    landformNoteTr:
      "Rusya'nın batı kesimini, Kuzey Buz Denizi'nden Kazakistan bozkırlarına kadar uzanan Ural " +
      'Dağları ikiye böler; bu sıradağ, Avrupa ile Asya arasındaki geleneksel kıta sınırı kabul ' +
      "edilir, en yüksek noktası 1.895 metrelik Narodnaya Dağı'dır. Ural'ın batısında kalan " +
      "geniş düzlük, Doğu Avrupa Ovası'nın bir parçasıdır." +
      '\n\n' +
      "Ural'ın doğusunda, ülke yüzölçümünün yaklaşık altıda birini kaplayan Batı Sibirya Ovası " +
      'uzanır — dünyanın en büyük düzlüklerinden biri, bataklık ve nehir ağlarıyla kaplı, ' +
      'neredeyse hiç engebesiz bir arazidir. Daha doğuda, Yenisey ve Lena nehirleri arasında ' +
      'kalan Orta Sibirya Platosu, derin vadilerle yarılmış bir yayla karakterindedir.' +
      '\n\n' +
      "Ülkenin güneyinde, Gürcistan sınırına yakın Kafkas Dağları'nda yükselen 5.642 metrelik " +
      "Elbruz, hem Rusya'nın hem Avrupa'nın en yüksek noktasıdır — sönmüş bir stratovolkandır. " +
      "Uzak Doğu'da ise Kamçatka Yarımadası'nın etkin yanardağları ve Sibirya'nın dağlık " +
      'kuşakları, ülkenin en engebeli kesimlerinden bazılarını oluşturur.',
    climateNoteTr:
      'Ülkenin devasa yüzölçümü ve denizden uzaklığı, iklimi kuzeyden güneye altı geniş kuşağa ' +
      'ayırır: kutup çölü, tundra, tayga, karışık-yapraklı orman, orman-bozkır ve bozkır. Kuzey ' +
      'kıyı şeridi ve adalarda tundra iklimi egemendir, yaz kısa ve serin geçer, toprak büyük ' +
      "ölçüde donmuş kalır (permafrost). Bu kuşağın güneyinde, Sibirya'nın büyük bölümünü " +
      'kaplayan tayga kuşağında sert, uzun kışlarla karakterize subarktik iklim görülür — ' +
      "dünyanın en soğuk yerleşim yerlerinden bazıları bu bölgededir. Avrupa Rusyası'nın " +
      "güneyi, Batı Sibirya'nın güneyi ve Uzak Doğu'nun bazı kesimleri (Moskova ve " +
      'Sankt-Peterburg dahil) nemli karasal bir iklim altındadır, dört mevsim belirgindir. ' +
      'Güneydeki bozkır kuşağında ise yazlar sıcak, kışlar soğuk ve kurak geçer. Güney ve ' +
      'doğudaki dağlık kesimlerde ise enlem yerine yükseklik belirleyici olur, kısa mesafelerde ' +
      'keskin iklim farklılıkları görülür.',
    hydrographyNoteTr:
      "Avrupa'nın en uzun nehri olan 3.531 kilometrelik Volga, tamamen Rusya sınırları içinde " +
      "akarak Hazar Denizi'ne dökülür. Sibirya'da, ülke sınırları içindeki en uzun nehir olan " +
      "4.294 kilometrelik Lena, Baykal Dağları'nda doğup Kuzey Buz Denizi'ne ulaşır. Yenisey, " +
      "Moğolistan'da doğan ana kolu Angara ile birlikte Kuzey Buz Denizi'ne akar; Angara, " +
      "dünyanın en derin gölü olan Baykal Gölü'nden çıkar. Ob Nehri ve kolu İrtiş, Batı Sibirya " +
      "Ovası'nı boydan boya kat eder." +
      '\n\n' +
      'Baykal Gölü, hem dünyanın en derin hem de en berrak gölü olarak kabul edilir.',
  },
  {
    isoCode: 'SK',
    isoCodeAlpha3: 'SVK',
    nameTr: 'Slovakya',
    nameEn: 'Slovakia',
    slugTr: 'slovakya',
    slugEn: 'slovakia',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 5_413_813,
    populationYear: null,
    areaKm2: 48_080,
    capitalNameTr: 'Bratislava',
    capitalNameEn: 'Bratislava',
    capitalLatitude: 48.1486,
    capitalLongitude: 17.1077,
    neighborIsoCodes: ['CZ', 'PL', 'UA', 'HU', 'AT'],
    officialLanguagesTr: ['Slovakça'],
    currencyNameTr: 'Euro',
    currencyCode: 'EUR',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "1 Ocak 1993'te Çekoslovakya'nın ayrılmasıyla kuruldu.",
  },
  {
    isoCode: 'UA',
    isoCodeAlpha3: 'UKR',
    nameTr: 'Ukrayna',
    nameEn: 'Ukraine',
    slugTr: 'ukrayna',
    slugEn: 'ukraine',
    continent: Continent.Europe,
    unSubregionTr: 'Doğu Avrupa',
    population: 38_980_376,
    populationYear: null,
    areaKm2: 579_400,
    capitalNameTr: 'Kiev',
    capitalNameEn: 'Kyiv',
    capitalLatitude: 50.4501,
    capitalLongitude: 30.5234,
    neighborIsoCodes: ['RU', 'BY', 'PL', 'SK', 'HU', 'RO', 'MD'],
    officialLanguagesTr: ['Ukraynaca'],
    currencyNameTr: 'Ukrayna Grivnası',
    currencyCode: 'UAH',
    governmentFormTr: 'Yarı-başkanlık parlamenter cumhuriyeti',
    independenceNoteTr:
      "24 Ağustos 1991'de Sovyetler Birliği'nden bağımsızlığını ilan etti (1 Aralık 1991 referandumuyla teyit).",
    introTr:
      "Rusya'dan sonra Avrupa'nın en büyük ikinci ülkesi olan Ukrayna — kıtada tamamen Avrupa " +
      "sınırları içinde kalan ülkeler arasında ise en büyüğüdür — Karadeniz ve Azak Denizi'ne " +
      'kıyısı olan geniş bir bozkır ülkesidir. Kuzeyde Belarus, kuzeydoğu ve doğuda Rusya, ' +
      'güneybatıda Romanya ve Moldova, batıda Polonya, Slovakya ve Macaristan ile komşudur.',
    landformNoteTr:
      'Ukrayna topraklarının büyük bölümünü verimli bozkırlar ve alçak platolar kaplar; ülkenin ' +
      "ana ekseni boyunca akan Dinyeper Nehri'nin çevresindeki düzlükler bu arazinin en geniş " +
      "parçasıdır. Ülkenin batı ucunda, Karpat Dağları'nın bir kolu yükselir; bu kesimde yer " +
      'alan 2.061 metrelik Hoverla, ülkenin en yüksek noktasıdır, yamaçları kayın ve ladin ' +
      'ormanları ile bunların üzerindeki "polonina" adı verilen sub-alpin çayırlarla kaplıdır.' +
      '\n\n' +
      "Güneyde, Karadeniz'e uzanan Kırım Yarımadası'nın kuzey ve orta kesimini (yaklaşık dörtte " +
      'üçünü) kurak bir bozkır düzlüğü oluşturur; yarımadanın güney kıyısı boyunca ise Kırım ' +
      "Dağları'nın üç paralel sırası uzanır, en yüksek noktası 1.545 metrelik Roman-Koş'tur.",
    climateNoteTr:
      'Ukrayna genel olarak ılıman-karasal bir iklime sahiptir; yıllık ortalama sıcaklık ' +
      "kuzeyde 5,5-7°C'den güneyde 11-13°C'ye kadar yükselir. Güney kıyı kesimleri (Kırım ve " +
      'Karadeniz kıyısı) yarı-kurak ve ılıman-nemli, farklı bir iklim kuşağındadır. Yağış ' +
      'dağılımı da dengesizdir: batıda, özellikle Karpat Dağları çevresinde yıllık ortalama ' +
      '1.200 milimetreye ulaşırken, Kırım ve Karadeniz kıyı şeridinde bu değer yaklaşık 400 ' +
      'milimetreye kadar düşer.',
    hydrographyNoteTr:
      'Ülkenin ana ekseni olan Dinyeper (Dnipro) Nehri, yaklaşık 2.200 kilometrelik uzunluğuyla ' +
      "Avrupa'nın Volga, Tuna ve Ural'dan sonra dördüncü en uzun nehridir ve güneye, " +
      "Karadeniz'e doğru akar. Batıda, Moldova sınırı boyunca akan Dinyester (Nistru), Desna, " +
      'Güney Bug ve Siverskyi Donets, ülkenin diğer büyük akarsularıdır; güneybatı ucunda Tuna ' +
      "Nehri de kısa bir kesimde Ukrayna topraklarından geçerek Karadeniz'e ulaşır." +
      '\n\n' +
      "Ülkenin güneydoğusundaki Azak Denizi, Kerç Boğazı üzerinden Karadeniz'e bağlanır ve " +
      'ortalama 7 metre, en derin noktasında ise 14 metre derinliğiyle dünyanın en sığ ' +
      'denizidir.',
  },
  {
    isoCode: 'AU',
    isoCodeAlpha3: 'AUS',
    nameTr: 'Avustralya',
    nameEn: 'Australia',
    slugTr: 'avustralya',
    slugEn: 'australia',
    continent: Continent.Oceania,
    unSubregionTr: 'Avustralya ve Yeni Zelanda',
    population: 27_614_411,
    populationYear: null,
    areaKm2: 7_692_020,
    capitalNameTr: 'Kanberra',
    capitalNameEn: 'Canberra',
    capitalLatitude: -35.2809,
    capitalLongitude: 149.13,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Avustralya Doları',
    currencyCode: 'AUD',
    governmentFormTr: 'Federal parlamenter anayasal monarşi',
    independenceNoteTr:
      "Federasyon 1 Ocak 1901'de kuruldu; tam anayasal bağımsızlık kademeli (1931 Westminster, 1986 Avustralya Yasası).",
  },
  {
    isoCode: 'NZ',
    isoCodeAlpha3: 'NZL',
    nameTr: 'Yeni Zelanda',
    nameEn: 'New Zealand',
    slugTr: 'yeni-zelanda',
    slugEn: 'new-zealand',
    continent: Continent.Oceania,
    unSubregionTr: 'Avustralya ve Yeni Zelanda',
    population: 5_324_700,
    populationYear: null,
    areaKm2: 263_310,
    capitalNameTr: 'Wellington',
    capitalNameEn: 'Wellington',
    capitalLatitude: -41.2865,
    capitalLongitude: 174.7762,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce', 'Maorice', 'Yeni Zelanda İşaret Dili'],
    currencyNameTr: 'Yeni Zelanda Doları',
    currencyCode: 'NZD',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr:
      'Dominyon statüsü 1907; tam bağımsızlık kademeli Commonwealth sürecinde kazanıldı.',
  },
  {
    isoCode: 'FJ',
    isoCodeAlpha3: 'FJI',
    nameTr: 'Fiji',
    nameEn: 'Fiji',
    slugTr: 'fiji',
    slugEn: 'fiji',
    continent: Continent.Oceania,
    unSubregionTr: 'Melanezya',
    population: 933_154,
    populationYear: null,
    areaKm2: 18_270,
    capitalNameTr: 'Suva',
    capitalNameEn: 'Suva',
    capitalLatitude: -18.1416,
    capitalLongitude: 178.4419,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce', 'Fijice', 'Fiji Hintçesi'],
    currencyNameTr: 'Fiji Doları',
    currencyCode: 'FJD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "10 Ekim 1970'te Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'PG',
    isoCodeAlpha3: 'PNG',
    nameTr: 'Papua Yeni Gine',
    nameEn: 'Papua New Guinea',
    slugTr: 'papua-yeni-gine',
    slugEn: 'papua-new-guinea',
    continent: Continent.Oceania,
    unSubregionTr: 'Melanezya',
    population: 10_762_817,
    populationYear: null,
    areaKm2: 452_860,
    capitalNameTr: 'Port Moresby',
    capitalNameEn: 'Port Moresby',
    capitalLatitude: -9.4438,
    capitalLongitude: 147.1803,
    neighborIsoCodes: ['ID'],
    officialLanguagesTr: ['İngilizce', 'Tok Pisin', 'Hiri Motu'],
    currencyNameTr: 'Papua Yeni Gine Kinası',
    currencyCode: 'PGK',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: "16 Eylül 1975'te Avustralya idaresinden bağımsız oldu.",
  },
  {
    isoCode: 'SB',
    isoCodeAlpha3: 'SLB',
    nameTr: 'Solomon Adaları',
    nameEn: 'Solomon Islands',
    slugTr: 'solomon-adalari',
    slugEn: 'solomon-islands',
    continent: Continent.Oceania,
    unSubregionTr: 'Melanezya',
    population: 838_645,
    populationYear: null,
    areaKm2: 27_990,
    capitalNameTr: 'Honiara',
    capitalNameEn: 'Honiara',
    capitalLatitude: -9.428,
    capitalLongitude: 159.9498,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'Solomon Adaları Doları',
    currencyCode: 'SBD',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: "7 Temmuz 1978'de Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'VU',
    isoCodeAlpha3: 'VUT',
    nameTr: 'Vanuatu',
    nameEn: 'Vanuatu',
    slugTr: 'vanuatu',
    slugEn: 'vanuatu',
    continent: Continent.Oceania,
    unSubregionTr: 'Melanezya',
    population: 335_169,
    populationYear: null,
    areaKm2: 12_190,
    capitalNameTr: 'Port Vila',
    capitalNameEn: 'Port Vila',
    capitalLatitude: -17.7333,
    capitalLongitude: 168.3273,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Bislama', 'İngilizce', 'Fransızca'],
    currencyNameTr: 'Vanuatu Vatusu',
    currencyCode: 'VUV',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr:
      "30 Temmuz 1980'de Birleşik Krallık-Fransa ortak yönetiminden bağımsız oldu.",
  },
  {
    isoCode: 'KI',
    isoCodeAlpha3: 'KIR',
    nameTr: 'Kiribati',
    nameEn: 'Kiribati',
    slugTr: 'kiribati',
    slugEn: 'kiribati',
    continent: Continent.Oceania,
    unSubregionTr: 'Mikronezya',
    population: 136_488,
    populationYear: null,
    areaKm2: 810,
    capitalNameTr: 'Tarava',
    capitalNameEn: 'Tarawa',
    capitalLatitude: 1.3291,
    capitalLongitude: 172.979,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce', 'Gilbertçe'],
    currencyNameTr: 'Avustralya Doları',
    currencyCode: 'AUD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "12 Temmuz 1979'da Birleşik Krallık'tan bağımsız oldu.",
  },
  {
    isoCode: 'MH',
    isoCodeAlpha3: 'MHL',
    nameTr: 'Marşal Adaları',
    nameEn: 'Marshall Islands',
    slugTr: 'marsal-adalari',
    slugEn: 'marshall-islands',
    continent: Continent.Oceania,
    unSubregionTr: 'Mikronezya',
    population: 36_282,
    populationYear: null,
    areaKm2: 180,
    capitalNameTr: 'Majuro',
    capitalNameEn: 'Majuro',
    capitalLatitude: 7.1164,
    capitalLongitude: 171.1858,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Marşalca', 'İngilizce'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr:
      "21 Ekim 1986'da ABD ile Serbest Ortaklık Anlaşması yürürlüğe girdi (BM üyeliği 1991).",
  },
  {
    isoCode: 'FM',
    isoCodeAlpha3: 'FSM',
    nameTr: 'Mikronezya Federe Devletleri',
    nameEn: 'Federated States of Micronesia',
    slugTr: 'mikronezya-federe-devletleri',
    slugEn: 'federated-states-of-micronesia',
    continent: Continent.Oceania,
    unSubregionTr: 'Mikronezya',
    population: 113_683,
    populationYear: null,
    areaKm2: 700,
    capitalNameTr: 'Palikir',
    capitalNameEn: 'Palikir',
    capitalLatitude: 6.9248,
    capitalLongitude: 158.1611,
    neighborIsoCodes: [],
    officialLanguagesTr: ['İngilizce'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Federal başkanlık cumhuriyeti',
    independenceNoteTr:
      "3 Kasım 1986'da ABD ile Serbest Ortaklık Anlaşması yürürlüğe girdi (BM üyeliği 1991).",
  },
  {
    isoCode: 'NR',
    isoCodeAlpha3: 'NRU',
    nameTr: 'Nauru',
    nameEn: 'Nauru',
    slugTr: 'nauru',
    slugEn: 'nauru',
    continent: Continent.Oceania,
    unSubregionTr: 'Mikronezya',
    population: 12_025,
    populationYear: null,
    areaKm2: 20,
    capitalNameTr: 'Yaren',
    capitalNameEn: 'Yaren',
    capitalLatitude: -0.5477,
    capitalLongitude: 166.9209,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Nauruca', 'İngilizce'],
    currencyNameTr: 'Avustralya Doları',
    currencyCode: 'AUD',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "31 Ocak 1968'de bağımsız oldu.",
  },
  {
    isoCode: 'PW',
    isoCodeAlpha3: 'PLW',
    nameTr: 'Palau',
    nameEn: 'Palau',
    slugTr: 'palau',
    slugEn: 'palau',
    continent: Continent.Oceania,
    unSubregionTr: 'Mikronezya',
    population: 17_663,
    populationYear: null,
    areaKm2: 460,
    capitalNameTr: 'Melekeok',
    capitalNameEn: 'Melekeok',
    capitalLatitude: 7.5006,
    capitalLongitude: 134.6242,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Palauca', 'İngilizce'],
    currencyNameTr: 'ABD Doları',
    currencyCode: 'USD',
    governmentFormTr: 'Başkanlık cumhuriyeti',
    independenceNoteTr: "1 Ekim 1994'te ABD ile Serbest Ortaklık Anlaşması yürürlüğe girdi.",
  },
  {
    isoCode: 'WS',
    isoCodeAlpha3: 'WSM',
    nameTr: 'Samoa',
    nameEn: 'Samoa',
    slugTr: 'samoa',
    slugEn: 'samoa',
    continent: Continent.Oceania,
    unSubregionTr: 'Polinezya',
    population: 219_306,
    populationYear: null,
    areaKm2: 2_780,
    capitalNameTr: 'Apia',
    capitalNameEn: 'Apia',
    capitalLatitude: -13.8506,
    capitalLongitude: -171.7513,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Samoaca', 'İngilizce'],
    currencyNameTr: 'Samoa Talası',
    currencyCode: 'WST',
    governmentFormTr: 'Parlamenter cumhuriyet',
    independenceNoteTr: "1 Ocak 1962'de Yeni Zelanda idaresinden bağımsız oldu.",
  },
  {
    isoCode: 'TO',
    isoCodeAlpha3: 'TON',
    nameTr: 'Tonga',
    nameEn: 'Tonga',
    slugTr: 'tonga',
    slugEn: 'tonga',
    continent: Continent.Oceania,
    unSubregionTr: 'Polinezya',
    population: 103_742,
    populationYear: null,
    areaKm2: 720,
    capitalNameTr: "Nuku'alofa",
    capitalNameEn: "Nuku'alofa",
    capitalLatitude: -21.1393,
    capitalLongitude: -175.2049,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Tongaca', 'İngilizce'],
    currencyNameTr: "Tonga Pa'angası",
    currencyCode: 'TOP',
    governmentFormTr: 'Anayasal monarşi (parlamenter)',
    independenceNoteTr: "4 Haziran 1970'te Birleşik Krallık himayesi sona erdi.",
  },
  {
    isoCode: 'TV',
    isoCodeAlpha3: 'TUV',
    nameTr: 'Tuvalu',
    nameEn: 'Tuvalu',
    slugTr: 'tuvalu',
    slugEn: 'tuvalu',
    continent: Continent.Oceania,
    unSubregionTr: 'Polinezya',
    population: 9_492,
    populationYear: null,
    areaKm2: 30,
    capitalNameTr: 'Funafuti',
    capitalNameEn: 'Funafuti',
    capitalLatitude: -8.5211,
    capitalLongitude: 179.1983,
    neighborIsoCodes: [],
    officialLanguagesTr: ['Tuvaluca', 'İngilizce'],
    currencyNameTr: 'Avustralya Doları',
    currencyCode: 'AUD',
    governmentFormTr: 'Parlamenter anayasal monarşi',
    independenceNoteTr: "1 Ekim 1978'de Birleşik Krallık'tan bağımsız oldu.",
  },
];
