import { Check, Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';
import { AccountRole, EducationLevel, GradeLevel, StudyStream } from '../account.types';
import type { MailLocale } from '../mail/mailer.port';

/**
 * ONE candidate registration for an address that has no `users` row yet: the submitted profile,
 * the Argon2id hash of the submitted password, and the HMAC of the 6-digit e-posta doğrulama kodu
 * that will materialize it (`GLOSSARY.md` §7: "e-posta doğrulama kodu", never "onay kodu").
 *
 * ## Why this table exists at all (`SEC136-C1`, PR #136 review)
 * Registration used to write the `users` row immediately, UNVERIFIED, and re-registering the same
 * address silently DISCARDED the second submission's password and profile. That made an
 * unverified `users` row a one-slot resource an unauthenticated caller could claim: whoever
 * registered an address FIRST owned the credentials, and the victim who later verified their own
 * mailbox activated the attacker's password on their own verified address.
 *
 * The naive repair — "let the newest register overwrite the UNVERIFIED row" — was measured and
 * REJECTED by owner ruling: it turns `POST /register` into an overwrite primitive over other
 * people's rows and only flips the race from first-writer-wins to last-writer-wins. So the slot is
 * gone instead. An address may carry SEVERAL live candidates at once, each with its own
 * credentials and its own code, and the `users` row is materialized in the verify transaction
 * from the candidate whose code was actually presented.
 *
 * ## The invariant this file exists to hold
 * **A code is not transferable: one candidate's code can never materialize another candidate.**
 * The digest input binds the candidate's own PRIMARY KEY —
 * `HMAC-SHA256(AUTH_HMAC_PEPPER, "pending:" + id + ":" + code)` — so a digest minted for one row
 * cannot match against a sibling row for the same address, exactly as the old digest bound
 * `user_id`. `id` is therefore generated by the APPLICATION (`randomUUID()`) and inserted
 * explicitly rather than left to the column default: the digest has to be computed before the
 * INSERT, so the key cannot be assigned by the database.
 *
 * ## Residual risk, accepted by the owner rather than engineered away
 * Two live candidates mean two codes in one mailbox, and a victim who enters the ATTACKER's code
 * materializes the attacker's password on their own address. That risk is owner-accepted and its
 * mitigation is the wording of the verification e-mail, which is `cografya_web`'s (UYELIK-04), not
 * this table's. What this table removes is the SILENT half: nothing is overwritten, nothing is
 * discarded, and the code the user types decides which credentials become the account.
 *
 * **`resend` additionally refuses to clone across a credential mismatch (D2, `SEC136R2-I3`,
 * PR #136 round 3).** The previous behaviour cloned the address's newest candidate unconditionally,
 * which meant a victim's OWN resend — triggered after an attacker had silently registered the same
 * address — carried the attacker's credentials into the victim's own mailbox, defeating the one
 * working mitigation (temporal correlation: a resend right after YOUR OWN register is trustworthy).
 * `insertCandidate` now refuses to write OR MAIL ANYTHING when the address's locked candidate group
 * carries more than one distinct `password_hash` — the refusal runs BEFORE the expired-row sweep, so
 * it cannot even delete the evidence it just refused on (round 3's own order did exactly that and
 * turned the protection into a one-call defence — `SEC136R3-I1`/`SFH136R3-I3`, pinned by V6b's
 * two-call assertion) — closing the whole "attacker registers, then the real owner's resend hands
 * them the attacker's password" class. The residual this leaves, at the width `DEC 2026-08-25p`
 * accepts: an ambiguous group stops being ambiguous only once something SWEEPS the expired row, and
 * the one thing that sweeps it is a `register` for that same address — which an attacker can trigger
 * by spending ONE of their own three daily `REGISTER_EMAIL` slots. Once that sweep runs, the
 * attacker's is the address's only live candidate and the clone is still theirs (measured: scenario
 * S7, PR #136 round 4 Phase 1). Only D1 (binding the resend request to a credential the caller can
 * prove, e.g. a password check) closes that residual, and D1 did not land this round — it is a
 * separate, Atlas-tracked follow-up (`FU-AUTH-RESEND-PROOF`).
 *
 * ## Column set
 * Every column below is a straight copy target for `users` — materialization is a field-for-field
 * INSERT with no transformation — plus the four code-mechanics columns and `locale`. `locale` is
 * carried HERE and not on `users` on purpose: it is the language of one verification e-mail, not a
 * user preference, and holding it lets a resend honour the language the original register asked
 * for (the old flow had nowhere to keep it and defaulted every bare resend to `tr`).
 *
 * The CHECK constraints mirror `user.entity.ts` token for token for the columns they share.
 * Nothing machine-compares the two, and that is the same standing caveat `InitUsers` carries: they
 * change together by hand. They are not redundant with the DTO — a candidate that could not
 * satisfy `users`' own constraints would fail at MATERIALIZATION time, i.e. after the user typed a
 * correct code, as a 400 they could never clear.
 *
 * The MIGRATION is the schema truth; these decorators are declared so the access paths read beside
 * the columns.
 */
@Entity('pending_registrations')
@Index('IDX_pending_registrations_email', ['email'])
@Index('IDX_pending_registrations_expires_at', ['expiresAt'])
@Check('CHK_pending_registrations_code_hash_length', `octet_length("code_hash") = 32`)
@Check('CHK_pending_registrations_attempts', `"attempt_count" >= 0 AND "attempt_count" <= 5`)
// Deliberately NO `expires_at > created_at` CHECK, unlike `sessions`: `created_at` is filled by
// the DATABASE's `now()` while `expires_at` is computed in the APPLICATION, so such a constraint
// would compare two clocks and could reject a perfectly valid row under skew. `sessions` can
// carry its equivalent because both of its timestamps come from the same application clock.
@Check('CHK_pending_registrations_locale', `"locale" IN ('tr', 'en')`)
@Check(
  'CHK_pending_registrations_first_name',
  `"first_name" <> '' AND "first_name" = btrim("first_name")`,
)
@Check(
  'CHK_pending_registrations_last_name',
  `"last_name" <> '' AND "last_name" = btrim("last_name")`,
)
@Check('CHK_pending_registrations_phone', `"phone" ~ '^\\+905[0-9]{9}$'`)
@Check(
  'CHK_pending_registrations_email_canonical',
  `"email" <> '' AND "email" = btrim("email") AND "email" = lower("email")`,
)
@Check('CHK_pending_registrations_password_hash', `"password_hash" ~ '^\\$argon2id\\$'`)
@Check('CHK_pending_registrations_account_role', `"account_role" IN ('STUDENT', 'TEACHER')`)
@Check(
  'CHK_pending_registrations_education_level',
  `"education_level" IS NULL OR "education_level" IN ('SECONDARY', 'UNDERGRADUATE', 'GRADUATE')`,
)
@Check(
  'CHK_pending_registrations_grade_level',
  `"grade_level" IS NULL OR "grade_level" IN (` +
    `'GRADE_5', 'GRADE_6', 'GRADE_7', 'GRADE_8', 'GRADE_9', 'GRADE_10', ` +
    `'GRADE_11', 'GRADE_12', 'MEZUN', 'KPSS', 'DIGER')`,
)
@Check(
  'CHK_pending_registrations_study_stream',
  `"study_stream" IS NULL OR "study_stream" IN (` +
    `'SAYISAL', 'SOZEL', 'ESIT_AGIRLIK', 'TYT', 'DIL', 'LGS', 'MSU', ` +
    `'ARA_SINIF', 'KPSS', 'DIGER')`,
)
@Check(
  'CHK_pending_registrations_university_name',
  `"university_name" IS NULL OR (` +
    `"university_name" <> '' AND "university_name" = btrim("university_name"))`,
)
@Check(
  'CHK_pending_registrations_department_name',
  `"department_name" IS NULL OR (` +
    `"department_name" <> '' AND "department_name" = btrim("department_name"))`,
)
// The outer `IS TRUE` is load-bearing for the same reason it is on `users`: with
// `education_level` NULL the STUDENT branch evaluates to UNKNOWN and a Postgres CHECK accepts
// UNKNOWN. Mirrored token for token from `user.entity.ts`'s `CHK_users_profile_shape`.
@Check(
  'CHK_pending_registrations_profile_shape',
  `((` +
    `"account_role" = 'TEACHER' AND ` +
    `"education_level" IS NULL AND "grade_level" IS NULL AND "study_stream" IS NULL AND ` +
    `"university_name" IS NULL AND "department_name" IS NULL` +
    `) OR (` +
    `"account_role" = 'STUDENT' AND (` +
    `(` +
    `"education_level" IS NULL AND "grade_level" IS NULL AND "study_stream" IS NULL AND ` +
    `"university_name" IS NULL AND "department_name" IS NULL` +
    `) OR (` +
    `"education_level" = 'SECONDARY' AND "grade_level" IS NOT NULL AND ` +
    `"study_stream" IS NOT NULL AND "university_name" IS NULL AND "department_name" IS NULL` +
    `) OR (` +
    `"education_level" = 'UNDERGRADUATE' AND "grade_level" IS NULL AND ` +
    `"study_stream" IS NULL AND "university_name" IS NOT NULL AND ` +
    `"department_name" IS NOT NULL` +
    `) OR (` +
    `"education_level" = 'GRADUATE' AND "grade_level" IS NULL AND ` +
    `"study_stream" IS NULL AND "university_name" IS NOT NULL` +
    `)` +
    `)` +
    `)) IS TRUE`,
)
export class PendingRegistration {
  /**
   * Assigned by the APPLICATION, never by the column default: the code digest binds this value,
   * so it has to exist before the row does. The migration still declares `gen_random_uuid()` as a
   * belt — a row inserted without an explicit id would simply carry a digest nothing can match,
   * which fails closed.
   */
  @PrimaryGeneratedColumn('uuid', { primaryKeyConstraintName: 'PK_pending_registrations' })
  id!: string;

  /** Canonical (trimmed, lower-cased) address. NOT unique — several candidates may share one. */
  @Column({ name: 'email', type: 'varchar', length: 254 })
  email!: string;

  /** Argon2id hash of the password THIS candidate submitted. Copied verbatim on materialization. */
  @Column({ name: 'password_hash', type: 'text' })
  passwordHash!: string;

  @Column({ name: 'first_name', type: 'varchar', length: 100 })
  firstName!: string;

  @Column({ name: 'last_name', type: 'varchar', length: 100 })
  lastName!: string;

  @Column({ name: 'phone', type: 'varchar', length: 13 })
  phone!: string;

  @Column({ name: 'account_role', type: 'varchar', length: 16 })
  accountRole!: AccountRole;

  @Column({ name: 'education_level', type: 'varchar', length: 20, nullable: true })
  educationLevel!: EducationLevel | null;

  @Column({ name: 'grade_level', type: 'varchar', length: 16, nullable: true })
  gradeLevel!: GradeLevel | null;

  @Column({ name: 'study_stream', type: 'varchar', length: 20, nullable: true })
  studyStream!: StudyStream | null;

  @Column({ name: 'university_name', type: 'varchar', length: 200, nullable: true })
  universityName!: string | null;

  @Column({ name: 'department_name', type: 'varchar', length: 200, nullable: true })
  departmentName!: string | null;

  /** `ON DELETE CASCADE` — a candidate pointing at a removed ilçe could never materialize. */
  @Column({ name: 'district_id', type: 'uuid' })
  districtId!: string;

  /** Language of THIS candidate's verification e-mail; a resend clone inherits it. */
  @Column({ name: 'locale', type: 'varchar', length: 2, default: 'tr' })
  locale!: MailLocale;

  /** `HMAC-SHA256(AUTH_HMAC_PEPPER, "pending:" + id + ":" + code)` — see the class docblock. */
  @Column({ name: 'code_hash', type: 'bytea' })
  codeHash!: Buffer;

  /** `created_at + EMAIL_VERIFICATION_TTL_MINUTES`. */
  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt!: Date;

  /**
   * Wrong-guess counter (§5.3's cap of 5).
   *
   * **Reaching the cap kills the CODE, not the row.** The old table deleted the row on the fifth
   * wrong attempt; here the row stays until it expires and `verify` simply stops considering it,
   * which has three measured consequences and no downside: (a) no caller without a valid code can
   * DELETE anything, (b) the honest owner's `resend` can still clone the credentials of a
   * candidate an attacker burned, so a third party cannot force a re-registration, and (c) the
   * counter's ceiling is enforced by not incrementing past it, so the CHECK above cannot be
   * violated by a concurrent pair — the failure mode `SFH136-I1` named in the review.
   */
  @Column({ name: 'attempt_count', type: 'smallint', default: 0 })
  attemptCount!: number;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;
}
