import type { DepartmentDto } from './dto/department.dto';

/**
 * The published bölüm list — **GENERATED, never hand-edited** (üyelik plan §3, PR-2).
 *
 * ## Where every row comes from
 * `data/reference/departments.yokatlas.json` is a byte copy of the collected artefact and is the
 * only source of truth for this file. `reference-lists.spec.ts` re-derives the array from that JSON
 * on every CI run and fails on any disagreement.
 *
 * ## The conversion is a NO-OP here, and that is asserted rather than assumed
 * Unlike the üniversite list, this source already arrives in the reader's writing — bare programme
 * names, `ve` kept small. The spec still runs the same `toDisplayWritingForm` over it and requires
 * it to change nothing, which is what pins the two lists to ONE writing convention instead of two
 * that merely happen to agree today.
 *
 * ## Scope, and the two rulings that set it
 * 345 lisans programme names. Önlisans is out of scope (`DEC 2026-08-20p` md.4) and the five
 * umbrella group names were removed at the source by the owner's decision (`DEC 2026-08-21a`); this
 * repo removes nothing of its own and adds nothing of its own. The source surface publishes no
 * usage terms, which is recorded verbatim as `[KAYNAK DOĞRULANAMADI]` in `provenance/datasets.md`
 * together with the owner's decision to seed the list anyway and the follow-up to rebuild it from
 * ÖSYM's own guide (`FU-BOLUM-KAYNAK-OSYM`).
 *
 * These rows are module-private on purpose, for the reason `university.data.ts` records:
 * {@link DEPARTMENTS} below is the published value and it is the frozen one.
 */
const DEPARTMENT_ROWS: DepartmentDto[] = [
  { nameTr: 'Abaza Dili ve Edebiyatı' },
  { nameTr: 'Acil Yardım ve Afet Yönetimi' },
  { nameTr: 'Adli Bilimler' },
  { nameTr: 'Adli Bilişim Mühendisliği' },
  { nameTr: 'Ağaç İşleri Endüstri Mühendisliği' },
  { nameTr: 'Aktüerya Bilimleri' },
  { nameTr: 'Alman Dili ve Edebiyatı' },
  { nameTr: 'Almanca Mütercim ve Tercümanlık' },
  { nameTr: 'Almanca Öğretmenliği' },
  { nameTr: 'Amerikan Kültürü ve Edebiyatı' },
  { nameTr: 'Antrenörlük Eğitimi' },
  { nameTr: 'Antropoloji' },
  { nameTr: 'Arap Dili ve Edebiyatı' },
  { nameTr: 'Arapça Mütercim ve Tercümanlık' },
  { nameTr: 'Arapça Öğretmenliği' },
  { nameTr: 'Arkeoloji' },
  { nameTr: 'Arkeoloji ve Sanat Tarihi' },
  { nameTr: 'Arnavut Dili ve Edebiyatı' },
  { nameTr: 'Astronomi ve Uzay Bilimleri' },
  { nameTr: 'Ayakkabı Tasarımı ve Üretimi' },
  { nameTr: 'Azerbaycan Türkçesi ve Edebiyatı' },
  { nameTr: 'Bahçe Bitkileri' },
  { nameTr: 'Balıkçılık Teknolojisi Mühendisliği' },
  { nameTr: 'Bankacılık' },
  { nameTr: 'Bankacılık ve Sigortacılık' },
  { nameTr: 'Basım Teknolojileri' },
  { nameTr: 'Basın ve Yayın' },
  { nameTr: 'Beden Eğitimi ve Spor Öğretmenliği' },
  { nameTr: 'Beslenme ve Diyetetik' },
  { nameTr: 'Bilgi Güvenliği Teknolojisi' },
  { nameTr: 'Bilgi ve Belge Yönetimi' },
  { nameTr: 'Bilgisayar Bilimleri' },
  { nameTr: 'Bilgisayar Mühendisliği' },
  { nameTr: 'Bilgisayar Teknolojisi ve Bilişim Sistemleri' },
  { nameTr: 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği' },
  { nameTr: 'Bilim Tarihi' },
  { nameTr: 'Bilişim Sistemleri Mühendisliği' },
  { nameTr: 'Bilişim Sistemleri ve Teknolojileri' },
  { nameTr: 'Bitki Koruma' },
  { nameTr: 'Bitkisel Üretim ve Teknolojileri' },
  { nameTr: 'Biyokimya' },
  { nameTr: 'Biyoloji' },
  { nameTr: 'Biyoloji Öğretmenliği' },
  { nameTr: 'Biyomedikal Mühendisliği' },
  { nameTr: 'Biyomühendislik' },
  { nameTr: 'Biyosistem Mühendisliği' },
  { nameTr: 'Biyoteknoloji' },
  { nameTr: 'Biyoteknoloji ve Genetik' },
  { nameTr: 'Boşnak Dili ve Edebiyatı' },
  { nameTr: 'Bulgar Dili ve Edebiyatı' },
  { nameTr: 'Bulgarca Mütercim ve Tercümanlık' },
  { nameTr: 'Cevher Hazırlama Mühendisliği' },
  { nameTr: 'Coğrafya' },
  { nameTr: 'Coğrafya Öğretmenliği' },
  { nameTr: 'Çağdaş Türk Lehçeleri ve Edebiyatları' },
  { nameTr: 'Çağdaş Yunan Dili ve Edebiyatı' },
  { nameTr: 'Çalışma Ekonomisi ve Endüstri İlişkileri' },
  { nameTr: 'Çerkez Dili ve Edebiyatı' },
  { nameTr: 'Çerkez Dili ve Kültürü' },
  { nameTr: 'Çeviribilimi' },
  { nameTr: 'Çevre Mühendisliği' },
  { nameTr: 'Çin Dili ve Edebiyatı' },
  { nameTr: 'Çince Mütercim ve Tercümanlık' },
  { nameTr: 'Çizgi Film ve Animasyon' },
  { nameTr: 'Çocuk Gelişimi' },
  { nameTr: 'Deniz Ulaştırma İşletme Mühendisliği' },
  { nameTr: 'Denizcilik İşletmeleri Yönetimi' },
  { nameTr: 'Deri Mühendisliği' },
  { nameTr: 'Dijital Oyun Tasarımı' },
  { nameTr: 'Dil ve Konuşma Terapisi' },
  { nameTr: 'Dilbilimi' },
  { nameTr: 'Diş Hekimliği' },
  { nameTr: 'Doğa Koruma ve Biyoçeşitlilik Yönetimi' },
  { nameTr: 'Ebelik' },
  { nameTr: 'Eczacılık' },
  { nameTr: 'Egzersiz ve Spor Bilimleri' },
  { nameTr: 'Ekonometri' },
  { nameTr: 'Ekonomi' },
  { nameTr: 'Ekonomi ve Finans' },
  { nameTr: 'El Sanatları' },
  { nameTr: 'Elektrik Mühendisliği' },
  { nameTr: 'Elektrik-Elektronik Mühendisliği' },
  { nameTr: 'Elektronik Mühendisliği' },
  { nameTr: 'Elektronik Ticaret ve Yönetimi' },
  { nameTr: 'Elektronik ve Haberleşme Mühendisliği' },
  { nameTr: 'Endüstri Mühendisliği' },
  { nameTr: 'Endüstriyel Tasarım' },
  { nameTr: 'Endüstriyel Tasarım Mühendisliği' },
  { nameTr: 'Enerji Bilimi ve Teknolojileri' },
  { nameTr: 'Enerji Sistemleri Mühendisliği' },
  { nameTr: 'Enerji Yönetimi' },
  { nameTr: 'Ergoterapi' },
  { nameTr: 'Ermeni Dili ve Kültürü' },
  { nameTr: 'Eski Yunan Dili ve Edebiyatı' },
  { nameTr: 'Fars Dili ve Edebiyatı' },
  { nameTr: 'Farsça Mütercim ve Tercümanlık' },
  { nameTr: 'Felsefe' },
  { nameTr: 'Felsefe Grubu Öğretmenliği' },
  { nameTr: 'Fen Bilgisi Öğretmenliği' },
  { nameTr: 'Film Tasarımı ve Yönetimi' },
  { nameTr: 'Finans ve Bankacılık' },
  { nameTr: 'Fizik' },
  { nameTr: 'Fizik Mühendisliği' },
  { nameTr: 'Fizik Öğretmenliği' },
  { nameTr: 'Fizyoterapi ve Rehabilitasyon' },
  { nameTr: 'Fotoğraf' },
  { nameTr: 'Fotoğraf ve Video' },
  { nameTr: 'Fotonik' },
  { nameTr: 'Fransız Dili ve Edebiyatı' },
  { nameTr: 'Fransızca Mütercim ve Tercümanlık' },
  { nameTr: 'Fransızca Öğretmenliği' },
  { nameTr: 'Gastronomi ve Mutfak Sanatları' },
  { nameTr: 'Gayrimenkul Geliştirme ve Yönetimi' },
  { nameTr: 'Gazetecilik' },
  { nameTr: 'Geleneksel Türk Sanatları' },
  { nameTr: 'Gemi İnşaatı ve Gemi Makineleri Mühendisliği' },
  { nameTr: 'Gemi Makineleri İşletme Mühendisliği' },
  { nameTr: 'Gemi ve Deniz Teknolojisi Mühendisliği' },
  { nameTr: 'Gemi ve Yat Tasarımı' },
  { nameTr: 'Genetik ve Biyomühendislik' },
  { nameTr: 'Gerontoloji' },
  { nameTr: 'Gıda Mühendisliği' },
  { nameTr: 'Gıda Teknolojisi' },
  { nameTr: 'Görsel İletişim Tasarımı' },
  { nameTr: 'Görsel Sanatlar' },
  { nameTr: 'Grafik' },
  { nameTr: 'Grafik Sanatlar' },
  { nameTr: 'Grafik Tasarımı' },
  { nameTr: 'Gümrük İşletme' },
  { nameTr: 'Gürcü Dili ve Edebiyatı' },
  { nameTr: 'Halkbilimi' },
  { nameTr: 'Halkla İlişkiler ve Reklamcılık' },
  { nameTr: 'Halkla İlişkiler ve Tanıtım' },
  { nameTr: 'Harita Mühendisliği' },
  { nameTr: 'Hassas Tarım ve Tarımsal Robotlar' },
  { nameTr: 'Havacılık Elektrik ve Elektroniği' },
  { nameTr: 'Havacılık ve Uzay Mühendisliği' },
  { nameTr: 'Havacılık Yönetimi' },
  { nameTr: 'Hayvansal Üretim ve Teknolojileri' },
  { nameTr: 'Hemşirelik' },
  { nameTr: 'Hidrojeoloji Mühendisliği' },
  { nameTr: 'Hindoloji' },
  { nameTr: 'Hititoloji' },
  { nameTr: 'Hukuk' },
  { nameTr: 'Hungaroloji' },
  { nameTr: 'İbrani Dili ve Kültürü' },
  { nameTr: 'İç Mimarlık' },
  { nameTr: 'İç Mimarlık ve Çevre Tasarımı' },
  { nameTr: 'İklim Bilimi ve Meteoroloji Mühendisliği' },
  { nameTr: 'İktisat' },
  { nameTr: 'İlahiyat' },
  { nameTr: 'İletişim' },
  { nameTr: 'İletişim Bilimleri' },
  { nameTr: 'İletişim Tasarımı ve Yönetimi' },
  { nameTr: 'İletişim ve Tasarımı' },
  { nameTr: 'İlköğretim Matematik Öğretmenliği' },
  { nameTr: 'İmalat Mühendisliği' },
  { nameTr: 'İngiliz Dilbilimi' },
  { nameTr: 'İngiliz Dili ve Edebiyatı' },
  { nameTr: 'İngilizce Mütercim ve Tercümanlık' },
  { nameTr: 'İngilizce Öğretmenliği' },
  { nameTr: 'İngilizce, Fransızca Mütercim ve Tercümanlık' },
  { nameTr: 'İnsan Kaynakları Yönetimi' },
  { nameTr: 'İnşaat Mühendisliği' },
  { nameTr: 'İslam İktisadı ve Finans' },
  { nameTr: 'İslami İlimler' },
  { nameTr: 'İspanyol Dili ve Edebiyatı' },
  { nameTr: 'İspanyolca Mütercim ve Tercümanlık' },
  { nameTr: 'İstatistik' },
  { nameTr: 'İstatistik ve Bilgisayar Bilimleri' },
  { nameTr: 'İş Sağlığı ve Güvenliği' },
  { nameTr: 'İşletme' },
  { nameTr: 'İşletme Mühendisliği' },
  { nameTr: 'İşletme ve Yapay Zeka' },
  { nameTr: 'İtalyan Dili ve Edebiyatı' },
  { nameTr: 'Japon Dili ve Edebiyatı' },
  { nameTr: 'Japonca Mütercim ve Tercümanlık' },
  { nameTr: 'Japonca Öğretmenliği' },
  { nameTr: 'Jeofizik Mühendisliği' },
  { nameTr: 'Jeoloji Mühendisliği' },
  { nameTr: 'Kamu Yönetimi' },
  { nameTr: 'Kanatlı Hayvan Yetiştiriciliği' },
  { nameTr: 'Karşılaştırmalı Edebiyat' },
  { nameTr: 'Kentsel Tasarım ve Peyzaj Mimarlığı' },
  { nameTr: 'Kimya' },
  { nameTr: 'Kimya Mühendisliği' },
  { nameTr: 'Kimya Öğretmenliği' },
  { nameTr: 'Kimya-Biyoloji Mühendisliği' },
  { nameTr: 'Klasik Arkeoloji' },
  { nameTr: 'Kontrol ve Otomasyon Mühendisliği' },
  { nameTr: 'Kore Dili ve Edebiyatı' },
  { nameTr: 'Kurgu, Ses ve Görüntü Yönetimi' },
  { nameTr: 'Kuyumculuk ve Mücevher Tasarımı' },
  { nameTr: 'Kültür Varlıklarını Koruma ve Onarım' },
  { nameTr: 'Kültür ve İletişim Bilimleri' },
  { nameTr: 'Küresel Siyaset ve Uluslararası İlişkiler' },
  { nameTr: 'Kürt Dili ve Edebiyatı' },
  { nameTr: 'Latin Dili ve Edebiyatı' },
  { nameTr: 'Leh Dili ve Edebiyatı' },
  { nameTr: 'Lojistik Yönetimi' },
  { nameTr: 'Maden Mühendisliği' },
  { nameTr: 'Makine Mühendisliği' },
  { nameTr: 'Maliye' },
  { nameTr: 'Malzeme Bilimi ve Mühendisliği' },
  { nameTr: 'Malzeme Bilimi ve Nanoteknoloji Mühendisliği' },
  { nameTr: 'Malzeme Bilimi ve Teknolojileri' },
  { nameTr: 'Matematik' },
  { nameTr: 'Matematik Mühendisliği' },
  { nameTr: 'Matematik Öğretmenliği' },
  { nameTr: 'Matematik ve Bilgisayar Bilimleri' },
  { nameTr: 'Medya ve Görsel Sanatlar' },
  { nameTr: 'Medya ve İletişim' },
  { nameTr: 'Mekatronik Mühendisliği' },
  { nameTr: 'Metalurji ve Malzeme Mühendisliği' },
  { nameTr: 'Mimarlık' },
  { nameTr: 'Moda Tasarımı' },
  { nameTr: 'Moleküler Biyoloji ve Genetik' },
  { nameTr: 'Moleküler Biyoteknoloji' },
  { nameTr: 'Muhasebe ve Finans Yönetimi' },
  { nameTr: 'Müzecilik' },
  { nameTr: 'Nanobilim ve Nanoteknoloji' },
  { nameTr: 'Nanoteknoloji Mühendisliği' },
  { nameTr: 'Nükleer Enerji Mühendisliği' },
  { nameTr: 'Odyoloji' },
  { nameTr: 'Okul Öncesi Öğretmenliği' },
  { nameTr: 'Optik ve Akustik Mühendisliği' },
  { nameTr: 'Organik Tarım İşletmeciliği' },
  { nameTr: 'Orman Endüstrisi Mühendisliği' },
  { nameTr: 'Orman Mühendisliği' },
  { nameTr: 'Ortez ve Protez' },
  { nameTr: 'Otel Yöneticiliği' },
  { nameTr: 'Otomotiv Mühendisliği' },
  { nameTr: 'Özel Eğitim Öğretmenliği' },
  { nameTr: 'Paramedik' },
  { nameTr: 'Pazarlama' },
  { nameTr: 'Perfüzyon' },
  { nameTr: 'Petrol ve Doğalgaz Mühendisliği' },
  { nameTr: 'Peyzaj Mimarlığı' },
  { nameTr: 'Pilotaj' },
  { nameTr: 'Polimer Malzeme Mühendisliği' },
  { nameTr: 'Politika ve Ekonomi' },
  { nameTr: 'Protohistorya ve Ön Asya Arkeolojisi' },
  { nameTr: 'Psikoloji' },
  { nameTr: 'Radyo, Televizyon ve Sinema' },
  { nameTr: 'Raylı Sistemler Mühendisliği' },
  { nameTr: 'Rehberlik ve Psikolojik Danışmanlık' },
  { nameTr: 'Reklam Tasarımı ve İletişimi' },
  { nameTr: 'Reklamcılık' },
  { nameTr: 'Rekreasyon' },
  { nameTr: 'Rekreasyon Yönetimi' },
  { nameTr: 'Rus Dili ve Edebiyatı' },
  { nameTr: 'Rusça Mütercim ve Tercümanlık' },
  { nameTr: 'Saç ve Güzellik Uygulamaları' },
  { nameTr: 'Sağlık Yönetimi' },
  { nameTr: 'Sanat Tarihi' },
  { nameTr: 'Sanat ve Kültür Yönetimi' },
  { nameTr: 'Sermaye Piyasası' },
  { nameTr: 'Seyahat İşletmeciliği' },
  { nameTr: 'Seyahat İşletmeciliği ve Turizm Rehberliği' },
  { nameTr: 'Sınıf Öğretmenliği' },
  { nameTr: 'Sırp Dili ve Edebiyatı' },
  { nameTr: 'Siber Güvenlik Mühendisliği' },
  { nameTr: 'Sigortacılık' },
  { nameTr: 'Sigortacılık ve Aktüerya Bilimleri' },
  { nameTr: 'Sigortacılık ve Risk Yönetimi' },
  { nameTr: 'Sigortacılık ve Sosyal Güvenlik' },
  { nameTr: 'Sinema ve Dijital Medya' },
  { nameTr: 'Sinema ve Televizyon' },
  { nameTr: 'Sinoloji' },
  { nameTr: 'Siyaset Bilimi' },
  { nameTr: 'Siyaset Bilimi ve Kamu Yönetimi' },
  { nameTr: 'Siyaset Bilimi ve Uluslararası İlişkiler' },
  { nameTr: 'Sosyal Bilgiler Öğretmenliği' },
  { nameTr: 'Sosyal Hizmet' },
  { nameTr: 'Sosyoloji' },
  { nameTr: 'Su Bilimleri ve Mühendisliği' },
  { nameTr: 'Su Ürünleri Endüstrisi Mühendisliği' },
  { nameTr: 'Su Ürünleri Mühendisliği' },
  { nameTr: 'Sümeroloji' },
  { nameTr: 'Süryani Dili ve Edebiyatı' },
  { nameTr: 'Süt Teknolojisi' },
  { nameTr: 'Şehir ve Bölge Planlama' },
  { nameTr: 'Takı Tasarımı ve İmalatı' },
  { nameTr: 'Tapu Kadastro' },
  { nameTr: 'Tarım Ekonomisi' },
  { nameTr: 'Tarım Makineleri ve Teknolojileri Mühendisliği' },
  { nameTr: 'Tarım Ticareti ve İşletmeciliği' },
  { nameTr: 'Tarımsal Biyoteknoloji' },
  { nameTr: 'Tarımsal Genetik Mühendisliği' },
  { nameTr: 'Tarımsal Yapılar ve Sulama' },
  { nameTr: 'Tarih' },
  { nameTr: 'Tarih Öğretmenliği' },
  { nameTr: 'Tarih Öncesi Arkeolojisi' },
  { nameTr: 'Tarla Bitkileri' },
  { nameTr: 'Teknoloji ve Bilgi Yönetimi' },
  { nameTr: 'Tekstil Mühendisliği' },
  { nameTr: 'Tekstil Tasarımı' },
  { nameTr: 'Tekstil ve Moda Tasarımı' },
  { nameTr: 'Televizyon Haberciliği ve Programcılığı' },
  { nameTr: 'Tıp' },
  { nameTr: 'Tiyatro Eleştirmenliği ve Dramaturji' },
  { nameTr: 'Tohum Bilimi ve Teknolojisi' },
  { nameTr: 'Toprak Bilimi ve Bitki Besleme' },
  { nameTr: 'Turizm İşletmeciliği' },
  { nameTr: 'Turizm Rehberliği' },
  { nameTr: 'Turizm ve Otel İşletmeciliği' },
  { nameTr: 'Türk Dili ve Edebiyatı' },
  { nameTr: 'Türk Dili ve Edebiyatı Öğretmenliği' },
  { nameTr: 'Türk Halkbilimi' },
  { nameTr: 'Türk İslam Arkeolojisi' },
  { nameTr: 'Türkçe Öğretmenliği' },
  { nameTr: 'Tütün Eksperliği' },
  { nameTr: 'Uçak Bakım ve Onarım' },
  { nameTr: 'Uçak Elektrik ve Elektroniği' },
  { nameTr: 'Uçak Gövde ve Motor Bakımı' },
  { nameTr: 'Uçak Mühendisliği' },
  { nameTr: 'Ukrayna Dili ve Edebiyatı' },
  { nameTr: 'Uluslararası Finans' },
  { nameTr: 'Uluslararası Finans ve Bankacılık' },
  { nameTr: 'Uluslararası Girişimcilik' },
  { nameTr: 'Uluslararası İlişkiler' },
  { nameTr: 'Uluslararası İşletme Yönetimi' },
  { nameTr: 'Uluslararası Ticaret' },
  { nameTr: 'Uluslararası Ticaret ve Finansman' },
  { nameTr: 'Uluslararası Ticaret ve İşletmecilik' },
  { nameTr: 'Uluslararası Ticaret ve Lojistik' },
  { nameTr: 'Urdu Dili ve Edebiyatı' },
  { nameTr: 'Uzay Bilimleri ve Teknolojileri' },
  { nameTr: 'Uzay Mühendisliği' },
  { nameTr: 'Veri Bilimi ve Analitiği' },
  { nameTr: 'Veteriner' },
  { nameTr: 'Yaban Hayatı Ekolojisi ve Yönetimi' },
  { nameTr: 'Yapay Zeka Mühendisliği' },
  { nameTr: 'Yapay Zeka ve Makine Öğrenmesi' },
  { nameTr: 'Yapay Zeka ve Veri Mühendisliği' },
  { nameTr: 'Yazılım Geliştirme' },
  { nameTr: 'Yazılım Mühendisliği' },
  { nameTr: 'Yeni Medya' },
  { nameTr: 'Yeni Medya ve İletişim' },
  { nameTr: 'Yerel Yönetimler' },
  { nameTr: 'Yiyecek ve İçecek İşletmeciliği' },
  { nameTr: 'Yönetim Bilişim Sistemleri' },
  { nameTr: 'Yunan Dili ve Edebiyatı' },
  { nameTr: 'Zaza Dili ve Edebiyatı' },
  { nameTr: 'Zootekni' },
];

/**
 * The published constant, frozen to the same depth and for the same reason as the üniversite
 * list — `university.data.ts` carries the full argument, and it is not restated here so the two
 * cannot drift into two explanations. In short: freezing the array alone leaves every row
 * writable, and this array is served by reference behind a one-day CDN window.
 *
 * **Its order is the PUBLISHED render order** — Turkish alphabetical, inherited from the
 * artefact, asserted (never re-sorted) by `reference-lists.spec.ts`.
 */
export const DEPARTMENTS: readonly DepartmentDto[] = Object.freeze(
  DEPARTMENT_ROWS.map((row) => Object.freeze(row)),
);
